#include "prts/antidebug.hpp"
extern "C" {
#include "Zydis.h"
}
#include <algorithm>
#include <array>
#include <cctype>
#include <cstring>
#include <future>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string_view>
#include <tuple>
namespace prts { namespace {
std::optional<std::size_t> rvaoff(const PeInfo&pe,std::uint32_t rva,std::size_t n){if(rva<pe.headers_size&&rva<n)return std::size_t(rva);for(const auto&s:pe.sections){auto span=std::max(s.vsize,s.raw_size);if(rva>=s.rva&&std::uint64_t(rva)<std::uint64_t(s.rva)+span){auto delta=std::uint64_t(rva)-s.rva;if(delta>=s.raw_size)return{};auto o=std::uint64_t(s.raw_offset)+delta;if(o<n)return std::size_t(o);}}return{};}
std::optional<std::uint64_t> fileoff(const PeInfo&pe,std::uint32_t rva){for(const auto&s:pe.sections){if(rva>=s.rva&&std::uint64_t(rva)<std::uint64_t(s.rva)+s.raw_size)return std::uint64_t(s.raw_offset)+(rva-s.rva);}if(rva<pe.headers_size)return rva;return{};}
ZydisRegister large(ZydisRegister r){return r==ZYDIS_REGISTER_NONE?r:ZydisRegisterGetLargestEnclosing(ZYDIS_MACHINE_MODE_LONG_64,r);}
struct FuncRange{std::uint32_t begin=0,end=0;};
FuncRange runtime_func(const PeInfo&pe,std::uint32_t rva){for(const auto&f:pe.exception.runtime_functions)if(f.begin_rva<=rva&&rva<f.end_rva)return{f.begin_rva,f.end_rva};return{};}
bool executable_rva(const PeInfo&pe,std::uint32_t rva){for(const auto&s:pe.sections){if(!(s.characteristics&0x20000000u))continue;auto span=std::max(s.vsize,s.raw_size);if(rva>=s.rva&&std::uint64_t(rva)<std::uint64_t(s.rva)+span)return true;}return false;}
struct Decoded{std::uint32_t rva=0;ZydisDecodedInstruction zi{};std::array<ZydisDecodedOperand,ZYDIS_MAX_OPERAND_COUNT>ops{};};
std::vector<Decoded> decode_range(std::span<const std::uint8_t>d,const PeInfo&pe,FuncRange f){std::vector<Decoded>out;if(!f.end||f.end<=f.begin)return out;ZydisDecoder dec;if(!ZYAN_SUCCESS(ZydisDecoderInit(&dec,ZYDIS_MACHINE_MODE_LONG_64,ZYDIS_STACK_WIDTH_64)))return out;auto cur=f.begin;while(cur<f.end&&out.size()<8192){auto o=rvaoff(pe,cur,d.size());if(!o||*o>=d.size())break;Decoded x;x.rva=cur;auto avail=std::min<std::size_t>(d.size()-*o,f.end-cur);if(!ZYAN_SUCCESS(ZydisDecoderDecodeFull(&dec,d.data()+*o,avail,&x.zi,x.ops.data()))||!x.zi.length)break;out.push_back(x);cur+=x.zi.length;}return out;}
struct ImportedCall{std::string module,name,transfer;std::uint32_t callsite=0,func_begin=0,func_end=0,iat_rva=0;};
std::span<const std::uint8_t> raw_runtime_function(std::span<const std::uint8_t>d,const PeInfo&pe,const PeRuntimeFunction&rf){if(rf.end_rva<=rf.begin_rva)return{};auto b=rvaoff(pe,rf.begin_rva,d.size()),e=rvaoff(pe,rf.end_rva-1,d.size());if(!b||!e||*e<*b||*e-*b+1!=rf.end_rva-rf.begin_rva)return{};return d.subspan(*b,*e-*b+1);}
bool import_transfer_candidate(std::span<const std::uint8_t>s,std::uint32_t begin,const std::map<std::uint32_t,std::pair<std::string,std::string>>&iat,const std::map<std::uint32_t,std::uint32_t>&thunks){if(s.empty())return true;for(std::size_t i=0;i<s.size();++i){const auto op=s[i];if((op==0xe8||op==0xe9)&&i+5<=s.size()){std::int32_t rel=0;std::memcpy(&rel,s.data()+i+1,4);auto t=std::int64_t(begin)+static_cast<std::int64_t>(i)+5+rel;if(t>=0&&t<=0xffffffffll&&thunks.count(static_cast<std::uint32_t>(t)))return true;}else if(op==0xeb&&i+2<=s.size()){auto rel=static_cast<std::int8_t>(s[i+1]);auto t=std::int64_t(begin)+static_cast<std::int64_t>(i)+2+rel;if(t>=0&&t<=0xffffffffll&&thunks.count(static_cast<std::uint32_t>(t)))return true;}else if(op==0xff&&i+2<=s.size()){const auto m=s[i+1];if((m&0xf8)==0xd0)return true;if((m==0x15||m==0x25)&&i+6<=s.size()){std::int32_t rel=0;std::memcpy(&rel,s.data()+i+2,4);auto t=std::int64_t(begin)+static_cast<std::int64_t>(i)+6+rel;if(t>=0&&t<=0xffffffffll&&iat.count(static_cast<std::uint32_t>(t)))return true;}}}return false;}
bool interesting_api(std::string_view n){static constexpr std::array<std::string_view,35>a={"IsDebuggerPresent","CheckRemoteDebuggerPresent","NtQueryInformationProcess","ZwQueryInformationProcess","NtSetInformationThread","ZwSetInformationThread","NtQuerySystemInformation","ZwQuerySystemInformation","NtQueryObject","ZwQueryObject","NtYieldExecution","NtCreateThreadEx","GetThreadContext","Wow64GetThreadContext","NtGetContextThread","DebugBreak","RaiseException","CloseHandle","AddVectoredExceptionHandler","SetUnhandledExceptionFilter","OutputDebugStringA","OutputDebugStringW","QueryPerformanceCounter","GetTickCount","GetTickCount64","timeGetTime","FindWindowA","FindWindowW","EnumWindows","CreateToolhelp32Snapshot","Process32FirstA","Process32FirstW","GetProcAddress","lstrcmpW","lstrcmpiW"};return std::find(a.begin(),a.end(),n)!=a.end()||n=="Process32NextA"||n=="Process32NextW"||n=="EnumProcesses";}
std::vector<ImportedCall> find_import_calls(std::span<const std::uint8_t>d,const PeInfo&pe){
    std::vector<ImportedCall>out;if(!pe.valid||!pe.pe64)return out;
    std::map<std::uint32_t,std::pair<std::string,std::string>>iat;constexpr std::uint32_t w=8;for(const auto&m:pe.imports)for(std::size_t i=0;i<m.functions.size();++i){const auto&f=m.functions[i];if(!f.by_ordinal&&interesting_api(f.name))iat[m.iat_rva+static_cast<std::uint32_t>(i)*w]={m.name,f.name};}if(iat.empty())return out;
    std::map<std::uint32_t,std::uint32_t>thunk_to_iat;
    for(const auto&s:pe.sections){if(!(s.characteristics&0x20000000u)||!s.raw_size||std::uint64_t(s.raw_offset)+s.raw_size>d.size())continue;for(std::size_t q=0;q+6<=s.raw_size;++q){auto o=std::size_t(s.raw_offset)+q;if(d[o]!=0xff||d[o+1]!=0x25)continue;std::int32_t disp=0;std::memcpy(&disp,d.data()+o+2,4);auto t=std::int64_t(s.rva+q+6)+disp;if(t>=0&&t<=0xffffffffll&&iat.count(static_cast<std::uint32_t>(t)))thunk_to_iat[s.rva+static_cast<std::uint32_t>(q)]=static_cast<std::uint32_t>(t);}}
    std::set<std::uint32_t>seen;
    auto emit=[&](std::uint32_t cr,std::uint32_t ir,std::string transfer){auto f=runtime_func(pe,cr);if(!f.end||!seen.insert(cr).second)return;auto nm=iat.find(ir);if(nm==iat.end())return;out.push_back({nm->second.first,nm->second.second,std::move(transfer),cr,f.begin,f.end,ir});};
    auto volatile_reg=[](ZydisRegister r){r=large(r);return r==ZYDIS_REGISTER_RAX||r==ZYDIS_REGISTER_RCX||r==ZYDIS_REGISTER_RDX||r==ZYDIS_REGISTER_R8||r==ZYDIS_REGISTER_R9||r==ZYDIS_REGISTER_R10||r==ZYDIS_REGISTER_R11;};
    // Normalize direct IAT calls, relative calls through import thunks, tail-jumps and register-indirect IAT calls.
    for(const auto&rf:pe.exception.runtime_functions){
        if(!import_transfer_candidate(raw_runtime_function(d,pe,rf),rf.begin_rva,iat,thunk_to_iat))continue;
        auto ins=decode_range(d,pe,{rf.begin_rva,rf.end_rva});std::map<ZydisRegister,std::uint32_t>alias;
        for(const auto&x:ins){
            bool emitted_call=false;
            if((x.zi.meta.category==ZYDIS_CATEGORY_CALL||x.zi.meta.category==ZYDIS_CATEGORY_UNCOND_BR)&&x.zi.operand_count_visible>=1){
                const auto&q=x.ops[0];std::uint32_t ir=0;
                if(q.type==ZYDIS_OPERAND_TYPE_MEMORY&&q.mem.index==ZYDIS_REGISTER_NONE&&large(q.mem.base)==ZYDIS_REGISTER_RIP){auto disp=q.mem.disp.has_displacement?q.mem.disp.value:0;auto t=std::int64_t(x.rva+x.zi.length)+disp;if(t>=0&&t<=0xffffffffll&&iat.count(static_cast<std::uint32_t>(t)))ir=static_cast<std::uint32_t>(t);}
                else if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&q.imm.is_relative&&(x.zi.meta.category==ZYDIS_CATEGORY_CALL||x.zi.meta.category==ZYDIS_CATEGORY_UNCOND_BR)){auto t=std::int64_t(x.rva+x.zi.length)+q.imm.value.s;if(t>=0&&t<=0xffffffffll){auto it=thunk_to_iat.find(static_cast<std::uint32_t>(t));if(it!=thunk_to_iat.end())ir=it->second;}}
                else if(q.type==ZYDIS_OPERAND_TYPE_REGISTER&&x.zi.meta.category==ZYDIS_CATEGORY_CALL){auto it=alias.find(large(q.reg.value));if(it!=alias.end())ir=it->second;}
                if(ir){std::string transfer;if(q.type==ZYDIS_OPERAND_TYPE_REGISTER)transfer="call_iat_register";else if(x.zi.meta.category==ZYDIS_CATEGORY_UNCOND_BR&&q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE)transfer="tail_jmp_thunk";else if(x.zi.meta.category==ZYDIS_CATEGORY_UNCOND_BR)transfer="tail_jmp_iat";else if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE)transfer="call_thunk";else transfer="call_iat";emit(x.rva,ir,std::move(transfer));emitted_call=x.zi.meta.category==ZYDIS_CATEGORY_CALL;}
            }
            if(x.zi.operand_count_visible&&x.ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)){
                auto dst=large(x.ops[0].reg.value);std::optional<std::uint32_t>v;
                if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=alias.find(large(q.reg.value));if(it!=alias.end())v=it->second;}else if(q.type==ZYDIS_OPERAND_TYPE_MEMORY&&q.mem.index==ZYDIS_REGISTER_NONE&&large(q.mem.base)==ZYDIS_REGISTER_RIP){auto disp=q.mem.disp.has_displacement?q.mem.disp.value:0;auto t=std::int64_t(x.rva+x.zi.length)+disp;if(t>=0&&t<=0xffffffffll&&iat.count(static_cast<std::uint32_t>(t)))v=static_cast<std::uint32_t>(t);}}
                if(v)alias[dst]=*v;else alias.erase(dst);
            }
            if(emitted_call){for(auto it=alias.begin();it!=alias.end();){if(volatile_reg(it->first))it=alias.erase(it);else ++it;}}
        }
    }
    std::sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.callsite<b.callsite;});return out;
}
std::optional<std::uint64_t> scalar_arg(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&c,int arg){if(arg<0||arg>3||!c.func_end)return{};auto ins=decode_range(d,pe,{c.func_begin,c.func_end});if(ins.empty())return{};auto want=std::array<ZydisRegister,4>{ZYDIS_REGISTER_RCX,ZYDIS_REGISTER_RDX,ZYDIS_REGISTER_R8,ZYDIS_REGISTER_R9}[arg];auto cur=large(want);std::size_t idx=ins.size();for(std::size_t i=0;i<ins.size();++i)if(ins[i].rva==c.callsite){idx=i;break;}if(idx==ins.size())return{};std::size_t seen=0;for(std::size_t z=idx;z-->0&&seen<96;){const auto&x=ins[z];++seen;if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)continue;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){cur=large(q.reg.value);continue;}if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE){auto v=q.imm.value.u;if(x.ops[0].size==64&&q.size==32)v=static_cast<std::uint64_t>(static_cast<std::int64_t>(static_cast<std::int32_t>(v)));return v;}}if(x.zi.mnemonic==ZYDIS_MNEMONIC_XOR&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[1].reg.value)==cur)return 0;return{};}return{};}
struct PointerArg{std::string source;std::uint32_t rva=0;};
std::optional<PointerArg> pointer_rva_arg(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&c,int arg){if(arg<0||arg>3||!c.func_end)return{};auto ins=decode_range(d,pe,{c.func_begin,c.func_end});if(ins.empty())return{};auto cur=large(std::array<ZydisRegister,4>{ZYDIS_REGISTER_RCX,ZYDIS_REGISTER_RDX,ZYDIS_REGISTER_R8,ZYDIS_REGISTER_R9}[arg]);std::size_t idx=ins.size();for(std::size_t i=0;i<ins.size();++i)if(ins[i].rva==c.callsite){idx=i;break;}if(idx==ins.size())return{};std::int64_t add=0;std::size_t seen=0;for(std::size_t z=idx;z-->0&&seen<128;){const auto&x=ins[z];++seen;if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)continue;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){cur=large(q.reg.value);continue;}if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE){auto va=q.imm.value.u;if(x.ops[0].size==64&&q.size==32)va=static_cast<std::uint64_t>(static_cast<std::int64_t>(static_cast<std::int32_t>(va)));auto sva=static_cast<std::int64_t>(va)+add;if(sva<0||static_cast<std::uint64_t>(sva)<pe.image_base||static_cast<std::uint64_t>(sva)-pe.image_base>0xffffffffull)return{};return PointerArg{"IMM_IMAGE_VA",static_cast<std::uint32_t>(static_cast<std::uint64_t>(sva)-pe.image_base)};}if(q.type==ZYDIS_OPERAND_TYPE_MEMORY&&q.mem.index==ZYDIS_REGISTER_NONE&&large(q.mem.base)==ZYDIS_REGISTER_RIP){auto disp=q.mem.disp.has_displacement?q.mem.disp.value:0;auto slot=std::int64_t(x.rva+x.zi.length)+disp;if(slot<0||slot>0xffffffffll)return{};auto so=rvaoff(pe,static_cast<std::uint32_t>(slot),d.size());if(!so||*so+8>d.size())return{};std::uint64_t va=0;std::memcpy(&va,d.data()+*so,8);auto sva=static_cast<std::int64_t>(va)+add;if(sva<0||static_cast<std::uint64_t>(sva)<pe.image_base||static_cast<std::uint64_t>(sva)-pe.image_base>0xffffffffull)return{};return PointerArg{"RIP_GLOBAL_PTR",static_cast<std::uint32_t>(static_cast<std::uint64_t>(sva)-pe.image_base)};}return{};}if(x.zi.mnemonic==ZYDIS_MNEMONIC_LEA&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY){const auto&m=x.ops[1].mem;if(m.index!=ZYDIS_REGISTER_NONE)return{};auto disp=m.disp.has_displacement?m.disp.value:0;if(large(m.base)==ZYDIS_REGISTER_RIP){auto r=std::int64_t(x.rva+x.zi.length)+disp+add;if(r<0||r>0xffffffffll)return{};return PointerArg{"RIP_GLOBAL",static_cast<std::uint32_t>(r)};}if(m.base!=ZYDIS_REGISTER_NONE){cur=large(m.base);add+=disp;continue;}return{};}if((x.zi.mnemonic==ZYDIS_MNEMONIC_ADD||x.zi.mnemonic==ZYDIS_MNEMONIC_SUB)&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_IMMEDIATE){auto v=x.ops[1].imm.value.s;add+=x.zi.mnemonic==ZYDIS_MNEMONIC_ADD?v:-v;continue;}return{};}return{};}
struct AsciiArg{std::string value,source;std::uint32_t rva=0;std::uint64_t offset=0;};
std::optional<AsciiArg> ascii_at_rva(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t rva,std::string source){auto o=rvaoff(pe,rva,d.size());if(!o)return{};std::string v;v.reserve(64);for(std::size_t i=0;i<128&&*o+i<d.size();++i){auto b=d[*o+i];if(!b){if(v.empty())return{};return AsciiArg{std::move(v),std::move(source),rva,*o};}if(b<0x20||b>0x7e)return{};v.push_back(static_cast<char>(b));}return{};}
std::optional<AsciiArg> pointer_ascii_arg(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&c,int arg){auto p=pointer_rva_arg(d,pe,c,arg);if(!p)return{};return ascii_at_rva(d,pe,p->rva,p->source);}
struct Utf16Arg{std::string value,source;std::uint32_t rva=0;std::uint64_t offset=0;};
std::optional<Utf16Arg> utf16_ascii_at_rva(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t rva,std::string source){auto o=rvaoff(pe,rva,d.size());if(!o)return{};std::string v;v.reserve(64);for(std::size_t i=0;i<128&&*o+2*i+1<d.size();++i){auto lo=d[*o+2*i],hi=d[*o+2*i+1];if(!lo&&!hi){if(v.empty())return{};return Utf16Arg{std::move(v),std::move(source),rva,*o};}if(hi||lo<0x20||lo>0x7e)return{};v.push_back(static_cast<char>(lo));}return{};}
std::optional<Utf16Arg> pointer_utf16_ascii_arg(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&c,int arg){auto p=pointer_rva_arg(d,pe,c,arg);if(!p)return{};return utf16_ascii_at_rva(d,pe,p->rva,p->source);}

std::optional<std::uint64_t> stack_scalar_arg(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&c,int arg){if(arg<4||!c.func_end)return{};auto ins=decode_range(d,pe,{c.func_begin,c.func_end});std::size_t idx=ins.size();for(std::size_t i=0;i<ins.size();++i)if(ins[i].rva==c.callsite){idx=i;break;}if(idx==ins.size())return{};const auto target=std::int64_t(0x20+8*(arg-4));std::map<ZydisRegister,std::uint64_t>regs;std::size_t seen=0;for(std::size_t z=idx;z-->0&&seen<160;){const auto&x=ins[z];++seen;if(x.zi.meta.category==ZYDIS_CATEGORY_CALL)break;if(x.zi.operand_count_visible>=1&&x.ops[0].type==ZYDIS_OPERAND_TYPE_MEMORY&&(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)&&x.ops[0].mem.index==ZYDIS_REGISTER_NONE&&large(x.ops[0].mem.base)==ZYDIS_REGISTER_RSP&&(x.ops[0].mem.disp.has_displacement?x.ops[0].mem.disp.value:0)==target){if(x.zi.mnemonic!=ZYDIS_MNEMONIC_MOV||x.zi.operand_count_visible<2)return{};const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE)return q.imm.value.u;if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=regs.find(large(q.reg.value));if(it!=regs.end())return it->second;}return{};}if(x.zi.operand_count_visible&&x.ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)){auto dst=large(x.ops[0].reg.value);std::optional<std::uint64_t>v;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE)v=q.imm.value.u;else if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=regs.find(large(q.reg.value));if(it!=regs.end())v=it->second;}}else if(x.zi.mnemonic==ZYDIS_MNEMONIC_XOR&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[1].reg.value)==dst)v=0;if(v)regs[dst]=*v;else regs.erase(dst);}}return{};}
bool postcall_return_compare_branch(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&c,std::uint64_t value,std::uint32_t&cmp_rva,std::uint32_t&branch_rva){if(!c.func_end)return false;auto ins=decode_range(d,pe,{c.func_begin,c.func_end});std::size_t idx=ins.size();for(std::size_t i=0;i<ins.size();++i)if(ins[i].rva==c.callsite){idx=i;break;}if(idx==ins.size())return false;for(std::size_t i=idx+1;i<ins.size()&&i<=idx+8;++i){const auto&x=ins[i];if(x.zi.meta.category==ZYDIS_CATEGORY_CALL||x.zi.meta.category==ZYDIS_CATEGORY_RET)return false;if(x.zi.mnemonic==ZYDIS_MNEMONIC_CMP&&x.zi.operand_count_visible>=2){bool ret=false;std::optional<std::uint64_t>imm;for(std::uint8_t k=0;k<x.zi.operand_count_visible;++k){if(x.ops[k].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[k].reg.value)==ZYDIS_REGISTER_RAX)ret=true;if(x.ops[k].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&!x.ops[k].imm.is_relative)imm=x.ops[k].imm.value.u;}if(ret&&imm&&static_cast<std::uint32_t>(*imm)==static_cast<std::uint32_t>(value)){cmp_rva=x.rva;for(std::size_t j=i+1;j<ins.size()&&j<=i+3;++j)if(ins[j].zi.meta.category==ZYDIS_CATEGORY_COND_BR){branch_rva=ins[j].rva;return true;}return false;}}}return false;}
struct StackArg{ZydisRegister base=ZYDIS_REGISTER_NONE;std::int64_t disp=0;};
std::optional<StackArg> stack_pointer_arg(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&c,int arg){if(arg<0||arg>3||!c.func_end)return{};auto ins=decode_range(d,pe,{c.func_begin,c.func_end});auto cur=large(std::array<ZydisRegister,4>{ZYDIS_REGISTER_RCX,ZYDIS_REGISTER_RDX,ZYDIS_REGISTER_R8,ZYDIS_REGISTER_R9}[arg]);std::size_t idx=ins.size();for(std::size_t i=0;i<ins.size();++i)if(ins[i].rva==c.callsite){idx=i;break;}if(idx==ins.size())return{};std::int64_t add=0;std::size_t seen=0;for(std::size_t z=idx;z-->0&&seen<128;){const auto&x=ins[z];++seen;if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)continue;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){cur=large(x.ops[1].reg.value);continue;}if(x.zi.mnemonic==ZYDIS_MNEMONIC_LEA&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY&&x.ops[1].mem.index==ZYDIS_REGISTER_NONE){auto b=large(x.ops[1].mem.base);auto disp=x.ops[1].mem.disp.has_displacement?x.ops[1].mem.disp.value:0;if(b==ZYDIS_REGISTER_RBP||b==ZYDIS_REGISTER_RSP)return StackArg{b,disp+add};if(b!=ZYDIS_REGISTER_NONE){cur=b;add+=disp;continue;}}if((x.zi.mnemonic==ZYDIS_MNEMONIC_ADD||x.zi.mnemonic==ZYDIS_MNEMONIC_SUB)&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_IMMEDIATE){auto v=x.ops[1].imm.value.s;add+=x.zi.mnemonic==ZYDIS_MNEMONIC_ADD?v:-v;continue;}return{};}return{};}
bool argument_loads_stack_field(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&c,int arg,const StackArg&ref,std::int64_t field_offset,std::uint32_t*load_rva=nullptr){if(arg<0||arg>3||!c.func_end)return false;auto ins=decode_range(d,pe,{c.func_begin,c.func_end});auto cur=large(std::array<ZydisRegister,4>{ZYDIS_REGISTER_RCX,ZYDIS_REGISTER_RDX,ZYDIS_REGISTER_R8,ZYDIS_REGISTER_R9}[arg]);std::size_t idx=ins.size();for(std::size_t i=0;i<ins.size();++i)if(ins[i].rva==c.callsite){idx=i;break;}if(idx==ins.size())return false;std::size_t seen=0;for(std::size_t z=idx;z-->0&&seen<128;){const auto&x=ins[z];++seen;if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)continue;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){cur=large(q.reg.value);continue;}if(q.type==ZYDIS_OPERAND_TYPE_MEMORY&&q.mem.index==ZYDIS_REGISTER_NONE&&large(q.mem.base)==ref.base&&q.mem.disp.has_displacement&&q.mem.disp.value==ref.disp+field_offset){if(load_rva)*load_rva=x.rva;return true;}}return false;}return false;}

struct DebugRegisterUse{std::uint32_t count=0,first_rva=0;std::string names;};
DebugRegisterUse debug_register_context_use(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&c){DebugRegisterUse out;auto ref=stack_pointer_arg(d,pe,c,1);if(!ref)return out;auto ins=decode_range(d,pe,{c.func_begin,c.func_end});std::size_t idx=ins.size();for(std::size_t i=0;i<ins.size();++i)if(ins[i].rva==c.callsite){idx=i;break;}if(idx==ins.size())return out;static constexpr std::array<std::pair<std::int64_t,const char*>,6>dr={{{0x48,"Dr0"},{0x50,"Dr1"},{0x58,"Dr2"},{0x60,"Dr3"},{0x68,"Dr6"},{0x70,"Dr7"}}};std::set<std::string>seen;for(std::size_t i=idx+1;i<ins.size()&&i<=idx+96;++i){const auto&x=ins[i];for(std::uint8_t k=0;k<x.zi.operand_count_visible;++k){const auto&o=x.ops[k];if(o.type!=ZYDIS_OPERAND_TYPE_MEMORY||o.mem.index!=ZYDIS_REGISTER_NONE||large(o.mem.base)!=ref->base||!o.mem.disp.has_displacement)continue;for(auto [off,name]:dr)if(o.mem.disp.value==ref->disp+off){if(seen.insert(name).second){if(!out.first_rva)out.first_rva=x.rva;++out.count;}}}if(x.zi.meta.category==ZYDIS_CATEGORY_RET)break;}for(const auto&n:seen){if(!out.names.empty())out.names+=",";out.names+=n;}return out;}
bool postcall_conditional(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&c){if(!c.func_end)return false;auto ins=decode_range(d,pe,{c.func_begin,c.func_end});std::size_t idx=ins.size();for(std::size_t i=0;i<ins.size();++i)if(ins[i].rva==c.callsite){idx=i;break;}if(idx==ins.size())return false;bool ret_test=false;for(std::size_t i=idx+1;i<ins.size()&&i<=idx+7;++i){const auto&x=ins[i];if(x.zi.mnemonic==ZYDIS_MNEMONIC_TEST||x.zi.mnemonic==ZYDIS_MNEMONIC_CMP){for(std::uint8_t k=0;k<x.zi.operand_count_visible;++k)if(x.ops[k].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[k].reg.value)==ZYDIS_REGISTER_RAX)ret_test=true;}if(ret_test&&x.zi.meta.category==ZYDIS_CATEGORY_COND_BR)return true;if(x.zi.meta.category==ZYDIS_CATEGORY_CALL||x.zi.meta.category==ZYDIS_CATEGORY_RET)break;}return false;}
bool function_has_imm(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&c,std::initializer_list<std::uint64_t>vals){if(!c.func_end)return false;auto ins=decode_range(d,pe,{c.func_begin,c.func_end});for(const auto&x:ins)for(std::uint8_t k=0;k<x.zi.operand_count_visible;++k)if(x.ops[k].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&!x.ops[k].imm.is_relative)for(auto v:vals)if(x.ops[k].imm.value.u==v)return true;return false;}
Finding mk(std::string variant,std::string state,double conf,std::string category,std::string method,std::uint32_t rva,std::uint32_t func,std::string api={}){Finding f;f.kind="anti-analysis";f.family="Anti-debug";f.variant=std::move(variant);f.state=std::move(state);f.confidence=conf;f.fields["category"]=std::move(category);f.fields["method"]=std::move(method);f.fields["malicious_intent"]="NOT_INFERRED";if(rva)f.fields["callsite_rva"]="0x"+[] (std::uint32_t v){std::ostringstream o;o<<std::hex<<v;return o.str();}(rva);if(func)f.fields["function_rva"]="0x"+[] (std::uint32_t v){std::ostringstream o;o<<std::hex<<v;return o.str();}(func);if(!api.empty())f.fields["api"]=std::move(api);return f;}
void add_call_range(Finding&f,const PeInfo&pe,std::uint32_t rva,std::uint32_t size=6){if(auto o=fileoff(pe,rva))f.ranges.push_back({*o,size,"anti-debug callsite"});}
void annotate_import_call(Finding&f,const PeInfo&pe,const ImportedCall&c){f.fields["module"]=c.module;f.fields["transfer"]=c.transfer;add_call_range(f,pe,c.callsite);}
std::optional<std::string> canonical_debugger_name(std::string_view in){static constexpr std::array<std::string_view,10>names={"x64dbg","x32dbg","ollydbg","windbg","immunity debugger","cheat engine","process hacker","ida64","idaq","ghidra"};std::string x;for(unsigned char c:in)x.push_back(static_cast<char>(std::tolower(c)));for(auto n:names)if(x==n)return std::string(n);return{};}
struct NameHit{std::uint64_t off=0;std::string name;};
std::vector<NameHit> debugger_name_hits(std::span<const std::uint8_t>d){static constexpr std::array<std::string_view,10>names={"x64dbg","x32dbg","ollydbg","windbg","immunity debugger","cheat engine","process hacker","ida64","idaq","ghidra"};std::array<std::optional<std::size_t>,10>a{},w{};std::size_t left=20;auto test=[&](std::size_t i,std::size_t n){auto s=names[n];if(!a[n]&&i+s.size()<=d.size()){bool ok=true;for(std::size_t k=1;k<s.size();++k){auto c=d[i+k];if(c>='A'&&c<='Z')c=std::uint8_t(c+32);if(c!=static_cast<std::uint8_t>(s[k])){ok=false;break;}}if(ok){a[n]=i;--left;}}if(!w[n]&&i+2*s.size()<=d.size()){bool ok=true;for(std::size_t k=0;k<s.size();++k){auto c=d[i+2*k];if(c>='A'&&c<='Z')c=std::uint8_t(c+32);if(d[i+2*k+1]!=0||c!=static_cast<std::uint8_t>(s[k])){ok=false;break;}}if(ok){w[n]=i;--left;}}};for(std::size_t i=0;i<d.size()&&left;++i){auto c=d[i];if(c>='A'&&c<='Z')c=std::uint8_t(c+32);switch(c){case 'x':test(i,0);test(i,1);break;case 'o':test(i,2);break;case 'w':test(i,3);break;case 'i':test(i,4);test(i,7);test(i,8);break;case 'c':test(i,5);break;case 'p':test(i,6);break;case 'g':test(i,9);break;default:break;}}std::vector<NameHit>out;for(std::size_t n=0;n<names.size();++n){if(a[n])out.push_back({*a[n],std::string(names[n])});if(w[n])out.push_back({*w[n],std::string(names[n])+" (UTF-16LE)"});}return out;}
struct ExecFileRange{std::uint32_t rva=0;std::uint64_t file_offset=0,size=0;std::string section;};
std::optional<ExecFileRange> executable_file_range(const PeInfo&pe,std::uint32_t rva,std::uint64_t size){if(!size||size>(1ull<<20))return{};for(const auto&s:pe.sections){if(!(s.characteristics&0x20000000u)||!s.raw_size)continue;if(rva<s.rva)continue;auto delta=std::uint64_t(rva)-s.rva;if(delta>s.raw_size||size>std::uint64_t(s.raw_size)-delta)continue;return ExecFileRange{rva,std::uint64_t(s.raw_offset)+delta,size,s.name};}return{};}
std::optional<std::uint32_t> rip_pointer_origin(const std::vector<Decoded>&ins,std::size_t before,ZydisRegister reg){auto cur=large(reg);std::size_t seen=0;for(std::size_t z=before;z-->0&&seen<48;){const auto&x=ins[z];++seen;if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)continue;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){cur=large(x.ops[1].reg.value);continue;}if(x.zi.mnemonic==ZYDIS_MNEMONIC_LEA&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY){const auto&m=x.ops[1].mem;if(m.index==ZYDIS_REGISTER_NONE&&large(m.base)==ZYDIS_REGISTER_RIP){auto disp=m.disp.has_displacement?m.disp.value:0;auto target=std::int64_t(x.rva+x.zi.length)+disp;if(target>=0&&target<=0xffffffffll)return static_cast<std::uint32_t>(target);}return{};}return{};}return{};}
bool register_zeroed_before(const std::vector<Decoded>&ins,std::size_t before,ZydisRegister reg){auto cur=large(reg);std::size_t seen=0;for(std::size_t z=before;z-->0&&seen<48;){const auto&x=ins[z];++seen;if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)continue;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){cur=large(q.reg.value);continue;}if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE)return q.imm.value.u==0;}if(x.zi.mnemonic==ZYDIS_MNEMONIC_XOR&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[1].reg.value)==cur)return true;return false;}return false;}
std::optional<std::uint32_t> register_u32_immediate_before(const std::vector<Decoded>&ins,std::size_t before,ZydisRegister reg,std::uint32_t value){auto cur=large(reg);std::size_t seen=0;for(std::size_t z=before;z-->0&&seen<48;){const auto&x=ins[z];++seen;if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)continue;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){cur=large(q.reg.value);continue;}if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&x.ops[0].size==32&&static_cast<std::uint32_t>(q.imm.value.u)==value)return x.rva;}return{};}return{};}
bool cmp_reg_imm(const Decoded&x,ZydisRegister reg,std::uint64_t&imm){if(x.zi.mnemonic!=ZYDIS_MNEMONIC_CMP||x.zi.operand_count_visible<2)return false;bool have=false;for(std::uint8_t k=0;k<x.zi.operand_count_visible;++k){const auto&o=x.ops[k];if(o.type==ZYDIS_OPERAND_TYPE_REGISTER&&large(o.reg.value)==large(reg))have=true;else if(o.type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&!o.imm.is_relative)imm=o.imm.value.u;}return have;}
bool increments_by_one(const Decoded&x,ZydisRegister reg){auto r=large(reg);if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=r||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)return false;if(x.zi.mnemonic==ZYDIS_MNEMONIC_INC)return true;if(x.zi.mnemonic==ZYDIS_MNEMONIC_ADD&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&x.ops[1].imm.value.u==1)return true;if(x.zi.mnemonic==ZYDIS_MNEMONIC_LEA&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY){const auto&m=x.ops[1].mem;return m.index==ZYDIS_REGISTER_NONE&&large(m.base)==r&&m.disp.has_displacement&&m.disp.value==1;}return false;}
std::optional<std::uint32_t> relative_branch_target(const Decoded&x){if(x.zi.meta.category!=ZYDIS_CATEGORY_COND_BR||!x.zi.operand_count_visible)return{};const auto&o=x.ops[0];if(o.type!=ZYDIS_OPERAND_TYPE_IMMEDIATE||!o.imm.is_relative)return{};auto t=std::int64_t(x.rva+x.zi.length)+o.imm.value.s;if(t<0||t>0xffffffffll)return{};return static_cast<std::uint32_t>(t);}
struct LocalCfg{std::vector<Decoded>ins;std::map<std::uint32_t,std::size_t>by_rva;std::vector<std::vector<std::size_t>>edges;};
std::optional<std::uint32_t> relative_control_target(const Decoded&x){if((x.zi.meta.category!=ZYDIS_CATEGORY_COND_BR&&x.zi.meta.category!=ZYDIS_CATEGORY_UNCOND_BR)||!x.zi.operand_count_visible)return{};const auto&o=x.ops[0];if(o.type!=ZYDIS_OPERAND_TYPE_IMMEDIATE||!o.imm.is_relative)return{};auto t=std::int64_t(x.rva+x.zi.length)+o.imm.value.s;if(t<0||t>0xffffffffll)return{};return static_cast<std::uint32_t>(t);}
LocalCfg bounded_local_cfg(std::span<const std::uint8_t>d,const PeInfo&pe,FuncRange f){LocalCfg g;if(!f.end||f.end<=f.begin||f.end-f.begin>(1u<<20))return g;g.ins=decode_range(d,pe,f);if(g.ins.empty()||g.ins.back().rva+g.ins.back().zi.length!=f.end){g.ins.clear();return g;}g.edges.resize(g.ins.size());for(std::size_t i=0;i<g.ins.size();++i)g.by_rva[g.ins[i].rva]=i;auto edge=[&](std::size_t a,std::uint32_t r){auto it=g.by_rva.find(r);if(it!=g.by_rva.end()&&std::find(g.edges[a].begin(),g.edges[a].end(),it->second)==g.edges[a].end())g.edges[a].push_back(it->second);};for(std::size_t i=0;i<g.ins.size();++i){const auto&x=g.ins[i];std::optional<std::uint32_t>fall;if(i+1<g.ins.size())fall=g.ins[i+1].rva;if(x.zi.meta.category==ZYDIS_CATEGORY_RET)continue;if(x.zi.meta.category==ZYDIS_CATEGORY_UNCOND_BR){if(auto t=relative_control_target(x))edge(i,*t);continue;}if(x.zi.meta.category==ZYDIS_CATEGORY_COND_BR){if(auto t=relative_control_target(x))edge(i,*t);if(fall)edge(i,*fall);continue;}if(fall)edge(i,*fall);}return g;}
bool cfg_reachable(const LocalCfg&g,std::size_t start,std::size_t goal,std::optional<std::size_t>blocked={}){if(start>=g.ins.size()||goal>=g.ins.size()||blocked==start)return false;std::vector<std::uint8_t>seen(g.ins.size());std::vector<std::size_t>q{start};seen[start]=1;for(std::size_t p=0;p<q.size();++p){auto u=q[p];if(u==goal)return true;for(auto v:g.edges[u])if(!seen[v]&&(!blocked||v!=*blocked)){seen[v]=1;q.push_back(v);}}return false;}
bool cfg_dominates(const LocalCfg&g,std::size_t dom,std::size_t node){if(g.ins.empty()||dom>=g.ins.size()||node>=g.ins.size()||!cfg_reachable(g,0,node))return false;if(dom==0)return true;return !cfg_reachable(g,0,node,dom);}
std::optional<std::uint32_t> conditional_trap_controller(const LocalCfg&g,std::size_t trap){for(std::size_t i=0;i<g.ins.size();++i){if(g.ins[i].zi.meta.category!=ZYDIS_CATEGORY_COND_BR||g.edges[i].size()!=2||!cfg_dominates(g,i,trap))continue;const bool a=cfg_reachable(g,g.edges[i][0],trap),b=cfg_reachable(g,g.edges[i][1],trap);if(a!=b)return g.ins[i].rva;}return{};}
struct BreakpointScan{ExecFileRange target;std::uint32_t scanner_rva=0,load_rva=0,compare_rva=0,breakpoint_branch_rva=0,bound_rva=0,increment_rva=0,backedge_rva=0;};
std::optional<BreakpointScan> detect_breakpoint_scan(const std::vector<Decoded>&ins,const PeInfo&pe){for(std::size_t i=0;i<ins.size();++i){const auto&load=ins[i];if((load.zi.mnemonic!=ZYDIS_MNEMONIC_MOVZX&&load.zi.mnemonic!=ZYDIS_MNEMONIC_MOV)||load.zi.operand_count_visible<2||load.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||load.ops[1].type!=ZYDIS_OPERAND_TYPE_MEMORY||load.ops[1].size!=8)continue;const auto&m=load.ops[1].mem;if((m.segment!=ZYDIS_REGISTER_NONE&&m.segment!=ZYDIS_REGISTER_DS)||m.scale!=1)continue;auto dst=large(load.ops[0].reg.value);std::uint32_t cc_cmp=0,cc_branch=0;bool cc=false;for(std::size_t j=i+1;j<ins.size()&&j<=i+3;++j){std::uint64_t imm=0;if(cmp_reg_imm(ins[j],dst,imm)&&((imm&0xffu)==0xccu)){for(std::size_t q=j+1;q<ins.size()&&q<=j+2;++q){if(auto t=relative_branch_target(ins[q]);t){cc=true;cc_cmp=ins[j].rva;cc_branch=ins[q].rva;break;}}}if(cc)break;}if(!cc)continue;std::array<ZydisRegister,2>regs={large(m.base),large(m.index)};for(int base_choice=0;base_choice<2;++base_choice){auto base=regs[base_choice],idx=regs[1-base_choice];if(base==ZYDIS_REGISTER_NONE||idx==ZYDIS_REGISTER_NONE||base==idx)continue;auto start=rip_pointer_origin(ins,i,base);if(!start||!register_zeroed_before(ins,i,idx))continue;std::size_t bound_idx=ins.size(),inc_idx=ins.size(),back_idx=ins.size();std::uint64_t bound=0;for(std::size_t j=i+1;j<ins.size()&&j<=i+14;++j){std::uint64_t v=0;if(bound_idx==ins.size()&&cmp_reg_imm(ins[j],idx,v)){bound_idx=j;bound=v;}if(inc_idx==ins.size()&&increments_by_one(ins[j],idx))inc_idx=j;if(auto t=relative_branch_target(ins[j]);t&&*t<=load.rva&&*t>=ins.front().rva){back_idx=j;if(bound_idx!=ins.size()&&inc_idx!=ins.size())break;}}if(bound_idx==ins.size()||inc_idx==ins.size()||back_idx==ins.size()||bound>(1u<<20))continue;std::uint64_t size=0;if(bound_idx<inc_idx)size=bound+1;else if(inc_idx<bound_idx)size=bound;if(!size||size>(1u<<20))continue;auto range=executable_file_range(pe,*start,size);if(!range)continue;return BreakpointScan{*range,ins.front().rva,load.rva,cc_cmp,cc_branch,ins[bound_idx].rva,ins[inc_idx].rva,ins[back_idx].rva};}}return{};}
struct ChecksumLoop{
    ExecFileRange target;std::string algorithm;ZydisRegister accumulator=ZYDIS_REGISTER_NONE;
    std::uint32_t scanner_rva=0,load_rva=0,combine_rva=0,multiply_rva=0,initializer_rva=0,bound_rva=0,increment_rva=0,backedge_rva=0,loop_code_size=0,computed=0;
    std::uint32_t initializer_value=0,multiply_constant=0;
    std::size_t backedge_index=0;
};
struct ChecksumReference{
    std::uint32_t compare_rva=0,branch_rva=0,function_rva=0,compare_size=0,storage_size=0,value=0;
    std::uint64_t compare_file_offset=0,reference_file_offset=0;
    std::string source;
};
bool writes_register(const Decoded&x,ZydisRegister r){r=large(r);for(std::uint8_t k=0;k<x.zi.operand_count_visible;++k)if(x.ops[k].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[k].reg.value)==r&&(x.ops[k].actions&ZYDIS_OPERAND_ACTION_WRITE))return true;return false;}
std::optional<std::uint32_t> direct_call_target(const Decoded&x){if(x.zi.meta.category!=ZYDIS_CATEGORY_CALL||!x.zi.operand_count_visible)return{};const auto&o=x.ops[0];if(o.type!=ZYDIS_OPERAND_TYPE_IMMEDIATE||!o.imm.is_relative)return{};auto t=std::int64_t(x.rva+x.zi.length)+o.imm.value.s;if(t<0||t>0xffffffffll)return{};return static_cast<std::uint32_t>(t);}
std::optional<ChecksumReference> checksum_reference_at(std::span<const std::uint8_t>d,const PeInfo&pe,const std::vector<Decoded>&ins,std::size_t i,ZydisRegister result,std::uint32_t func_rva){
    if(i>=ins.size())return{};
    const auto&x=ins[i];
    if(x.zi.mnemonic!=ZYDIS_MNEMONIC_CMP||x.zi.operand_count_visible<2)return{};
    bool have_result=false;std::optional<std::uint32_t>value;std::uint32_t storage=0;std::uint64_t reference_off=0;std::string source;
    for(std::uint8_t k=0;k<x.zi.operand_count_visible;++k){const auto&o=x.ops[k];if(o.type==ZYDIS_OPERAND_TYPE_REGISTER&&large(o.reg.value)==large(result))have_result=true;else if(o.type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&!o.imm.is_relative){value=static_cast<std::uint32_t>(o.imm.value.u);storage=std::max<std::uint32_t>(1,o.size/8);source="IMMEDIATE_U32";}else if(o.type==ZYDIS_OPERAND_TYPE_MEMORY&&o.size==32&&o.mem.index==ZYDIS_REGISTER_NONE&&large(o.mem.base)==ZYDIS_REGISTER_RIP){auto disp=o.mem.disp.has_displacement?o.mem.disp.value:0;auto rr=std::int64_t(x.rva+x.zi.length)+disp;if(rr<0||rr>0xffffffffll)continue;auto ro=rvaoff(pe,static_cast<std::uint32_t>(rr),d.size());if(!ro||*ro+4>d.size())continue;std::uint32_t v=0;std::memcpy(&v,d.data()+*ro,4);value=v;storage=4;reference_off=*ro;source="RIP_GLOBAL_U32";}}
    if(!have_result||!value||!storage)return{};
    std::uint32_t branch=0;for(std::size_t q=i+1;q<ins.size()&&q<=i+2;++q){if(ins[q].zi.meta.category==ZYDIS_CATEGORY_COND_BR){branch=ins[q].rva;break;}if(ins[q].zi.meta.category==ZYDIS_CATEGORY_CALL||ins[q].zi.meta.category==ZYDIS_CATEGORY_RET)break;}if(!branch)return{};auto co=fileoff(pe,x.rva);if(!co)return{};return ChecksumReference{x.rva,branch,func_rva,x.zi.length,storage,*value,*co,reference_off,std::move(source)};
}
std::optional<ChecksumReference> checksum_reference_after(std::span<const std::uint8_t>d,const PeInfo&pe,const std::vector<Decoded>&ins,std::size_t start,std::size_t max_steps,ZydisRegister result,std::uint32_t func_rva){
    for(std::size_t i=start;i<ins.size()&&i<start+max_steps;++i){if(auto r=checksum_reference_at(d,pe,ins,i,result,func_rva))return r;const auto&x=ins[i];if(x.zi.meta.category==ZYDIS_CATEGORY_CALL||x.zi.meta.category==ZYDIS_CATEGORY_RET)break;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2&&x.ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[1].reg.value)==large(result)){result=large(x.ops[0].reg.value);continue;}if(writes_register(x,result))break;}return{};
}
bool returns_checksum(const std::vector<Decoded>&ins,const ChecksumLoop&loop){ZydisRegister result=large(loop.accumulator);for(std::size_t i=loop.backedge_index+1;i<ins.size()&&i<=loop.backedge_index+12;++i){const auto&x=ins[i];if(x.zi.meta.category==ZYDIS_CATEGORY_RET)return result==ZYDIS_REGISTER_RAX;if(x.zi.meta.category==ZYDIS_CATEGORY_CALL)return false;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2&&x.ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[1].reg.value)==result){result=large(x.ops[0].reg.value);continue;}if(writes_register(x,result))return false;}return false;}
std::optional<ChecksumLoop> detect_checksum_loop(std::span<const std::uint8_t>d,const std::vector<Decoded>&ins,const PeInfo&pe){
    constexpr std::uint32_t kFnvOffset=0x811c9dc5u,kFnvPrime=0x01000193u;
    auto finish=[&](std::size_t i,std::size_t combine_idx,std::size_t multiply_idx,ZydisRegister acc,ZydisRegister byte_reg,const ZydisDecodedOperandMem&m,std::string algorithm,std::uint32_t init_rva,std::uint32_t init_value,std::uint32_t mul_value)->std::optional<ChecksumLoop>{
        std::array<ZydisRegister,2>regs={large(m.base),large(m.index)};
        for(int base_choice=0;base_choice<2;++base_choice){auto base=regs[base_choice],idx=regs[1-base_choice];if(base==ZYDIS_REGISTER_NONE||idx==ZYDIS_REGISTER_NONE||base==idx||base==acc||idx==acc||base==byte_reg||idx==byte_reg)continue;auto target_rva=rip_pointer_origin(ins,i,base);if(!target_rva||!register_zeroed_before(ins,i,idx))continue;
            const auto search_from=multiply_idx<ins.size()?multiply_idx:combine_idx;std::size_t bound_idx=ins.size(),inc_idx=ins.size(),back_idx=ins.size();std::uint64_t bound=0;for(std::size_t j=search_from+1;j<ins.size()&&j<=search_from+18;++j){std::uint64_t v=0;if(bound_idx==ins.size()&&cmp_reg_imm(ins[j],idx,v)){bound_idx=j;bound=v;}if(inc_idx==ins.size()&&increments_by_one(ins[j],idx))inc_idx=j;if(auto t=relative_branch_target(ins[j]);t&&*t<=ins[i].rva&&*t>=ins.front().rva){back_idx=j;if(bound_idx!=ins.size()&&inc_idx!=ins.size())break;}}if(bound_idx==ins.size()||inc_idx==ins.size()||back_idx==ins.size()||bound>(1u<<20))continue;std::uint64_t size=bound_idx<inc_idx?bound+1:(inc_idx<bound_idx?bound:0);if(!size||size>(1u<<20))continue;auto range=executable_file_range(pe,*target_rva,size);if(!range||range->file_offset+range->size>d.size())continue;
            bool stable=true;for(std::size_t j=i;j<=back_idx;++j){if(writes_register(ins[j],base)){stable=false;break;}if(writes_register(ins[j],idx)&&j!=inc_idx){stable=false;break;}if(writes_register(ins[j],acc)&&j!=combine_idx&&j!=multiply_idx){stable=false;break;}if(algorithm=="FNV1A32_BYTE"&&writes_register(ins[j],byte_reg)&&j!=i&&j!=combine_idx){stable=false;break;}}if(!stable)continue;
            std::uint32_t computed=0;if(algorithm=="ADD32_BYTE")for(std::uint64_t z=0;z<range->size;++z)computed+=d[range->file_offset+z];else if(algorithm=="XOR32_BYTE")for(std::uint64_t z=0;z<range->size;++z)computed^=d[range->file_offset+z];else{computed=kFnvOffset;for(std::uint64_t z=0;z<range->size;++z){computed^=d[range->file_offset+z];computed*=kFnvPrime;}}
            ChecksumLoop out;out.target=*range;out.algorithm=std::move(algorithm);out.accumulator=acc;out.scanner_rva=ins.front().rva;out.load_rva=ins[i].rva;out.combine_rva=ins[combine_idx].rva;out.multiply_rva=multiply_idx<ins.size()?ins[multiply_idx].rva:0;out.initializer_rva=init_rva;out.initializer_value=init_value;out.multiply_constant=mul_value;out.bound_rva=ins[bound_idx].rva;out.increment_rva=ins[inc_idx].rva;out.backedge_rva=ins[back_idx].rva;out.loop_code_size=static_cast<std::uint32_t>(ins[back_idx].rva+ins[back_idx].zi.length-ins[i].rva);out.computed=computed;out.backedge_index=back_idx;return out;
        }
        return{};
    };
    auto fnv_multiply=[&](const Decoded&x,ZydisRegister acc,ZydisRegister input)->bool{if(x.zi.mnemonic!=ZYDIS_MNEMONIC_IMUL||x.zi.operand_count_visible<2||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=large(acc)||x.ops[0].size!=32)return false;if(x.zi.operand_count_visible>=3&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[1].reg.value)==large(input)&&x.ops[1].size==32&&x.ops[2].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&!x.ops[2].imm.is_relative&&static_cast<std::uint32_t>(x.ops[2].imm.value.u)==kFnvPrime)return true;if(input==acc&&x.ops[1].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&!x.ops[1].imm.is_relative&&static_cast<std::uint32_t>(x.ops[1].imm.value.u)==kFnvPrime)return true;return false;};
    for(std::size_t i=0;i<ins.size();++i){const auto&load=ins[i];if((load.zi.mnemonic!=ZYDIS_MNEMONIC_MOVZX&&load.zi.mnemonic!=ZYDIS_MNEMONIC_MOV)||load.zi.operand_count_visible<2||load.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||load.ops[1].type!=ZYDIS_OPERAND_TYPE_MEMORY||load.ops[1].size!=8)continue;const auto&m=load.ops[1].mem;if((m.segment!=ZYDIS_REGISTER_NONE&&m.segment!=ZYDIS_REGISTER_DS)||m.scale!=1)continue;auto byte_reg=large(load.ops[0].reg.value);
        // Existing zero-seeded ADD/XOR checks.
        for(std::size_t ci=i+1;ci<ins.size()&&ci<=i+3;++ci){const auto&comb=ins[ci];if((comb.zi.mnemonic!=ZYDIS_MNEMONIC_ADD&&comb.zi.mnemonic!=ZYDIS_MNEMONIC_XOR)||comb.zi.operand_count_visible<2||comb.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||comb.ops[1].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(comb.ops[1].reg.value)!=byte_reg)continue;auto acc=large(comb.ops[0].reg.value);if(acc==byte_reg||!register_zeroed_before(ins,i,acc))continue;if(auto out=finish(i,ci,ins.size(),acc,byte_reg,m,comb.zi.mnemonic==ZYDIS_MNEMONIC_ADD?"ADD32_BYTE":"XOR32_BYTE",0,0,0))return out;}
        // FNV-1a32: offset-basis seed, XOR one loaded byte, then multiply by the exact FNV prime.
        for(std::size_t xi=i+1;xi<ins.size()&&xi<=i+3;++xi){const auto&x=ins[xi];if(x.zi.mnemonic!=ZYDIS_MNEMONIC_XOR||x.zi.operand_count_visible<2||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||x.ops[1].type!=ZYDIS_OPERAND_TYPE_REGISTER||x.ops[0].size!=32||x.ops[1].size!=32)continue;auto dst=large(x.ops[0].reg.value),src=large(x.ops[1].reg.value),acc=ZYDIS_REGISTER_NONE,xor_result=dst;if(dst==byte_reg&&src!=byte_reg)acc=src;else if(src==byte_reg&&dst!=byte_reg)acc=dst;else continue;if(acc==ZYDIS_REGISTER_NONE||acc==byte_reg)continue;auto init=register_u32_immediate_before(ins,i,acc,kFnvOffset);if(!init)continue;for(std::size_t mi=xi+1;mi<ins.size()&&mi<=xi+3;++mi){if(!fnv_multiply(ins[mi],acc,xor_result))continue;if(auto out=finish(i,xi,mi,acc,byte_reg,m,"FNV1A32_BYTE",*init,kFnvOffset,kFnvPrime))return out;}}
    }
    return{};
}
Finding checksum_finding(const PeInfo&pe,const ChecksumLoop&cs,const ChecksumReference&ref){
    auto hx=[](std::uint32_t v){std::ostringstream o;o<<"0x"<<std::hex<<v;return o.str();};const bool match=cs.computed==ref.value;std::string short_name="XOR32",display="XOR32";if(cs.algorithm=="ADD32_BYTE"){short_name="ADD32";display="SUM32";}else if(cs.algorithm=="FNV1A32_BYTE"){short_name="FNV1A32";display="FNV1A32";}auto f=mk("executable-range checksum/"+short_name,"CONFIRMED",0.995,"self-integrity/anti-tamper","compute a byte checksum over a bounded executable code range and compare it against an embedded reference",cs.load_rva,cs.scanner_rva);f.family="Self-integrity";
    f.fields["checksum_algorithm"]=cs.algorithm;f.fields["algorithm"]=display;f.fields["reference_state"]=match?"REFERENCE_MATCH":"REFERENCE_MISMATCH";f.fields["reference_relation"]=match?"MATCH":"MISMATCH";f.fields["expected_checksum"]=hx(ref.value);f.fields["computed_checksum"]=hx(cs.computed);f.fields["reference_value"]=hx(ref.value);f.fields["computed_current_value"]=hx(cs.computed);f.fields["reference_source"]=ref.source;f.fields["reference_storage_size"]=std::to_string(ref.storage_size);f.fields["reference_compare_function_rva"]=hx(ref.function_rva);f.fields["scan_start_rva"]=hx(cs.target.rva);f.fields["scan_end_rva"]=hx(static_cast<std::uint32_t>(cs.target.rva+cs.target.size));f.fields["scan_size"]=std::to_string(cs.target.size);f.fields["scan_section"]=cs.target.section;f.fields["checked_start_rva"]=hx(cs.target.rva);f.fields["checked_end_rva"]=hx(static_cast<std::uint32_t>(cs.target.rva+cs.target.size));f.fields["checked_size"]=std::to_string(cs.target.size);f.fields["checked_section"]=cs.target.section;f.fields["checked_offset_space"]="current_input_file";{std::ostringstream o;o<<"0x"<<std::hex<<cs.target.file_offset;f.fields["checked_file_offset"]=o.str();}f.fields["scanner_function_rva"]=hx(cs.scanner_rva);f.fields["byte_load_rva"]=hx(cs.load_rva);f.fields["accumulate_rva"]=hx(cs.combine_rva);f.fields["checksum_update_rva"]=hx(cs.combine_rva);if(cs.multiply_rva){f.fields["multiply_rva"]=hx(cs.multiply_rva);f.fields["multiply_constant"]=hx(cs.multiply_constant);}if(cs.initializer_rva){f.fields["accumulator_init_rva"]=hx(cs.initializer_rva);f.fields["accumulator_init_value"]=hx(cs.initializer_value);}f.fields["bound_compare_rva"]=hx(cs.bound_rva);f.fields["increment_rva"]=hx(cs.increment_rva);f.fields["loop_backedge_rva"]=hx(cs.backedge_rva);f.fields["reference_compare_rva"]=hx(ref.compare_rva);f.fields["reference_branch_rva"]=hx(ref.branch_rva);
    if(cs.algorithm=="FNV1A32_BYTE")f.evidence.push_back("a byte-wise loop reads a statically recovered current-PE executable/file-backed range into a 32-bit FNV-1a accumulator initialized to offset basis 0x811C9DC5; each byte is XORed before multiplication by prime 0x01000193");else f.evidence.push_back("a byte-wise loop reads a statically recovered current-PE executable/file-backed range into a zero-initialized ADD/XOR accumulator");f.evidence.push_back("the index starts at zero, increments by one, is bounded by an immediate limit and returns through a conditional loop backedge");f.evidence.push_back("the checksum result is compared against an embedded reference in the scanner or a direct caller and that comparison feeds conditional control flow");if(match)f.evidence.push_back("the current checked executable bytes reproduce the embedded checksum reference");else{f.evidence.push_back("the current checked executable bytes do not reproduce the embedded checksum reference");f.negative_evidence.push_back("the mismatch proves disagreement between the current checked bytes and the embedded reference, but static analysis cannot attribute whether the code range, the reference value, or both were modified");}f.negative_evidence.push_back("self-integrity/anti-tamper behavior is confirmed; checksum match does not prove pristine/trusted content and malicious intent is not inferred");
    f.ranges.push_back({cs.target.file_offset,cs.target.size,"executable range covered by embedded checksum reference"});if(auto o=fileoff(pe,cs.load_rva))f.ranges.push_back({*o,cs.loop_code_size,"checksum byte-load/update/bound loop"});f.ranges.push_back({ref.compare_file_offset,ref.compare_size,"embedded checksum reference comparison"});if(ref.source=="RIP_GLOBAL_U32")f.ranges.push_back({ref.reference_file_offset,4,"embedded checksum reference value"});if(!match)f.suggested_actions.push_back("inspect the exact checked executable range and embedded reference separately; they disagree, but static analysis does not identify which side changed");return f;
}
void collect_checksum_caller_references(std::span<const std::uint8_t>d,const PeInfo&pe,const std::vector<Decoded>&ins,std::uint32_t func_rva,std::map<std::uint32_t,std::vector<ChecksumReference>>&refs,std::size_t&total){if(total>=65536)return;for(std::size_t i=0;i<ins.size();++i){auto target=direct_call_target(ins[i]);if(!target)continue;ZydisRegister result=ZYDIS_REGISTER_RAX;for(std::size_t j=i+1;j<ins.size()&&j<=i+5;++j){if(auto r=checksum_reference_at(d,pe,ins,j,result,func_rva)){auto&v=refs[*target];if(v.size()<8&&total<65536){v.push_back(*r);++total;}break;}const auto&x=ins[j];if(x.zi.meta.category==ZYDIS_CATEGORY_CALL||x.zi.meta.category==ZYDIS_CATEGORY_RET)break;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2&&x.ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[1].reg.value)==result){result=large(x.ops[0].reg.value);continue;}if(writes_register(x,result))break;}}}

bool raw_backward_conditional(std::span<const std::uint8_t>s){for(std::size_t i=0;i<s.size();++i){const auto op=s[i];if(((op>=0x70&&op<=0x7f)||(op>=0xe0&&op<=0xe3))&&i+2<=s.size()&&static_cast<std::int8_t>(s[i+1])<0)return true;if(op==0x0f&&i+6<=s.size()&&s[i+1]>=0x80&&s[i+1]<=0x8f){std::int32_t rel=0;std::memcpy(&rel,s.data()+i+2,4);if(rel<0)return true;}}return false;}
bool instruction_scan_candidate(std::span<const std::uint8_t>s){if(s.empty())return true;const auto has=[&](std::initializer_list<std::uint8_t>q){return std::search(s.begin(),s.end(),q.begin(),q.end())!=s.end();};if(std::find(s.begin(),s.end(),std::uint8_t(0xcc))!=s.end()||std::find(s.begin(),s.end(),std::uint8_t(0xf1))!=s.end()||has({0xcd,0x2d})||(std::find(s.begin(),s.end(),std::uint8_t(0x65))!=s.end()&&has({0x60,0x00,0x00,0x00})))return true;const bool byte_load=has({0x0f,0xb6})||std::find(s.begin(),s.end(),std::uint8_t(0x8a))!=s.end();return byte_load&&raw_backward_conditional(s);}
bool raw_calls_any(std::span<const std::uint8_t>s,std::uint32_t begin,const std::set<std::uint32_t>&targets){if(s.empty())return true;for(std::size_t i=0;i+5<=s.size();++i)if(s[i]==0xe8){std::int32_t rel=0;std::memcpy(&rel,s.data()+i+1,4);auto t=std::int64_t(begin)+static_cast<std::int64_t>(i)+5+rel;if(t>=0&&t<=0xffffffffll&&targets.count(static_cast<std::uint32_t>(t)))return true;}return false;}
struct FuncInsnStats{std::uint32_t begin=0;std::uint32_t int3=0,int1=0,int2d=0,cond=0;std::vector<std::uint32_t>trap_rvas;};
std::vector<FuncInsnStats> instruction_stats(std::span<const std::uint8_t>d,const PeInfo&pe,std::vector<Finding>&out){
    std::vector<FuncInsnStats>stats;if(!pe.pe64)return stats;std::vector<ChecksumLoop>pending_checksums;std::map<std::uint32_t,std::vector<ChecksumReference>>caller_references;std::set<std::pair<std::uint32_t,std::uint32_t>>checksum_emitted;std::size_t caller_reference_total=0;
    auto emit_checksum=[&](const ChecksumLoop&loop,const ChecksumReference&ref){if(checksum_emitted.size()>=64)return;if(checksum_emitted.insert({loop.scanner_rva,ref.compare_rva}).second)out.push_back(checksum_finding(pe,loop,ref));};
    for(const auto&rf:pe.exception.runtime_functions){
        if(!instruction_scan_candidate(raw_runtime_function(d,pe,rf)))continue;
        auto ins=decode_range(d,pe,{rf.begin_rva,rf.end_rva});if(ins.empty())continue;if(auto cs=detect_checksum_loop(d,ins,pe)){if(auto ref=checksum_reference_after(d,pe,ins,cs->backedge_index+1,12,cs->accumulator,rf.begin_rva))emit_checksum(*cs,*ref);else if(returns_checksum(ins,*cs)&&pending_checksums.size()<64)pending_checksums.push_back(*cs);}
        if(auto bp=detect_breakpoint_scan(ins,pe)){auto f=mk("software-breakpoint scan/INT3","CONFIRMED",0.995,"software-breakpoint/self-integrity probe","scan a bounded executable code range for INT3/software-breakpoint byte 0xCC",bp->load_rva,rf.begin_rva);auto hx=[](std::uint32_t v){std::ostringstream o;o<<"0x"<<std::hex<<v;return o.str();};f.fields["scan_start_rva"]=hx(bp->target.rva);f.fields["scan_end_rva"]=hx(static_cast<std::uint32_t>(bp->target.rva+bp->target.size));f.fields["scan_size"]=std::to_string(bp->target.size);f.fields["scan_section"]=bp->target.section;f.fields["breakpoint_byte"]="0xcc";f.fields["compare_rva"]=hx(bp->compare_rva);f.fields["breakpoint_branch_rva"]=hx(bp->breakpoint_branch_rva);f.fields["bound_compare_rva"]=hx(bp->bound_rva);f.fields["increment_rva"]=hx(bp->increment_rva);f.fields["loop_backedge_rva"]=hx(bp->backedge_rva);f.evidence.push_back("a byte-wise loop reads a statically recovered current-PE executable/file-backed range and compares each byte against 0xCC");f.evidence.push_back("the loop index starts at zero, has a bounded upper limit, increments by one and has a conditional backedge");f.negative_evidence.push_back("the software-breakpoint/self-integrity scan behavior is confirmed; why the program reacts to a detected 0xCC byte is not interpreted as malicious intent");if(auto o=fileoff(pe,bp->load_rva))f.ranges.push_back({*o,6,"software-breakpoint scan byte load/compare loop"});f.ranges.push_back({bp->target.file_offset,bp->target.size,"executable range scanned for software breakpoint byte 0xCC"});out.push_back(std::move(f));}FuncInsnStats st;st.begin=rf.begin_rva;std::set<ZydisRegister>peb;bool being_emitted=false,ntglobal_emitted=false;ZydisRegister ntglobal_reg=ZYDIS_REGISTER_NONE;std::uint32_t ntglobal_read_rva=0;int ntglobal_ttl=0;
        auto emit_ntglobal=[&](std::uint32_t read_rva,std::uint32_t check_rva,std::string pattern){if(ntglobal_emitted)return;auto f=mk("PEB.NtGlobalFlag/debug-heap-bits","LIKELY",0.94,"debugger-state probe","read x64 PEB NtGlobalFlag and test debug-heap flag mask",check_rva,rf.begin_rva);f.fields["architecture"]="x64";f.fields["peb_offset"]="0xbc";f.fields["debug_heap_mask"]="0x70";f.fields["access_pattern"]=std::move(pattern);f.fields["ntglobalflag_read_rva"]="0x"+[] (std::uint32_t v){std::ostringstream o;o<<std::hex<<v;return o.str();}(read_rva);f.evidence.push_back("code derives the PEB from GS:[0x60], accesses x64 PEB+0xBC, and explicitly masks/tests 0x70 debug-heap bits");f.negative_evidence.push_back("NtGlobalFlag/PEB layout is an internal Windows contract; the exact x64 offset is version-sensitive and is not treated as a public API guarantee");add_call_range(f,pe,read_rva,4);if(check_rva!=read_rva)add_call_range(f,pe,check_rva,6);out.push_back(std::move(f));ntglobal_emitted=true;};
        for(const auto&x:ins){
            if(x.zi.meta.category==ZYDIS_CATEGORY_COND_BR)++st.cond;
            if(x.zi.mnemonic==ZYDIS_MNEMONIC_INT3){++st.int3;if(st.trap_rvas.size()<64)st.trap_rvas.push_back(x.rva);}
            if(x.zi.mnemonic==ZYDIS_MNEMONIC_INT1){++st.int1;if(st.trap_rvas.size()<64)st.trap_rvas.push_back(x.rva);}
            if(x.zi.mnemonic==ZYDIS_MNEMONIC_INT&&x.zi.operand_count_visible&&x.ops[0].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&x.ops[0].imm.value.u==0x2d){++st.int2d;if(st.trap_rvas.size()<64)st.trap_rvas.push_back(x.rva);}
            if(ntglobal_ttl>0)--ntglobal_ttl;else ntglobal_reg=ZYDIS_REGISTER_NONE;
            if(!ntglobal_emitted&&ntglobal_reg!=ZYDIS_REGISTER_NONE){bool reg=false;std::optional<std::uint64_t>imm;for(std::uint8_t k=0;k<x.zi.operand_count_visible;++k){if(x.ops[k].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[k].reg.value)==ntglobal_reg)reg=true;if(x.ops[k].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&!x.ops[k].imm.is_relative)imm=x.ops[k].imm.value.u;}if(reg&&imm&&*imm==0x70&&(x.zi.mnemonic==ZYDIS_MNEMONIC_TEST||x.zi.mnemonic==ZYDIS_MNEMONIC_AND||x.zi.mnemonic==ZYDIS_MNEMONIC_CMP))emit_ntglobal(ntglobal_read_rva,x.rva,"REGISTER_READ_THEN_MASK");}
            bool peb_load=false;ZydisRegister dst=ZYDIS_REGISTER_NONE;if((x.zi.mnemonic==ZYDIS_MNEMONIC_MOV||x.zi.mnemonic==ZYDIS_MNEMONIC_MOVZX)&&x.zi.operand_count_visible>=2&&x.ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&x.ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY){const auto&m=x.ops[1].mem;if(m.segment==ZYDIS_REGISTER_GS&&m.base==ZYDIS_REGISTER_NONE&&m.index==ZYDIS_REGISTER_NONE&&m.disp.has_displacement&&m.disp.value==0x60){peb_load=true;dst=large(x.ops[0].reg.value);}}
            if(peb_load)peb.insert(dst);
            for(std::uint8_t k=0;k<x.zi.operand_count_visible;++k){const auto&o=x.ops[k];if(o.type!=ZYDIS_OPERAND_TYPE_MEMORY||o.mem.index!=ZYDIS_REGISTER_NONE||!peb.count(large(o.mem.base))||!o.mem.disp.has_displacement)continue;auto disp=o.mem.disp.value;if(disp==2&&!being_emitted){auto f=mk("PEB.BeingDebugged","CONFIRMED",0.99,"debugger-state probe","direct PEB BeingDebugged read",x.rva,rf.begin_rva);f.evidence.push_back("x64 code obtains the PEB through GS:[0x60] and reads byte offset +2 (BeingDebugged)");f.negative_evidence.push_back("PEB is an internal OS structure; behavior is a debugger-state probe, not proof of malicious intent");add_call_range(f,pe,x.rva,x.zi.length);out.push_back(std::move(f));being_emitted=true;}if(disp==0xbc&&!ntglobal_emitted){std::optional<std::uint64_t>imm;for(std::uint8_t z=0;z<x.zi.operand_count_visible;++z)if(x.ops[z].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&!x.ops[z].imm.is_relative)imm=x.ops[z].imm.value.u;if(x.zi.mnemonic==ZYDIS_MNEMONIC_TEST&&imm&&*imm==0x70)emit_ntglobal(x.rva,x.rva,"DIRECT_MEMORY_TEST");else if(x.zi.operand_count_visible>=2&&x.ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)){ntglobal_reg=large(x.ops[0].reg.value);ntglobal_read_rva=x.rva;ntglobal_ttl=8;}}}
            if(x.zi.operand_count_visible&&x.ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)){auto w=large(x.ops[0].reg.value);if(!peb_load){if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&peb.count(large(x.ops[1].reg.value)))peb.insert(w);else peb.erase(w);}}
        }
        stats.push_back(st);
    }
    if(!pending_checksums.empty()){std::set<std::uint32_t>targets;for(const auto&loop:pending_checksums)targets.insert(loop.scanner_rva);for(const auto&rf:pe.exception.runtime_functions){if(!raw_calls_any(raw_runtime_function(d,pe,rf),rf.begin_rva,targets))continue;auto ins=decode_range(d,pe,{rf.begin_rva,rf.end_rva});if(ins.empty())continue;collect_checksum_caller_references(d,pe,ins,rf.begin_rva,caller_references,caller_reference_total);}}for(const auto&loop:pending_checksums){auto it=caller_references.find(loop.scanner_rva);if(it==caller_references.end())continue;for(const auto&ref:it->second){if(checksum_emitted.size()>=64)break;emit_checksum(loop,ref);}}
    return stats;
}
struct TrapHandlerRelation{std::uint32_t trap_rva=0,registration_rva=0,handler_rva=0,condition_rva=0;std::string api;};
std::optional<TrapHandlerRelation> close_trap_handler_relation(std::span<const std::uint8_t>d,const PeInfo&pe,const FuncInsnStats&s,const std::vector<const ImportedCall*>&calls){if(s.trap_rvas.empty()||calls.empty())return{};std::uint32_t end=0;for(auto*c:calls)if(c->func_begin==s.begin){end=c->func_end;break;}if(!end)return{};auto g=bounded_local_cfg(d,pe,{s.begin,end});if(g.ins.empty())return{};for(auto*c:calls){if(c->func_begin!=s.begin||c->func_end!=end||(c->name!="AddVectoredExceptionHandler"&&c->name!="SetUnhandledExceptionFilter"))continue;const int arg=c->name=="AddVectoredExceptionHandler"?1:0;auto handler=pointer_rva_arg(d,pe,*c,arg);if(!handler||!executable_rva(pe,handler->rva))continue;auto ri=g.by_rva.find(c->callsite);if(ri==g.by_rva.end())continue;for(auto tr:s.trap_rvas){auto ti=g.by_rva.find(tr);if(ti==g.by_rva.end()||ti->second==ri->second)continue;if(!cfg_dominates(g,ri->second,ti->second)||!cfg_reachable(g,ri->second,ti->second))continue;auto ctrl=conditional_trap_controller(g,ti->second);if(!ctrl)continue;return TrapHandlerRelation{tr,c->callsite,handler->rva,*ctrl,c->name};}}return{};}
} // namespace
std::vector<Finding> detect_antidebug(std::span<const std::uint8_t>d,const PeInfo&pe){std::vector<Finding>out;if(!pe.valid)return out;auto calls_future=std::async(std::launch::async,[&](){return find_import_calls(d,pe);});std::vector<Finding>scan_findings;auto stats=instruction_stats(d,pe,scan_findings);auto calls=calls_future.get();std::map<std::uint32_t,std::vector<const ImportedCall*>>byfunc;for(const auto&c:calls)byfunc[c.func_begin].push_back(&c);
    for(const auto&c:calls){if(c.name=="IsDebuggerPresent"){auto guarded=postcall_conditional(d,pe,c);auto f=mk(c.name,"CONFIRMED",guarded?0.99:0.97,"debugger-state probe","query current-process debugger presence",c.callsite,c.func_begin,c.name);f.fields["result_controls_branch"]=guarded?"true":"not_confirmed";f.evidence.push_back("a real IsDebuggerPresent callsite was recovered, not import-name presence alone");if(guarded)f.evidence.push_back("the returned debugger-presence value is tested and feeds a nearby conditional branch");else f.negative_evidence.push_back("a debug-dependent reaction was not statically confirmed");annotate_import_call(f,pe,c);out.push_back(std::move(f));continue;}
        if(c.name=="CheckRemoteDebuggerPresent"){auto f=mk(c.name,"CONFIRMED",0.98,"debugger-state probe","query debugger presence for a process",c.callsite,c.func_begin,c.name);f.fields["debugger_present_output_usage"]="NOT_DATAFLOW_CONFIRMED";f.evidence.push_back("a real CheckRemoteDebuggerPresent callsite was recovered; the API is explicitly a debugger-presence query");f.negative_evidence.push_back("the output BOOL's later control-flow use is not yet data-flow-resolved");annotate_import_call(f,pe,c);out.push_back(std::move(f));continue;}
        if(c.name=="DebugBreak"){auto f=mk("DebugBreak","SUSPECTED",0.62,"exception/debugger interaction","trigger an explicit breakpoint exception",c.callsite,c.func_begin,c.name);f.evidence.push_back("a real DebugBreak callsite was recovered");f.negative_evidence.push_back("DebugBreak is also used by benign diagnostics/assertions; debugger-dependent reaction is not inferred");annotate_import_call(f,pe,c);out.push_back(std::move(f));continue;}
        if(c.name=="NtQueryInformationProcess"||c.name=="ZwQueryInformationProcess"){auto q=scalar_arg(d,pe,c,1);if(q&&(*q==7||*q==30||*q==31)){std::string cls=*q==7?"ProcessDebugPort":(*q==30?"ProcessDebugObjectHandle":"ProcessDebugFlags");auto f=mk(c.name+"/"+cls,"CONFIRMED",0.99,"native debugger-state probe","native process debug information query",c.callsite,c.func_begin,c.name);f.fields["information_class"]=std::to_string(*q);f.fields["information_class_name"]=cls;f.evidence.push_back("ProcessInformationClass immediate resolves to a debugger-specific PROCESSINFOCLASS value");f.negative_evidence.push_back("the query behavior is confirmed; why the program reacts to the result is a separate question");annotate_import_call(f,pe,c);out.push_back(std::move(f));}continue;}
        if(c.name=="NtQuerySystemInformation"||c.name=="ZwQuerySystemInformation"){auto q=scalar_arg(d,pe,c,0);if(q&&*q==35){auto n=scalar_arg(d,pe,c,2);auto f=mk(c.name+"/SystemKernelDebuggerInformation","LIKELY",n&&*n==2?0.97:0.95,"kernel debugger-state probe","query undocumented SystemKernelDebuggerInformation",c.callsite,c.func_begin,c.name);f.fields["system_information_class"]="35";f.fields["system_information_class_name"]="SystemKernelDebuggerInformation";f.fields["undocumented_information_class"]="true";if(n)f.fields["buffer_size"]=std::to_string(*n);f.evidence.push_back("SystemInformationClass immediate is 35 (0x23), widely used for SYSTEM_KERNEL_DEBUGGER_INFORMATION");if(n&&*n==2)f.evidence.push_back("requested output length is 2 bytes, matching the two BOOLEAN kernel-debugger state fields used by established NT headers");f.negative_evidence.push_back("this information class is not part of the stable documented Win32 contract and may vary across Windows versions");annotate_import_call(f,pe,c);out.push_back(std::move(f));}continue;}
        if(c.name=="NtQueryObject"||c.name=="ZwQueryObject"){auto cls=scalar_arg(d,pe,c,1);if(cls&&*cls==2){auto buf=stack_pointer_arg(d,pe,c,2);if(buf){for(const auto&cmp:calls){if(cmp.func_begin!=c.func_begin||cmp.callsite<=c.callsite||cmp.callsite-c.callsite>192||(cmp.name!="lstrcmpW"&&cmp.name!="lstrcmpiW"))continue;std::optional<Utf16Arg>lit;int literal_arg=-1,buffer_arg=-1;for(int a=0;a<2&&!lit;++a){auto q=pointer_utf16_ascii_arg(d,pe,cmp,a);if(q&&q->value=="DebugObject"){lit=std::move(q);literal_arg=a;buffer_arg=1-a;}}if(!lit)continue;std::uint32_t load_rva=0;if(!argument_loads_stack_field(d,pe,cmp,buffer_arg,*buf,8,&load_rva))continue;auto guarded=postcall_conditional(d,pe,cmp);auto f=mk("NtQueryObject/ObjectTypeInformation/DebugObject","CONFIRMED",guarded?0.995:0.98,"debugger-object probe","query an object type and compare its returned TypeName against DebugObject",c.callsite,c.func_begin,c.name);f.fields["object_information_class"]="2";f.fields["object_information_class_name"]="ObjectTypeInformation";f.fields["type_name_buffer_field_offset"]="8";f.fields["compare_api"]=cmp.name;f.fields["compare_callsite_rva"]="0x"+[] (std::uint32_t v){std::ostringstream o;o<<std::hex<<v;return o.str();}(cmp.callsite);f.fields["type_name_load_rva"]="0x"+[] (std::uint32_t v){std::ostringstream o;o<<std::hex<<v;return o.str();}(load_rva);f.fields["matched_object_type"]="DebugObject";f.fields["literal_argument"]=std::to_string(literal_arg);f.fields["comparison_controls_branch"]=guarded?"true":"not_confirmed";f.evidence.push_back("NtQueryObject uses ObjectTypeInformation and writes to a recovered stack-resident OBJECT_TYPE_INFORMATION buffer");f.evidence.push_back("a later string-compare call reads UNICODE_STRING.Buffer at output-buffer +8 and compares it with the actual UTF-16 literal DebugObject");if(guarded)f.evidence.push_back("the comparison result feeds nearby conditional control flow");f.negative_evidence.push_back("DebugObject type inspection is confirmed; the reason the program performs the check is not inferred");annotate_import_call(f,pe,c);add_call_range(f,pe,cmp.callsite);if(auto o=fileoff(pe,load_rva))f.ranges.push_back({*o,6,"ObjectTypeInformation.TypeName.Buffer load"});f.ranges.push_back({lit->offset,(lit->value.size()+1)*2,"DebugObject UTF-16 comparison literal"});out.push_back(std::move(f));break;}}}continue;}
        if(c.name=="NtYieldExecution"){std::uint32_t cr=0,br=0;if(postcall_return_compare_branch(d,pe,c,0x40000024u,cr,br)){auto f=mk("NtYieldExecution/STATUS_NO_YIELD_PERFORMED","LIKELY",0.82,"scheduler/timing debugger probe","compare NtYieldExecution return status against STATUS_NO_YIELD_PERFORMED",c.callsite,c.func_begin,c.name);f.fields["status_value"]="0x40000024";f.fields["status_name"]="STATUS_NO_YIELD_PERFORMED";{std::ostringstream a;a<<"0x"<<std::hex<<cr;f.fields["compare_rva"]=a.str();}{std::ostringstream a;a<<"0x"<<std::hex<<br;f.fields["branch_rva"]=a.str();}f.evidence.push_back("a real NtYieldExecution call is immediately compared against STATUS_NO_YIELD_PERFORMED and feeds conditional control flow");f.negative_evidence.push_back("this technique is unreliable and also underlies benign SwitchToThread behavior; the exact comparison is reported without inferring malicious intent");annotate_import_call(f,pe,c);add_call_range(f,pe,cr,5);out.push_back(std::move(f));}continue;}
        if(c.name=="NtCreateThreadEx"){auto flags=stack_scalar_arg(d,pe,c,6);if(flags&&((*flags)&4u)){auto f=mk("NtCreateThreadEx/HIDE_FROM_DEBUGGER","CONFIRMED",0.995,"debugger-control/evasion","create a thread with THREAD_CREATE_FLAGS_HIDE_FROM_DEBUGGER",c.callsite,c.func_begin,c.name);f.fields["create_flags"]=std::to_string(*flags);f.fields["hide_from_debugger_bit"]="0x4";f.evidence.push_back("the actual seventh NtCreateThreadEx argument contains THREAD_CREATE_FLAGS_HIDE_FROM_DEBUGGER (0x4)");f.negative_evidence.push_back("thread hiding behavior is confirmed; software intent remains separate");annotate_import_call(f,pe,c);out.push_back(std::move(f));}continue;}
        if(c.name=="NtSetInformationThread"||c.name=="ZwSetInformationThread"){auto q=scalar_arg(d,pe,c,1);if(q&&*q==17){auto f=mk(c.name+"/ThreadHideFromDebugger","CONFIRMED",0.995,"debugger-control/evasion","set ThreadHideFromDebugger information class",c.callsite,c.func_begin,c.name);f.fields["thread_information_class"]="17";f.fields["thread_information_class_name"]="ThreadHideFromDebugger";f.evidence.push_back("ThreadInformationClass immediate is the Windows SDK ThreadHideFromDebugger enum value");annotate_import_call(f,pe,c);out.push_back(std::move(f));}continue;}
        if(c.name=="GetThreadContext"||c.name=="Wow64GetThreadContext"||c.name=="NtGetContextThread"){if(function_has_imm(d,pe,c,{0x00100010u,0x00010010u})){auto use=debug_register_context_use(d,pe,c);auto confirmed=use.count>0;auto f=mk(c.name+"/DebugRegisters",confirmed?"CONFIRMED":"LIKELY",confirmed?0.98:0.9,"hardware-breakpoint probe",confirmed?"request and consume thread hardware-debug-register context":"request thread context with debug-register flags",c.callsite,c.func_begin,c.name);f.fields["debug_register_reads"]=std::to_string(use.count);if(!use.names.empty())f.fields["debug_register_names"]=use.names;f.evidence.push_back("GetThreadContext-family call shares a function with CONTEXT_DEBUG_REGISTERS-compatible ContextFlags literal");if(confirmed){f.evidence.push_back("post-call code reads one or more x64 CONTEXT Dr0/Dr1/Dr2/Dr3/Dr6/Dr7 fields from the same stack-resident CONTEXT buffer");if(auto o=fileoff(pe,use.first_rva))f.ranges.push_back({*o,6,"hardware debug-register consumption"});}else f.negative_evidence.push_back("crash handlers and diagnostics can request thread contexts legitimately; DR0-DR7 consumption is not statically proven");annotate_import_call(f,pe,c);out.push_back(std::move(f));}continue;}
        if(c.name=="FindWindowA"){std::optional<AsciiArg>a;int arg=-1;for(int k=0;k<2&&!a;++k){auto q=pointer_ascii_arg(d,pe,c,k);if(q&&canonical_debugger_name(q->value)){a=std::move(q);arg=k;}}if(a){auto canon=canonical_debugger_name(a->value);auto f=mk("debugger window discovery/exact","LIKELY",0.95,"debugger discovery","FindWindowA with statically resolved debugger-identifying class/title",c.callsite,c.func_begin,c.name);f.fields["matched_debugger_name"]=canon?*canon:a->value;f.fields["window_string"]=a->value;f.fields["window_string_argument"]=arg==0?"class_name":"window_title";f.fields["string_arg_source"]=a->source;{std::ostringstream r;r<<"0x"<<std::hex<<a->rva;f.fields["string_rva"]=r.str();}f.fields["string_file_offset"]=std::to_string(a->offset);f.evidence.push_back("the actual FindWindowA class/title argument resolves to a file-backed debugger-identifying string");f.negative_evidence.push_back("finding a debugger window is a debugger-discovery action, but software intent remains separate");annotate_import_call(f,pe,c);f.ranges.push_back({a->offset,a->value.size()+1,"FindWindowA debugger-identifying argument"});out.push_back(std::move(f));}continue;}
        if(c.name=="CloseHandle"){auto q=scalar_arg(d,pe,c,0);if(q&&(*q==~std::uint64_t(0)||*q==~std::uint64_t(1))){auto f=mk("CloseHandle/invalid-pseudohandle","LIKELY",0.93,"exception debugger probe","close invalid or pseudo handle to exploit debugger exception behavior",c.callsite,c.func_begin,c.name);std::ostringstream x;x<<"0x"<<std::hex<<*q;f.fields["handle_value"]=x.str();f.evidence.push_back("CloseHandle receives an immediate invalid/pseudo-handle value");f.negative_evidence.push_back("this can also be an application bug; nearby exception handling would further strengthen the classification");annotate_import_call(f,pe,c);out.push_back(std::move(f));}continue;}
        if(c.name=="RaiseException"){auto q=scalar_arg(d,pe,c,0);if(q&&(*q==0x40010005u||*q==0x40010006u||*q==0x40010007u||*q==0x4001000au)){auto f=mk("RaiseException/debug-status","LIKELY",0.94,"exception debugger probe","raise debugger-specific NTSTATUS exception",c.callsite,c.func_begin,c.name);std::ostringstream x;x<<"0x"<<std::hex<<*q;f.fields["exception_code"]=x.str();f.evidence.push_back("RaiseException code is a DBG_* status from Windows headers");annotate_import_call(f,pe,c);out.push_back(std::move(f));}continue;}}
    for(auto&f:scan_findings)out.push_back(std::move(f));
    for(const auto&s:stats){if((s.int1||s.int2d||s.int3)&&s.cond){auto rel=close_trap_handler_relation(d,pe,s,byfunc[s.begin]);const bool handler_related=rel.has_value();std::uint32_t chosen=handler_related?rel->trap_rva:(s.trap_rvas.empty()?0:s.trap_rvas.front());if(s.int1||s.int2d||(s.int3&&handler_related)){auto f=mk("exception/trap probe",handler_related?"LIKELY":"SUSPECTED",handler_related?0.86:0.66,"exception debugger probe","software trap/exception sequence",chosen,s.begin);f.fields["int3_count"]=std::to_string(s.int3);f.fields["int1_count"]=std::to_string(s.int1);f.fields["int2d_count"]=std::to_string(s.int2d);f.fields["exception_handler_registration_controls_trap"]=handler_related?"true":"false";if(rel){std::ostringstream hr,hh,cr;hr<<"0x"<<std::hex<<rel->registration_rva;hh<<"0x"<<std::hex<<rel->handler_rva;cr<<"0x"<<std::hex<<rel->condition_rva;f.fields["handler_registration_rva"]=hr.str();f.fields["handler_callback_rva"]=hh.str();f.fields["trap_condition_rva"]=cr.str();f.fields["handler_registration_api"]=rel->api;f.fields["registration_trap_relation"]="SAME_FUNCTION_CFG_DOMINANCE_REACHABILITY";}f.evidence.push_back("function contains debugger-relevant trap instruction(s) and conditional control flow");if(rel){f.evidence.push_back("an exact exception-handler registration call resolves an executable callback and dominates the trap in the same bounded function CFG");f.evidence.push_back("the registration reaches the trap and a concrete conditional branch structurally controls whether the trap is reached");}else f.negative_evidence.push_back("trap instruction can be diagnostics/assertion behavior; exact registration-to-conditional-trap CFG correlation is absent");add_call_range(f,pe,chosen,1);out.push_back(std::move(f));}}}
    for(const auto&[fb,v]:byfunc){std::map<std::string,std::vector<const ImportedCall*>>timer;for(auto*c:v)if(c->name=="QueryPerformanceCounter"||c->name=="GetTickCount"||c->name=="GetTickCount64"||c->name=="timeGetTime")timer[c->name].push_back(c);for(const auto&[name,samples]:timer)if(samples.size()>=2){auto f=mk(name+" timing pair","SUSPECTED",0.45,"timing probe","multiple timing API samples in one function",0,fb,name);f.fields["sample_count"]=std::to_string(samples.size());std::ostringstream sites;for(const auto*c:samples){if(sites.tellp()>0)sites<<',';sites<<"0x"<<std::hex<<c->callsite;}f.fields["sample_callsites"]=sites.str();f.evidence.push_back("the same function calls the timing source at least twice");f.negative_evidence.push_back("timing APIs have broad benign use; threshold and debug-dependent reaction are not statically confirmed");out.push_back(std::move(f));}}
    bool exact_discovery=std::any_of(out.begin(),out.end(),[](const Finding&f){return f.family=="Anti-debug"&&f.variant=="debugger window discovery/exact";});auto names=debugger_name_hits(d);if(!exact_discovery&&!names.empty()){std::set<std::string>enumapis;for(const auto&c:calls)if(c.name=="FindWindowA"||c.name=="FindWindowW"||c.name=="EnumWindows"||c.name=="CreateToolhelp32Snapshot"||c.name=="Process32FirstA"||c.name=="Process32FirstW"||c.name=="Process32NextA"||c.name=="Process32NextW"||c.name=="EnumProcesses")enumapis.insert(c.name);if(!enumapis.empty()){auto f=mk("debugger process/window discovery","SUSPECTED",0.5,"debugger discovery","process/window enumeration plus uncorrelated debugger-identifying strings",0,0);std::string a;for(const auto&x:enumapis){if(!a.empty())a+=",";a+=x;}f.fields["enumeration_apis"]=a;std::string ns;for(const auto&h:names){if(!ns.empty())ns+=",";ns+=h.name;f.ranges.push_back({h.off,h.name.find("UTF-16LE")!=std::string::npos?(h.name.size()-11)*2:h.name.size(),"debugger-name string"});}f.fields["debugger_name_hints"]=ns;f.evidence.push_back("debugger-identifying names coexist with actual process/window-enumeration callsites");f.negative_evidence.push_back("the debugger string is not data-flow-correlated to the enumeration call, so this remains a weak co-occurrence clue");out.push_back(std::move(f));}}
    static constexpr std::array<std::string_view,9>dyn={"IsDebuggerPresent","CheckRemoteDebuggerPresent","NtQueryInformationProcess","ZwQueryInformationProcess","NtSetInformationThread","ZwSetInformationThread","GetThreadContext","NtGetContextThread","OutputDebugStringA"};
    bool getproc=false,exact_dynamic=false;for(const auto&c:calls)if(c.name=="GetProcAddress"){getproc=true;auto a=pointer_ascii_arg(d,pe,c,1);if(!a)continue;auto it=std::find(dyn.begin(),dyn.end(),std::string_view(a->value));if(it==dyn.end())continue;exact_dynamic=true;auto f=mk("dynamic anti-debug API resolution","LIKELY",0.94,"dynamic debugger probe surface","GetProcAddress with statically resolved anti-debug API-name argument",c.callsite,c.func_begin,"GetProcAddress");f.fields["resolved_name"]=a->value;f.fields["name_arg_source"]=a->source;{std::ostringstream x;x<<"0x"<<std::hex<<a->rva;f.fields["name_rva"]=x.str();}f.fields["name_file_offset"]=std::to_string(a->offset);f.evidence.push_back("the actual GetProcAddress name argument resolves to a file-backed NUL-terminated anti-debug API string");f.negative_evidence.push_back("resolving an anti-debug API proves acquisition of its address, not that the resolved function is later invoked");annotate_import_call(f,pe,c);f.ranges.push_back({a->offset,a->value.size()+1,"GetProcAddress anti-debug API-name argument"});out.push_back(std::move(f));}
    if(getproc&&!exact_dynamic){for(auto n:dyn){auto it=std::search(d.begin(),d.end(),n.begin(),n.end());if(it!=d.end()){auto off=static_cast<std::uint64_t>(it-d.begin());auto f=mk("dynamic anti-debug API resolution","SUSPECTED",0.45,"dynamic debugger probe surface","GetProcAddress plus anti-debug API-name string without argument correlation",0,0,"GetProcAddress");f.fields["resolved_name_hint"]=std::string(n);f.evidence.push_back("GetProcAddress is actually called and the binary contains an anti-debug API name string");f.negative_evidence.push_back("the exact GetProcAddress name argument was not resolved; co-occurrence alone is insufficient for LIKELY/CONFIRMED behavior");f.ranges.push_back({off,n.size(),"anti-debug API name string"});out.push_back(std::move(f));break;}}}
    constexpr std::size_t weak_cap=24;std::size_t weak_seen=0;std::vector<Finding>bounded;bounded.reserve(out.size());for(auto&f:out){if(f.state=="SUSPECTED"){if(weak_seen++>=weak_cap)continue;}bounded.push_back(std::move(f));}return bounded;}
} // namespace prts
