#include "prts/crypto.hpp"
#include "prts/x86_semantic.hpp"
extern "C" {
#include "Zydis.h"
}
#include <algorithm>
#include <array>
#include <cstring>
#include <iomanip>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <tuple>
#include <vector>
namespace prts { namespace {
std::optional<std::size_t> rvaoff(const PeInfo&pe,std::uint32_t rva,std::size_t n){if(rva<pe.headers_size&&rva<n)return std::size_t(rva);for(const auto&s:pe.sections){auto span=std::max(s.vsize,s.raw_size);if(rva>=s.rva&&std::uint64_t(rva)<std::uint64_t(s.rva)+span){auto delta=std::uint64_t(rva)-s.rva;if(delta>=s.raw_size)return{};auto o=std::uint64_t(s.raw_offset)+delta;if(o<n)return std::size_t(o);}}return{};}
std::optional<std::uint32_t> offrva(const PeInfo&pe,std::uint64_t off){for(const auto&s:pe.sections)if(off>=s.raw_offset&&off<std::uint64_t(s.raw_offset)+s.raw_size){auto r=std::uint64_t(s.rva)+(off-s.raw_offset);if(r<=0xffffffffull)return static_cast<std::uint32_t>(r);}return{};}
const PeSection* section_for_rva(const PeInfo&pe,std::uint32_t rva){for(const auto&s:pe.sections){auto span=std::max(s.vsize,s.raw_size);if(rva>=s.rva&&std::uint64_t(rva)<std::uint64_t(s.rva)+span)return &s;}return nullptr;}
std::uint32_t u32(std::span<const std::uint8_t>d,std::size_t o){return o+4<=d.size()?std::uint32_t(d[o])|(std::uint32_t(d[o+1])<<8)|(std::uint32_t(d[o+2])<<16)|(std::uint32_t(d[o+3])<<24):0;}
bool delta_value(std::uint64_t v){auto x=static_cast<std::uint32_t>(v);return x==0x9e3779b9u||x==0x61c88647u||x==0xc6ef3720u;}
ZydisRegister large(ZydisRegister r){return r==ZYDIS_REGISTER_NONE?r:ZydisRegisterGetLargestEnclosing(ZYDIS_MACHINE_MODE_LONG_64,r);}
std::string argname(int n){static const char*x[]={"RCX","RDX","R8","R9"};return n>=0&&n<4?x[n]:"";}
struct Origin {int arg=-1;std::int64_t delta=0;bool dynamic=false;};
struct FunctionSem {
    bool valid=false;std::string algorithm;std::uint32_t begin=0,end=0;int key_arg=-1;
    std::array<std::set<int>,4> fixed;std::array<std::uint32_t,4> dynamic{};
    std::uint32_t shift4=0,shift5=0,xors=0,addsub=0,back=0,deltas=0,instructions=0;
};
FunctionSem analyze_function(std::span<const std::uint8_t>d,const PeInfo&pe,const PeRuntimeFunction&rf){FunctionSem f;f.begin=rf.begin_rva;f.end=rf.end_rva;auto off=rvaoff(pe,rf.begin_rva,d.size());if(!off||rf.end_rva<=rf.begin_rva)return f;ZydisDecoder dec;if(!ZYAN_SUCCESS(ZydisDecoderInit(&dec,ZYDIS_MACHINE_MODE_LONG_64,ZYDIS_STACK_WIDTH_64)))return f;std::map<ZydisRegister,Origin>orig;orig[ZYDIS_REGISTER_RCX]={0,0,false};orig[ZYDIS_REGISTER_RDX]={1,0,false};orig[ZYDIS_REGISTER_R8]={2,0,false};orig[ZYDIS_REGISTER_R9]={3,0,false};std::uint32_t cur=rf.begin_rva;
    while(cur<rf.end_rva&&f.instructions<4096){auto ro=rvaoff(pe,cur,d.size());if(!ro||*ro>=d.size())break;ZydisDecodedInstruction zi{};ZydisDecodedOperand ops[ZYDIS_MAX_OPERAND_COUNT]{};auto avail=std::min<std::size_t>(d.size()-*ro,rf.end_rva-cur);if(!ZYAN_SUCCESS(ZydisDecoderDecodeFull(&dec,d.data()+*ro,avail,&zi,ops))||!zi.length)break;++f.instructions;
        for(std::uint8_t i=0;i<zi.operand_count_visible;i++)if(ops[i].type==ZYDIS_OPERAND_TYPE_IMMEDIATE){if(delta_value(ops[i].imm.value.u))++f.deltas;if((zi.mnemonic==ZYDIS_MNEMONIC_SHL||zi.mnemonic==ZYDIS_MNEMONIC_SHR)&&!ops[i].imm.is_relative){auto v=ops[i].imm.value.u;if(v==4)++f.shift4;if(v==5)++f.shift5;}}
        if(zi.mnemonic==ZYDIS_MNEMONIC_XOR)++f.xors;
        if(zi.mnemonic==ZYDIS_MNEMONIC_ADD||zi.mnemonic==ZYDIS_MNEMONIC_SUB)++f.addsub;
        for(std::uint8_t i=0;i<zi.operand_count_visible;i++)if(ops[i].type==ZYDIS_OPERAND_TYPE_MEMORY){auto b=large(ops[i].mem.base);auto it=orig.find(b);if(it==orig.end()||it->second.arg<0)continue;auto disp=it->second.delta+(ops[i].mem.disp.has_displacement?ops[i].mem.disp.value:0);auto a=it->second.arg;if(ops[i].mem.index==ZYDIS_REGISTER_NONE&&!it->second.dynamic){if((disp==0||disp==4||disp==8||disp==12)&&ops[i].size>=32)f.fixed[a].insert(static_cast<int>(disp));}else ++f.dynamic[a];}
        if(zi.meta.category==ZYDIS_CATEGORY_COND_BR||zi.meta.category==ZYDIS_CATEGORY_UNCOND_BR){for(std::uint8_t i=0;i<zi.operand_count_visible;i++)if(ops[i].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&ops[i].imm.is_relative){auto t=std::uint64_t(pe.image_base)+cur+zi.length+ops[i].imm.value.s;if(t>=pe.image_base&&t-pe.image_base<cur)++f.back;}}
        // Propagate only simple pointer aliases. Other writes invalidate the tracked origin.
        if(zi.operand_count_visible&&ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER){auto dst=large(ops[0].reg.value);bool wrote=(ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)!=0;if(wrote){std::optional<Origin>n;if(zi.mnemonic==ZYDIS_MNEMONIC_MOV&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=orig.find(large(ops[1].reg.value));if(it!=orig.end())n=it->second;}else if(zi.mnemonic==ZYDIS_MNEMONIC_LEA&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY){auto it=orig.find(large(ops[1].mem.base));if(it!=orig.end()){n=it->second;n->delta+=ops[1].mem.disp.has_displacement?ops[1].mem.disp.value:0;if(ops[1].mem.index!=ZYDIS_REGISTER_NONE)n->dynamic=true;}}else if((zi.mnemonic==ZYDIS_MNEMONIC_ADD||zi.mnemonic==ZYDIS_MNEMONIC_SUB)&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=orig.find(dst);if(it!=orig.end()){n=it->second;n->dynamic=true;}}if(n)orig[dst]=*n;else orig.erase(dst);}}
        cur+=zi.length;
    }
    int best=-1,best_score=-1;std::size_t best_fixed=0;std::uint32_t best_dyn=0;for(int a=0;a<4;a++){auto fx=f.fixed[a].size();auto dy=f.dynamic[a];int score=(fx==4?200:0)+(dy>=2?150+int(dy):0)+int(fx);if(score>best_score){best=a;best_score=score;best_fixed=fx;best_dyn=dy;}}
    const bool key_shape=best>=0&&(best_fixed==4||best_dyn>=2);const bool crypto_shape=f.deltas>=1&&f.shift4>=2&&f.shift5>=2&&f.xors>=4&&f.addsub>=4&&f.back>=1;
    if(key_shape&&crypto_shape){f.valid=true;f.key_arg=best;if(best_fixed==4&&best_dyn==0)f.algorithm="TEA";else if(best_dyn>=2)f.algorithm="XTEA";else f.algorithm="TEA/XTEA-family";}return f;
}
const PeRuntimeFunction* containing_func(const PeInfo&pe,std::uint32_t rva){for(const auto&f:pe.exception.runtime_functions)if(f.begin_rva<=rva&&rva<f.end_rva)return &f;return nullptr;}
struct Decoded {std::uint32_t rva=0;ZydisDecodedInstruction zi{};std::array<ZydisDecodedOperand,ZYDIS_MAX_OPERAND_COUNT>ops{};};
std::vector<Decoded> decode_to(std::span<const std::uint8_t>d,const PeInfo&pe,const PeRuntimeFunction&rf,std::uint32_t stop){std::vector<Decoded>out;ZydisDecoder dec;if(!ZYAN_SUCCESS(ZydisDecoderInit(&dec,ZYDIS_MACHINE_MODE_LONG_64,ZYDIS_STACK_WIDTH_64)))return out;std::uint32_t cur=rf.begin_rva;while(cur<rf.end_rva&&cur<=stop&&out.size()<8192){auto o=rvaoff(pe,cur,d.size());if(!o)break;Decoded x;x.rva=cur;if(!ZYAN_SUCCESS(ZydisDecoderDecodeFull(&dec,d.data()+*o,std::min<std::size_t>(d.size()-*o,rf.end_rva-cur),&x.zi,x.ops.data()))||!x.zi.length)break;out.push_back(x);if(cur==stop)break;cur+=x.zi.length;}return out;}
struct Ptr {bool ok=false,stack=false,stack_load=false;std::uint64_t va=0;ZydisRegister stack_base=ZYDIS_REGISTER_NONE;std::int64_t stack_disp=0;std::string source;};
Ptr resolve_arg_pointer(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t callsite,int arg){Ptr out;if(arg<0||arg>3)return out;const auto*rf=containing_func(pe,callsite);if(!rf)return out;auto ins=decode_to(d,pe,*rf,callsite);if(ins.empty())return out;ZydisRegister cur=std::array<ZydisRegister,4>{ZYDIS_REGISTER_RCX,ZYDIS_REGISTER_RDX,ZYDIS_REGISTER_R8,ZYDIS_REGISTER_R9}[arg];std::int64_t pending=0;std::size_t seen=0;for(std::size_t z=ins.size();z-->0&&seen<96;){const auto&x=ins[z];if(x.rva==callsite)continue;++seen;if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur)continue;bool writes=(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)!=0;if(!writes)continue;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){const auto&s=x.ops[1];if(s.type==ZYDIS_OPERAND_TYPE_REGISTER){cur=large(s.reg.value);continue;}if(s.type==ZYDIS_OPERAND_TYPE_IMMEDIATE){out.va=s.imm.value.u+pending;out.ok=true;out.source="IMM_VA";return out;}}if(x.zi.mnemonic==ZYDIS_MNEMONIC_LEA&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY){const auto&m=x.ops[1].mem;if(m.index!=ZYDIS_REGISTER_NONE)return out;auto disp=m.disp.has_displacement?m.disp.value:0;if(large(m.base)==ZYDIS_REGISTER_RIP){out.va=pe.image_base+x.rva+x.zi.length+disp+pending;out.ok=true;out.source="RIP_GLOBAL";return out;}auto lb=large(m.base);if((lb==ZYDIS_REGISTER_RSP||lb==ZYDIS_REGISTER_RBP)&&pending==0){out.ok=true;out.stack=true;out.stack_base=lb;out.stack_disp=disp;out.source="STACK_LOCAL";return out;}if(m.base!=ZYDIS_REGISTER_NONE&&lb!=ZYDIS_REGISTER_RSP&&lb!=ZYDIS_REGISTER_RBP){pending+=disp;cur=lb;continue;}}return out;}return out;}
bool vector_move(ZydisMnemonic m){return m==ZYDIS_MNEMONIC_MOVAPS||m==ZYDIS_MNEMONIC_MOVUPS||m==ZYDIS_MNEMONIC_MOVDQA||m==ZYDIS_MNEMONIC_MOVDQU||m==ZYDIS_MNEMONIC_VMOVAPS||m==ZYDIS_MNEMONIC_VMOVUPS||m==ZYDIS_MNEMONIC_VMOVDQA||m==ZYDIS_MNEMONIC_VMOVDQU;}
struct StackBytes {bool ok=false;std::vector<std::uint8_t>bytes;std::string source;};
StackBytes reconstruct_stack_bytes(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t callsite,ZydisRegister base,std::int64_t target_disp,std::size_t length){
    StackBytes out;if(!length||length>4096)return out;out.bytes.assign(length,0);const auto*rf=containing_func(pe,callsite);if(!rf)return out;auto ins=decode_to(d,pe,*rf,callsite);if(ins.empty())return out;std::vector<bool>known(length,false);std::map<ZydisRegister,std::uint64_t>gpr;std::map<ZydisRegister,std::array<std::uint8_t,16>>vec;
    auto write=[&](std::int64_t disp,std::span<const std::uint8_t>src,bool have){auto a=disp-target_disp,b=a+static_cast<std::int64_t>(src.size());if(b<=0||a>=static_cast<std::int64_t>(length))return;auto lo=std::max<std::int64_t>(0,a),hi=std::min<std::int64_t>(static_cast<std::int64_t>(length),b);for(auto i=lo;i<hi;i++){if(have){out.bytes[static_cast<std::size_t>(i)]=src[static_cast<std::size_t>(i-a)];known[static_cast<std::size_t>(i)]=true;}else known[static_cast<std::size_t>(i)]=false;}};
    for(const auto&x:ins){if(x.rva==callsite)break;
        if(x.zi.operand_count_visible>=1&&x.ops[0].type==ZYDIS_OPERAND_TYPE_MEMORY&&(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)&&x.ops[0].mem.index==ZYDIS_REGISTER_NONE&&large(x.ops[0].mem.base)==base){auto disp=x.ops[0].mem.disp.has_displacement?x.ops[0].mem.disp.value:0;auto width=std::size_t(x.ops[0].size/8);bool handled=false;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){std::array<std::uint8_t,8>b{};if(x.ops[1].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&width&&width<=8){std::uint64_t v=x.ops[1].imm.value.u;if(width==8&&x.ops[1].size==32)v=static_cast<std::uint64_t>(static_cast<std::int64_t>(static_cast<std::int32_t>(v)));for(std::size_t k=0;k<width;k++)b[k]=std::uint8_t(v>>(8*k));write(disp,std::span<const std::uint8_t>(b.data(),width),true);handled=true;}else if(x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&width&&width<=8){auto it=gpr.find(large(x.ops[1].reg.value));if(it!=gpr.end()){for(std::size_t k=0;k<width;k++)b[k]=std::uint8_t(it->second>>(8*k));write(disp,std::span<const std::uint8_t>(b.data(),width),true);handled=true;}}}else if(vector_move(x.zi.mnemonic)&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&width==16){auto it=vec.find(x.ops[1].reg.value);if(it!=vec.end()){write(disp,it->second,true);handled=true;}}if(!handled&&width){std::array<std::uint8_t,32>z{};write(disp,std::span<const std::uint8_t>(z.data(),std::min<std::size_t>(width,z.size())),false);}}
        if(x.zi.operand_count_visible&&x.ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)){auto dst=large(x.ops[0].reg.value);std::optional<std::uint64_t>v;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){if(x.ops[1].type==ZYDIS_OPERAND_TYPE_IMMEDIATE){auto q=x.ops[1].imm.value.u;if(x.ops[0].size==64&&x.ops[1].size==32)q=static_cast<std::uint64_t>(static_cast<std::int64_t>(static_cast<std::int32_t>(q)));v=q;}else if(x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=gpr.find(large(x.ops[1].reg.value));if(it!=gpr.end())v=it->second;}}else if(x.zi.mnemonic==ZYDIS_MNEMONIC_XOR&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[1].reg.value)==dst)v=0;if(v)gpr[dst]=*v;else gpr.erase(dst);}
        if(x.zi.operand_count_visible&&x.ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&x.ops[0].size==128){auto dst=x.ops[0].reg.value;std::optional<std::array<std::uint8_t,16>>v;if(vector_move(x.zi.mnemonic)&&x.zi.operand_count_visible>=2){if(x.ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY&&large(x.ops[1].mem.base)==ZYDIS_REGISTER_RIP&&x.ops[1].mem.index==ZYDIS_REGISTER_NONE){auto disp=x.ops[1].mem.disp.has_displacement?x.ops[1].mem.disp.value:0;auto va=pe.image_base+x.rva+x.zi.length+disp;if(va>=pe.image_base&&va-pe.image_base<=0xffffffffull){auto rva=static_cast<std::uint32_t>(va-pe.image_base);auto o=rvaoff(pe,rva,d.size());auto*sec=section_for_rva(pe,rva);if(o&&sec&&!(sec->characteristics&0x20000000u)&&std::uint64_t(rva-sec->rva)+16<=sec->raw_size&&*o+16<=d.size()){std::array<std::uint8_t,16>a{};std::copy_n(d.begin()+static_cast<std::ptrdiff_t>(*o),16,a.begin());v=a;}}}else if(x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=vec.find(x.ops[1].reg.value);if(it!=vec.end())v=it->second;}}if(v)vec[dst]=*v;else vec.erase(dst);}
    }
    out.ok=std::all_of(known.begin(),known.end(),[](bool x){return x;});if(out.ok)out.source="STACK_MATERIALIZED";return out;
}
struct StackKey {bool ok=false;std::array<std::uint8_t,16>bytes{};std::string source;};
StackKey reconstruct_stack_key(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t callsite,ZydisRegister base,std::int64_t target_disp){StackKey o;auto b=reconstruct_stack_bytes(d,pe,callsite,base,target_disp,16);if(b.ok&&b.bytes.size()==16){o.ok=true;std::copy(b.bytes.begin(),b.bytes.end(),o.bytes.begin());o.source=b.source;}return o;}
std::string hexbytes(std::span<const std::uint8_t>d){std::ostringstream o;o<<std::hex<<std::setfill('0');for(auto b:d)o<<std::setw(2)<<unsigned(b);return o.str();}

struct ScalarValue {bool ok=false;std::uint64_t value=0;std::string source;};
ScalarValue resolve_arg_scalar(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t callsite,int arg){
    ScalarValue out;if(arg<0||arg>3)return out;const auto*rf=containing_func(pe,callsite);if(!rf)return out;auto ins=decode_to(d,pe,*rf,callsite);if(ins.empty())return out;ZydisRegister cur=std::array<ZydisRegister,4>{ZYDIS_REGISTER_RCX,ZYDIS_REGISTER_RDX,ZYDIS_REGISTER_R8,ZYDIS_REGISTER_R9}[arg];std::size_t seen=0;
    for(std::size_t z=ins.size();z-->0&&seen<96;){const auto&x=ins[z];if(x.rva==callsite)continue;++seen;if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)continue;
        if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){cur=large(q.reg.value);continue;}if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE){auto v=q.imm.value.u;if(x.ops[0].size==64&&q.size==32)v=static_cast<std::uint64_t>(static_cast<std::int64_t>(static_cast<std::int32_t>(v)));out.ok=true;out.value=v;out.source="IMM";return out;}}
        if(x.zi.mnemonic==ZYDIS_MNEMONIC_XOR&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[1].reg.value)==cur){out.ok=true;out.value=0;out.source="ZERO_XOR";return out;}return out;
    }return out;
}

ZydisRegister win64_arg_reg(int arg){static constexpr std::array<ZydisRegister,4>r={ZYDIS_REGISTER_RCX,ZYDIS_REGISTER_RDX,ZYDIS_REGISTER_R8,ZYDIS_REGISTER_R9};return arg>=0&&arg<4?r[static_cast<std::size_t>(arg)]:ZYDIS_REGISTER_NONE;}
std::string win64_arg_name(int arg){if(arg<4)return argname(arg);std::ostringstream o;o<<"STACK+0x"<<std::hex<<(0x20+8*(arg-4));return o.str();}
Ptr resolve_reg_pointer_before(std::span<const std::uint8_t>d,const PeInfo&pe,const std::vector<Decoded>&ins,std::size_t before,ZydisRegister start){Ptr out;auto cur=large(start);std::int64_t pending=0;std::size_t seen=0;for(std::size_t z=before;z-->0&&seen<128;){const auto&x=ins[z];++seen;if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)continue;
    if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){auto src=large(q.reg.value);if((src==ZYDIS_REGISTER_RSP||src==ZYDIS_REGISTER_RBP)&&pending==0){out.ok=true;out.stack=true;out.stack_base=src;out.stack_disp=0;out.source="STACK_LOCAL";return out;}cur=src;continue;}if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE){out.ok=true;out.va=q.imm.value.u+pending;out.source="IMM_VA";return out;}if(q.type==ZYDIS_OPERAND_TYPE_MEMORY&&q.mem.index==ZYDIS_REGISTER_NONE){auto b=large(q.mem.base);auto disp=q.mem.disp.has_displacement?q.mem.disp.value:0;if(b==ZYDIS_REGISTER_RSP||b==ZYDIS_REGISTER_RBP){out.ok=true;out.stack_load=true;out.stack_base=b;out.stack_disp=disp;out.source="STACK_LOAD";return out;}if(b==ZYDIS_REGISTER_RIP){auto pva=pe.image_base+x.rva+x.zi.length+disp; if(pva>=pe.image_base&&pva-pe.image_base<=0xffffffffull){auto po=rvaoff(pe,static_cast<std::uint32_t>(pva-pe.image_base),d.size());if(po&&*po+8<=d.size()){std::uint64_t v=0;for(int k=0;k<8;k++)v|=std::uint64_t(d[*po+k])<<(8*k);out.ok=true;out.va=v+pending;out.source="RIP_GLOBAL_PTR";return out;}}}}}
    if(x.zi.mnemonic==ZYDIS_MNEMONIC_LEA&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY){const auto&m=x.ops[1].mem;auto b=large(m.base);auto disp=m.disp.has_displacement?m.disp.value:0;if(m.index!=ZYDIS_REGISTER_NONE)return out;if(b==ZYDIS_REGISTER_RIP){out.ok=true;out.va=pe.image_base+x.rva+x.zi.length+disp+pending;out.source="RIP_GLOBAL";return out;}if((b==ZYDIS_REGISTER_RSP||b==ZYDIS_REGISTER_RBP)&&pending==0){out.ok=true;out.stack=true;out.stack_base=b;out.stack_disp=disp;out.source="STACK_LOCAL";return out;}if(b!=ZYDIS_REGISTER_NONE){pending+=disp;cur=b;continue;}}
    if((x.zi.mnemonic==ZYDIS_MNEMONIC_ADD||x.zi.mnemonic==ZYDIS_MNEMONIC_SUB)&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_IMMEDIATE){auto v=static_cast<std::int64_t>(x.ops[1].imm.value.s);pending+=x.zi.mnemonic==ZYDIS_MNEMONIC_ADD?v:-v;continue;}return out;}return out;}
ScalarValue resolve_reg_scalar_before(const std::vector<Decoded>&ins,std::size_t before,ZydisRegister start){ScalarValue out;auto cur=large(start);std::size_t seen=0;for(std::size_t z=before;z-->0&&seen<128;){const auto&x=ins[z];++seen;if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)continue;if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2){const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){cur=large(q.reg.value);continue;}if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE){auto v=q.imm.value.u;if(x.ops[0].size==64&&q.size==32)v=static_cast<std::uint64_t>(static_cast<std::int64_t>(static_cast<std::int32_t>(v)));out.ok=true;out.value=v;out.source="IMM";return out;}}if(x.zi.mnemonic==ZYDIS_MNEMONIC_XOR&&x.zi.operand_count_visible>=2&&x.ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&large(x.ops[1].reg.value)==cur){out.ok=true;out.value=0;out.source="ZERO_XOR";return out;}return out;}return out;}
bool stack_arg_store(const Decoded&x,std::int64_t disp){if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_MEMORY||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)return false;const auto&m=x.ops[0].mem;return large(m.base)==ZYDIS_REGISTER_RSP&&m.index==ZYDIS_REGISTER_NONE&&(m.disp.has_displacement?m.disp.value:0)==disp;}
Ptr resolve_win64_pointer_arg(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t callsite,int arg){Ptr out;const auto*rf=containing_func(pe,callsite);if(!rf)return out;auto ins=decode_to(d,pe,*rf,callsite);if(ins.empty())return out;auto call_index=ins.size()-1;if(arg<4)return resolve_reg_pointer_before(d,pe,ins,call_index,win64_arg_reg(arg));auto disp=std::int64_t(0x20+8*(arg-4));for(std::size_t z=call_index;z-->0;){const auto&x=ins[z];if(!stack_arg_store(x,disp))continue;if(x.zi.mnemonic!=ZYDIS_MNEMONIC_MOV||x.zi.operand_count_visible<2)return out;const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER)return resolve_reg_pointer_before(d,pe,ins,z,q.reg.value);if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE){out.ok=true;out.va=q.imm.value.u;out.source="STACK_ARG_IMM_VA";}return out;}return out;}
ScalarValue resolve_win64_scalar_arg(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t callsite,int arg){ScalarValue out;const auto*rf=containing_func(pe,callsite);if(!rf)return out;auto ins=decode_to(d,pe,*rf,callsite);if(ins.empty())return out;auto call_index=ins.size()-1;if(arg<4)return resolve_reg_scalar_before(ins,call_index,win64_arg_reg(arg));auto disp=std::int64_t(0x20+8*(arg-4));for(std::size_t z=call_index;z-->0;){const auto&x=ins[z];if(!stack_arg_store(x,disp))continue;if(x.zi.mnemonic!=ZYDIS_MNEMONIC_MOV||x.zi.operand_count_visible<2)return out;const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER)return resolve_reg_scalar_before(ins,z,q.reg.value);if(q.type==ZYDIS_OPERAND_TYPE_IMMEDIATE){out.ok=true;out.value=q.imm.value.u;out.source="STACK_ARG_IMM";}return out;}return out;}
std::optional<std::size_t> raw_cmp_256(std::span<const std::uint8_t>d,std::size_t o){
    if(o>=d.size())return{};
    if(d[o]==0x3d){if(o+5<=d.size()&&u32(d,o+1)==256)return 5;return{};}
    if(d[o]!=0x81||o+2>d.size())return{};
    auto m=d[o+1];if(((m>>3)&7)!=7)return{};auto mod=m>>6,rm=m&7;std::size_t p=o+2;
    if(mod!=3&&rm==4){if(p>=d.size())return{};auto sib=d[p++];if(mod==0&&(sib&7)==5)p+=4;}
    if(mod==0&&rm==5)p+=4;else if(mod==1)p+=1;else if(mod==2)p+=4;
    if(p+4>d.size()||u32(d,p)!=256)return{};
    return p+4-o;
}
bool raw_rc4_prefilter(std::span<const std::uint8_t>d,const PeInfo&pe,const PeRuntimeFunction&rf){auto b=rvaoff(pe,rf.begin_rva,d.size()),e=rvaoff(pe,rf.end_rva-1,d.size());if(!b||!e||*e<*b)return false;auto lo=*b,hi=std::min(d.size(),*e+1);std::uint32_t cmps=0,movzx8=0,stores8=0,divs=0;for(std::size_t p=lo;p<hi;){if((d[p]==0x81||d[p]==0x3d)&&raw_cmp_256(d,p)){++cmps;}if(p+1<hi&&d[p]==0x0f&&d[p+1]==0xb6)++movzx8;if(d[p]==0x88)++stores8;if(p+1<hi&&(d[p]==0xf6||d[p]==0xf7)&&(((d[p+1]>>3)&7)==6||((d[p+1]>>3)&7)==7))++divs;++p;}return cmps>=1&&divs>=1&&movzx8>=2&&stores8>=2;
}
struct Rc4Sem {
    bool valid=false;std::uint32_t begin=0,end=0;int state_arg=-1,key_arg=-1,keylen_arg=-1;
    std::array<std::uint32_t,4>identity_bytes{},indexed_byte_reads{},indexed_byte_writes{},div_uses{};
    std::uint32_t cmp256=0,back_edges=0,mix_adds=0,byte_truncations=0,instructions=0;
};
Rc4Sem analyze_rc4_function(std::span<const std::uint8_t>d,const PeInfo&pe,const PeRuntimeFunction&rf){
    Rc4Sem f;f.begin=rf.begin_rva;f.end=rf.end_rva;auto off=rvaoff(pe,rf.begin_rva,d.size());if(!off||rf.end_rva<=rf.begin_rva)return f;ZydisDecoder dec;if(!ZYAN_SUCCESS(ZydisDecoderInit(&dec,ZYDIS_MACHINE_MODE_LONG_64,ZYDIS_STACK_WIDTH_64)))return f;
    std::map<ZydisRegister,Origin>orig;orig[ZYDIS_REGISTER_RCX]={0,0,false};orig[ZYDIS_REGISTER_RDX]={1,0,false};orig[ZYDIS_REGISTER_R8]={2,0,false};orig[ZYDIS_REGISTER_R9]={3,0,false};std::map<std::pair<ZydisRegister,std::int64_t>,Origin>stack_orig;std::map<ZydisRegister,std::array<std::uint8_t,16>>vec;std::uint32_t cur=rf.begin_rva;
    while(cur<rf.end_rva&&f.instructions<4096){auto ro=rvaoff(pe,cur,d.size());if(!ro)break;ZydisDecodedInstruction zi{};ZydisDecodedOperand ops[ZYDIS_MAX_OPERAND_COUNT]{};auto avail=std::min<std::size_t>(d.size()-*ro,rf.end_rva-cur);if(!ZYAN_SUCCESS(ZydisDecoderDecodeFull(&dec,d.data()+*ro,avail,&zi,ops))||!zi.length)break;++f.instructions;
        for(std::uint8_t i=0;i<zi.operand_count_visible;i++)if(ops[i].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&!ops[i].imm.is_relative&&ops[i].imm.value.u==256)++f.cmp256;
        if(zi.mnemonic==ZYDIS_MNEMONIC_ADD&&zi.operand_count_visible&&(ops[0].size==8||ops[0].size==32||ops[0].size==64))++f.mix_adds;
        if(zi.mnemonic==ZYDIS_MNEMONIC_MOVZX&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER&&ops[1].size==8)++f.byte_truncations;
        if(zi.meta.category==ZYDIS_CATEGORY_COND_BR||zi.meta.category==ZYDIS_CATEGORY_UNCOND_BR){for(std::uint8_t i=0;i<zi.operand_count_visible;i++)if(ops[i].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&ops[i].imm.is_relative){auto t=std::uint64_t(pe.image_base)+cur+zi.length+ops[i].imm.value.s;if(t>=pe.image_base&&t-pe.image_base<cur)++f.back_edges;}}
        if(zi.mnemonic==ZYDIS_MNEMONIC_DIV||zi.mnemonic==ZYDIS_MNEMONIC_IDIV){for(std::uint8_t i=0;i<zi.operand_count_visible;i++)if(ops[i].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=orig.find(large(ops[i].reg.value));if(it!=orig.end()&&it->second.arg>=0)++f.div_uses[it->second.arg];}}
        // Indexed byte state/key accesses, and exact identity S-box materialization from RIP constants.
        for(std::uint8_t i=0;i<zi.operand_count_visible;i++)if(ops[i].type==ZYDIS_OPERAND_TYPE_MEMORY){auto it=orig.find(large(ops[i].mem.base));if(it==orig.end()||it->second.arg<0)continue;auto a=it->second.arg;auto disp=it->second.delta+(ops[i].mem.disp.has_displacement?ops[i].mem.disp.value:0);if((ops[i].mem.index!=ZYDIS_REGISTER_NONE||it->second.dynamic)&&ops[i].size==8){if(ops[i].actions&ZYDIS_OPERAND_ACTION_READ)++f.indexed_byte_reads[a];if(ops[i].actions&ZYDIS_OPERAND_ACTION_WRITE)++f.indexed_byte_writes[a];}
            if(ops[i].mem.index==ZYDIS_REGISTER_NONE&&(ops[i].actions&ZYDIS_OPERAND_ACTION_WRITE)&&ops[i].size==128&&zi.operand_count_visible>=2&&ops[0].type==ZYDIS_OPERAND_TYPE_MEMORY&&ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto vi=vec.find(ops[1].reg.value);if(vi!=vec.end()&&disp>=0&&disp+16<=256){bool exact=true;for(int k=0;k<16;k++)if(vi->second[k]!=static_cast<std::uint8_t>(disp+k)){exact=false;break;}if(exact)f.identity_bytes[a]+=16;}}
        }
        // Preserve argument origins through ordinary O0 stack spills/reloads.
        if(zi.mnemonic==ZYDIS_MNEMONIC_MOV&&zi.operand_count_visible>=2&&ops[0].type==ZYDIS_OPERAND_TYPE_MEMORY&&ops[0].mem.index==ZYDIS_REGISTER_NONE&&(large(ops[0].mem.base)==ZYDIS_REGISTER_RSP||large(ops[0].mem.base)==ZYDIS_REGISTER_RBP)&&ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=orig.find(large(ops[1].reg.value));auto k=std::make_pair(large(ops[0].mem.base),ops[0].mem.disp.has_displacement?ops[0].mem.disp.value:0);if(it!=orig.end())stack_orig[k]=it->second;else stack_orig.erase(k);}
        // Pointer-origin propagation.
        if(zi.operand_count_visible&&ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER){auto dst=large(ops[0].reg.value);if(ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE){std::optional<Origin>n;if(zi.mnemonic==ZYDIS_MNEMONIC_MOV&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=orig.find(large(ops[1].reg.value));if(it!=orig.end())n=it->second;}else if(zi.mnemonic==ZYDIS_MNEMONIC_MOV&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY&&ops[1].mem.index==ZYDIS_REGISTER_NONE&&(large(ops[1].mem.base)==ZYDIS_REGISTER_RSP||large(ops[1].mem.base)==ZYDIS_REGISTER_RBP)){auto k=std::make_pair(large(ops[1].mem.base),ops[1].mem.disp.has_displacement?ops[1].mem.disp.value:0);auto it=stack_orig.find(k);if(it!=stack_orig.end())n=it->second;}else if(zi.mnemonic==ZYDIS_MNEMONIC_LEA&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY){auto it=orig.find(large(ops[1].mem.base));if(it!=orig.end()){n=it->second;n->delta+=ops[1].mem.disp.has_displacement?ops[1].mem.disp.value:0;if(ops[1].mem.index!=ZYDIS_REGISTER_NONE)n->dynamic=true;}}else if((zi.mnemonic==ZYDIS_MNEMONIC_ADD||zi.mnemonic==ZYDIS_MNEMONIC_SUB)&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=orig.find(dst);if(it!=orig.end()){n=it->second;n->dynamic=true;}}if(n)orig[dst]=*n;else orig.erase(dst);}}
        // Vector constants used by optimized identity-S initialization.
        if(zi.operand_count_visible&&ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&ops[0].size==128){auto dst=ops[0].reg.value;std::optional<std::array<std::uint8_t,16>>v;if(vector_move(zi.mnemonic)&&zi.operand_count_visible>=2){if(ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY&&large(ops[1].mem.base)==ZYDIS_REGISTER_RIP&&ops[1].mem.index==ZYDIS_REGISTER_NONE){auto disp=ops[1].mem.disp.has_displacement?ops[1].mem.disp.value:0;auto va=pe.image_base+cur+zi.length+disp;if(va>=pe.image_base&&va-pe.image_base<=0xffffffffull){auto rva=static_cast<std::uint32_t>(va-pe.image_base);auto o=rvaoff(pe,rva,d.size());auto*sec=section_for_rva(pe,rva);if(o&&sec&&!(sec->characteristics&0x20000000u)&&std::uint64_t(rva-sec->rva)+16<=sec->raw_size&&*o+16<=d.size()){std::array<std::uint8_t,16>a{};std::copy_n(d.begin()+static_cast<std::ptrdiff_t>(*o),16,a.begin());v=a;}}}else if(ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=vec.find(ops[1].reg.value);if(it!=vec.end())v=it->second;}}if(v)vec[dst]=*v;else vec.erase(dst);}
        cur+=zi.length;
    }
    // Strong role assignment: state has full identity init plus indexed byte swap; key is another indexed byte-read arg; keylen feeds DIV/IDIV.
    for(int a=0;a<4;a++){const bool vector_identity=f.identity_bytes[a]>=240;const bool scalar_identity_loop=f.cmp256>=2&&f.back_edges>=2&&f.indexed_byte_writes[a]>=3&&f.indexed_byte_reads[a]>=1;if((vector_identity||scalar_identity_loop)&&(f.state_arg<0||f.identity_bytes[a]>f.identity_bytes[f.state_arg]))f.state_arg=a;}
    for(int a=0;a<4;a++)if(a!=f.state_arg&&f.indexed_byte_reads[a]>=1){if(f.key_arg<0||f.indexed_byte_reads[a]>f.indexed_byte_reads[f.key_arg])f.key_arg=a;}
    for(int a=0;a<4;a++)if(a!=f.state_arg&&a!=f.key_arg&&f.div_uses[a]){if(f.keylen_arg<0||f.div_uses[a]>f.div_uses[f.keylen_arg])f.keylen_arg=a;}
    f.valid=f.state_arg>=0&&f.key_arg>=0&&f.keylen_arg>=0&&f.cmp256>=1&&f.back_edges>=1&&f.mix_adds>=2&&(f.byte_truncations>=1||f.indexed_byte_writes[f.state_arg]>=2);return f;
}
std::vector<Rc4Sem> find_rc4_primitives(std::span<const std::uint8_t>d,const PeInfo&pe,const std::vector<std::uint64_t>&offs){std::set<std::uint32_t>starts;for(auto off:offs){auto r=offrva(pe,off);if(!r)continue;auto*f=containing_func(pe,*r);if(f&&raw_rc4_prefilter(d,pe,*f))starts.insert(f->begin_rva);}std::vector<Rc4Sem>out;for(auto b:starts){auto*f=containing_func(pe,b);if(!f)continue;auto x=analyze_rc4_function(d,pe,*f);if(x.valid)out.push_back(std::move(x));}return out;}

struct ImportedCall {std::string module,name;std::uint32_t callsite_rva=0,caller_begin=0,caller_end=0,iat_rva=0,thunk_rva=0;};
bool bcrypt_name(std::string_view n){return n=="BCryptOpenAlgorithmProvider"||n=="BCryptSetProperty"||n=="BCryptGenerateSymmetricKey"||n=="BCryptDecrypt"||n=="BCryptEncrypt";}
bool cryptoapi_name(std::string_view n){return n=="CryptAcquireContextW"||n=="CryptAcquireContextA"||n=="CryptImportKey"||n=="CryptSetKeyParam"||n=="CryptDecrypt"||n=="CryptEncrypt";}
bool openssl_name(std::string_view n){return n=="EVP_CIPHER_CTX_new"||n=="EVP_CIPHER_CTX_ctrl"||n=="EVP_get_cipherbyname"||n=="EVP_CIPHER_fetch"||n=="EVP_EncryptInit"||n=="EVP_DecryptInit"||n=="EVP_CipherInit"||n=="EVP_EncryptInit_ex"||n=="EVP_DecryptInit_ex"||n=="EVP_CipherInit_ex"||n=="EVP_EncryptInit_ex2"||n=="EVP_DecryptInit_ex2"||n=="EVP_CipherInit_ex2"||n.rfind("EVP_aes_",0)==0;}
using ImportPred=bool(*)(std::string_view);
std::vector<ImportedCall> find_import_calls(std::span<const std::uint8_t>d,const PeInfo&pe,ImportPred pred){
    std::map<std::uint32_t,std::pair<std::string,std::string>>iat;const std::uint32_t w=pe.pe64?8u:4u;for(const auto&m:pe.imports)for(std::size_t i=0;i<m.functions.size();++i){const auto&f=m.functions[i];if(!f.by_ordinal&&pred(f.name))iat[m.iat_rva+static_cast<std::uint32_t>(i)*w]={m.name,f.name};}if(iat.empty())return{};
    std::map<std::uint32_t,std::uint32_t>thunk_to_iat;for(const auto&s:pe.sections){if(!(s.characteristics&0x20000000u)||!s.raw_size||std::uint64_t(s.raw_offset)+s.raw_size>d.size())continue;for(std::size_t q=0;q+6<=s.raw_size;++q){auto fo=std::size_t(s.raw_offset)+q;if(d[fo]!=0xff||d[fo+1]!=0x25)continue;std::int32_t disp=0;std::memcpy(&disp,d.data()+fo+2,4);auto tr=std::int64_t(s.rva+q+6)+disp;if(tr>=0&&tr<=0xffffffffll&&iat.count(static_cast<std::uint32_t>(tr)))thunk_to_iat[s.rva+static_cast<std::uint32_t>(q)]=static_cast<std::uint32_t>(tr);}}
    std::vector<ImportedCall>out;std::set<std::uint32_t>seen;for(const auto&s:pe.sections){if(!(s.characteristics&0x20000000u)||!s.raw_size||std::uint64_t(s.raw_offset)+s.raw_size>d.size())continue;for(std::size_t q=0;q+5<=s.raw_size;++q){auto fo=std::size_t(s.raw_offset)+q;auto cr=s.rva+static_cast<std::uint32_t>(q);std::uint32_t ir=0,tr=0;bool hit=false;if(d[fo]==0xe8){std::int32_t disp=0;std::memcpy(&disp,d.data()+fo+1,4);auto x=std::int64_t(cr+5)+disp;if(x>=0&&x<=0xffffffffll){tr=static_cast<std::uint32_t>(x);auto it=thunk_to_iat.find(tr);if(it!=thunk_to_iat.end()){ir=it->second;hit=true;}}}else if(q+6<=s.raw_size&&d[fo]==0xff&&d[fo+1]==0x15){std::int32_t disp=0;std::memcpy(&disp,d.data()+fo+2,4);auto x=std::int64_t(cr+6)+disp;if(x>=0&&x<=0xffffffffll&&iat.count(static_cast<std::uint32_t>(x))){ir=static_cast<std::uint32_t>(x);hit=true;}}
        if(!hit||!seen.insert(cr).second)continue;
        auto*rf=containing_func(pe,cr);if(!rf)continue;const auto&nm=iat.at(ir);out.push_back({nm.first,nm.second,cr,rf->begin_rva,rf->end_rva,ir,tr});}}
    // Compilers may cache imported function pointers in nonvolatile registers:
    //   mov rbx,[rip+IAT] ; ... ; call rbx
    // Track those aliases inside PE64 RUNTIME_FUNCTION bounds so repeated API calls
    // normalize to the same ImportedCall representation without relying on one compiler's thunk style.
    if(pe.pe64&&pe.machine==0x8664&&!pe.exception.runtime_functions.empty()){
        ZydisDecoder dec;if(ZYAN_SUCCESS(ZydisDecoderInit(&dec,ZYDIS_MACHINE_MODE_LONG_64,ZYDIS_STACK_WIDTH_64))){
            auto volatile_reg=[](ZydisRegister r){r=large(r);return r==ZYDIS_REGISTER_RAX||r==ZYDIS_REGISTER_RCX||r==ZYDIS_REGISTER_RDX||r==ZYDIS_REGISTER_R8||r==ZYDIS_REGISTER_R9||r==ZYDIS_REGISTER_R10||r==ZYDIS_REGISTER_R11;};
            for(const auto&rf:pe.exception.runtime_functions){auto bo=rvaoff(pe,rf.begin_rva,d.size()),eo=rf.end_rva>rf.begin_rva?rvaoff(pe,rf.end_rva-1,d.size()):std::optional<std::size_t>{};if(!bo||!eo||*eo<*bo)continue;bool has_reg_call=false;for(std::size_t q=*bo;q+1<=*eo;++q)if(d[q]==0xff&&(d[q+1]>>6)==3&&((d[q+1]>>3)&7)==2){has_reg_call=true;break;}if(!has_reg_call)continue;std::map<ZydisRegister,std::uint32_t>alias;std::uint32_t cur=rf.begin_rva;while(cur<rf.end_rva){auto ro=rvaoff(pe,cur,d.size());if(!ro)break;ZydisDecodedInstruction zi{};ZydisDecodedOperand ops[ZYDIS_MAX_OPERAND_COUNT]{};if(!ZYAN_SUCCESS(ZydisDecoderDecodeFull(&dec,d.data()+*ro,std::min<std::size_t>(d.size()-*ro,rf.end_rva-cur),&zi,ops))||!zi.length)break;
                    if(zi.mnemonic==ZYDIS_MNEMONIC_MOV&&zi.operand_count_visible>=2&&ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER){auto dst=large(ops[0].reg.value);std::optional<std::uint32_t>v;const auto&q=ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=alias.find(large(q.reg.value));if(it!=alias.end())v=it->second;}else if(q.type==ZYDIS_OPERAND_TYPE_MEMORY&&q.mem.index==ZYDIS_REGISTER_NONE&&large(q.mem.base)==ZYDIS_REGISTER_RIP){auto disp=q.mem.disp.has_displacement?q.mem.disp.value:0;auto tr=std::int64_t(cur+zi.length)+disp;if(tr>=0&&tr<=0xffffffffll&&iat.count(static_cast<std::uint32_t>(tr)))v=static_cast<std::uint32_t>(tr);}if(v)alias[dst]=*v;else alias.erase(dst);}
                    else if(zi.operand_count_visible&&ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER&&(ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE))alias.erase(large(ops[0].reg.value));
                    if(zi.meta.category==ZYDIS_CATEGORY_CALL){std::uint32_t ir=0;if(zi.operand_count_visible>=1&&ops[0].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=alias.find(large(ops[0].reg.value));if(it!=alias.end())ir=it->second;}else if(zi.operand_count_visible>=1&&ops[0].type==ZYDIS_OPERAND_TYPE_MEMORY&&ops[0].mem.index==ZYDIS_REGISTER_NONE&&large(ops[0].mem.base)==ZYDIS_REGISTER_RIP){auto disp=ops[0].mem.disp.has_displacement?ops[0].mem.disp.value:0;auto tr=std::int64_t(cur+zi.length)+disp;if(tr>=0&&tr<=0xffffffffll&&iat.count(static_cast<std::uint32_t>(tr)))ir=static_cast<std::uint32_t>(tr);}if(ir&&seen.insert(cur).second){const auto&nm=iat.at(ir);out.push_back({nm.first,nm.second,cur,rf.begin_rva,rf.end_rva,ir,0});}for(auto it=alias.begin();it!=alias.end();){if(volatile_reg(it->first))it=alias.erase(it);else ++it;}}
                    cur+=zi.length;}}
        }
    }
    std::sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.callsite_rva<b.callsite_rva;});return out;
}
std::vector<ImportedCall> find_bcrypt_calls(std::span<const std::uint8_t>d,const PeInfo&pe){return find_import_calls(d,pe,bcrypt_name);}
std::vector<ImportedCall> find_cryptoapi_calls(std::span<const std::uint8_t>d,const PeInfo&pe){return find_import_calls(d,pe,cryptoapi_name);}
std::vector<ImportedCall> find_openssl_calls(std::span<const std::uint8_t>d,const PeInfo&pe){return find_import_calls(d,pe,openssl_name);}
std::optional<std::string> wide_ascii_ptr(std::span<const std::uint8_t>d,const PeInfo&pe,const Ptr&p,std::size_t max_chars=128){if(!p.ok||p.stack||p.stack_load||p.va<pe.image_base||p.va-pe.image_base>0xffffffffull)return{};auto r=static_cast<std::uint32_t>(p.va-pe.image_base);auto o=rvaoff(pe,r,d.size());if(!o)return{};std::string s;for(std::size_t i=0;i<max_chars&&*o+i*2+2<=d.size();++i){auto c=std::uint16_t(d[*o+i*2])|(std::uint16_t(d[*o+i*2+1])<<8);if(!c)return s;if(c<0x20||c>0x7e)return{};s.push_back(static_cast<char>(c));}return{};}
std::optional<std::string> ascii_ptr(std::span<const std::uint8_t>d,const PeInfo&pe,const Ptr&p,std::size_t max_chars=128){if(!p.ok||p.stack||p.stack_load||p.va<pe.image_base||p.va-pe.image_base>0xffffffffull)return{};auto r=static_cast<std::uint32_t>(p.va-pe.image_base);auto o=rvaoff(pe,r,d.size());if(!o)return{};std::string s;for(std::size_t i=0;i<max_chars&&*o+i<d.size();++i){auto c=d[*o+i];if(!c)return s;if(c<0x20||c>0x7e)return{};s.push_back(static_cast<char>(c));}return{};}
bool same_stack_slot(const Ptr&a,const Ptr&b){return a.ok&&b.ok&&(a.stack||a.stack_load)&&(b.stack||b.stack_load)&&a.stack_base==b.stack_base&&a.stack_disp==b.stack_disp;}
struct Blob {bool ok=false;std::uint32_t rva=0,size=0;std::string source,section,hex;std::vector<std::uint8_t> bytes;};
Blob resolve_blob(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t callsite,const Ptr&p,std::size_t len){Blob b;if(!p.ok||!len||len>4096)return b;if(p.stack&&!p.stack_load){auto x=reconstruct_stack_bytes(d,pe,callsite,p.stack_base,p.stack_disp,len);if(x.ok){b.ok=true;b.size=static_cast<std::uint32_t>(len);b.source=x.source;b.section="stack";b.bytes=x.bytes;b.hex=hexbytes(b.bytes);}return b;}if(p.stack||p.stack_load||p.va<pe.image_base||p.va-pe.image_base>0xffffffffull)return b;auto r=static_cast<std::uint32_t>(p.va-pe.image_base);auto o=rvaoff(pe,r,d.size());auto*sec=section_for_rva(pe,r);if(!o||!sec||(sec->characteristics&0x20000000u)||r<sec->rva||std::uint64_t(r-sec->rva)+len>sec->raw_size||*o+len>d.size())return b;b.ok=true;b.rva=r;b.size=static_cast<std::uint32_t>(len);b.source=p.source;b.section=sec->name;b.bytes.assign(d.begin()+static_cast<std::ptrdiff_t>(*o),d.begin()+static_cast<std::ptrdiff_t>(*o+len));b.hex=hexbytes(b.bytes);return b;}

struct ProviderCtx {std::uint32_t caller=0;Ptr handle_slot;std::string algorithm,mode;};
struct KeyCtx {CryptoKeyUse use;std::uint32_t caller=0;Ptr handle_slot;};
std::vector<CryptoKeyUse> detect_bcrypt_uses(std::span<const std::uint8_t>d,const PeInfo&pe){auto calls=find_bcrypt_calls(d,pe);if(calls.empty())return{};std::vector<ProviderCtx>providers;std::vector<KeyCtx>keys;
    for(const auto&c:calls){if(c.name!="BCryptOpenAlgorithmProvider")continue;auto slot=resolve_win64_pointer_arg(d,pe,c.callsite_rva,0);auto algp=resolve_win64_pointer_arg(d,pe,c.callsite_rva,1);auto alg=wide_ascii_ptr(d,pe,algp);if(!slot.stack||!alg||alg->empty())continue;providers.push_back({c.caller_begin,slot,*alg,{}});}
    for(const auto&c:calls){if(c.name!="BCryptSetProperty")continue;auto h=resolve_win64_pointer_arg(d,pe,c.callsite_rva,0);auto np=resolve_win64_pointer_arg(d,pe,c.callsite_rva,1);auto vp=resolve_win64_pointer_arg(d,pe,c.callsite_rva,2);auto vl=resolve_win64_scalar_arg(d,pe,c.callsite_rva,3);auto n=wide_ascii_ptr(d,pe,np),v=wide_ascii_ptr(d,pe,vp);if(!h.stack_load||!n||!v||!vl.ok||vl.value!=(v->size()+1)*2)continue;for(auto&ctx:providers)if(ctx.caller==c.caller_begin&&same_stack_slot(ctx.handle_slot,h)&&*n=="ChainingMode"){if(*v=="ChainingModeCBC")ctx.mode="CBC";else if(*v=="ChainingModeECB")ctx.mode="ECB";else if(*v=="ChainingModeCFB")ctx.mode="CFB";else if(*v=="ChainingModeCCM")ctx.mode="CCM";else if(*v=="ChainingModeGCM")ctx.mode="GCM";}}
    for(const auto&c:calls){if(c.name!="BCryptGenerateSymmetricKey")continue;auto halg=resolve_win64_pointer_arg(d,pe,c.callsite_rva,0);auto outslot=resolve_win64_pointer_arg(d,pe,c.callsite_rva,1);auto secret=resolve_win64_pointer_arg(d,pe,c.callsite_rva,4);auto len=resolve_win64_scalar_arg(d,pe,c.callsite_rva,5);ProviderCtx*provider=nullptr;for(auto&ctx:providers)if(ctx.caller==c.caller_begin&&same_stack_slot(ctx.handle_slot,halg)){provider=&ctx;break;}CryptoKeyUse u;u.function_rva=c.caller_begin;u.function_end_rva=c.caller_end;u.callsite_rva=c.callsite_rva;u.api_source="BCryptGenerateSymmetricKey";u.key_arg=win64_arg_name(4);u.key_length_arg=win64_arg_name(5);u.state="API_USE_CONFIRMED";u.algorithm=provider?"BCrypt-"+provider->algorithm:"BCrypt-SymmetricKey";if(provider&&!provider->mode.empty()){u.mode=provider->mode;u.algorithm+="-"+provider->mode;}u.evidence.push_back("BCryptGenerateSymmetricKey import call located and normalized through IAT/thunk mapping");if(provider){u.evidence.push_back("BCryptOpenAlgorithmProvider handle slot correlates to algorithm "+provider->algorithm);if(!provider->mode.empty())u.evidence.push_back("BCryptSetProperty on the same algorithm handle sets chaining mode "+provider->mode);}if(len.ok&&len.value>0&&len.value<=4096){u.key_length_resolved=true;u.key_length=len.value;u.key_size=static_cast<std::uint32_t>(len.value);u.evidence.push_back("Win64 stack argument backslice resolves symmetric-key secret length to "+std::to_string(len.value));auto b=resolve_blob(d,pe,c.callsite_rva,secret,static_cast<std::size_t>(len.value));if(b.ok){u.key_resolved=true;u.state="KEY_USE_CONFIRMED";u.key_rva=b.rva;u.key_source=b.source;u.key_section=b.section;u.key_hex=b.hex;u.evidence.push_back("secret pointer and exact secret length resolve to a bounded materialized key object");}}if(outslot.stack)keys.push_back({std::move(u),c.caller_begin,outslot});else keys.push_back({std::move(u),c.caller_begin,{}});}
    for(const auto&c:calls){if(c.name!="BCryptDecrypt"&&c.name!="BCryptEncrypt")continue;auto hk=resolve_win64_pointer_arg(d,pe,c.callsite_rva,0);if(!hk.stack_load)continue;for(auto&k:keys){if(k.caller!=c.caller_begin||!same_stack_slot(k.handle_slot,hk))continue;k.use.operation=c.name=="BCryptDecrypt"?"decrypt":"encrypt";k.use.evidence.push_back(c.name+" consumes the key handle produced by the correlated BCryptGenerateSymmetricKey call");auto ivp=resolve_win64_pointer_arg(d,pe,c.callsite_rva,4);auto ivl=resolve_win64_scalar_arg(d,pe,c.callsite_rva,5);k.use.iv_arg=win64_arg_name(4);k.use.iv_length_arg=win64_arg_name(5);if(ivl.ok&&ivl.value>0&&ivl.value<=4096){k.use.iv_length_resolved=true;k.use.iv_length=ivl.value;k.use.iv_size=static_cast<std::uint32_t>(ivl.value);auto b=resolve_blob(d,pe,c.callsite_rva,ivp,static_cast<std::size_t>(ivl.value));if(b.ok){k.use.iv_resolved=true;k.use.iv_rva=b.rva;k.use.iv_source=b.source;k.use.iv_section=b.section;k.use.iv_hex=b.hex;k.use.evidence.push_back(c.name+" IV pointer and length resolve to the pre-call IV bytes");}}break;}}
    std::vector<CryptoKeyUse>out;for(auto&k:keys)out.push_back(std::move(k.use));return out;}

struct CryptoApiProvCtx {std::uint32_t caller=0;Ptr handle_slot;};
struct CryptoApiKeyCtx {CryptoKeyUse use;std::uint32_t caller=0;Ptr handle_slot;};
std::optional<std::pair<std::string,std::uint32_t>> cryptoapi_aes_alg(std::uint32_t alg){if(alg==0x660e)return std::pair<std::string,std::uint32_t>{"AES-128",16};if(alg==0x660f)return std::pair<std::string,std::uint32_t>{"AES-192",24};if(alg==0x6610)return std::pair<std::string,std::uint32_t>{"AES-256",32};return{};}
std::string cryptoapi_mode(std::uint32_t m){switch(m){case 1:return"CBC";case 2:return"ECB";case 3:return"OFB";case 4:return"CFB";case 5:return"CTS";default:return{};}}
std::vector<CryptoKeyUse> detect_cryptoapi_uses(std::span<const std::uint8_t>d,const PeInfo&pe){auto calls=find_cryptoapi_calls(d,pe);if(calls.empty())return{};std::vector<CryptoApiProvCtx>providers;std::vector<CryptoApiKeyCtx>keys;
    for(const auto&c:calls){if(c.name!="CryptAcquireContextW"&&c.name!="CryptAcquireContextA")continue;auto slot=resolve_win64_pointer_arg(d,pe,c.callsite_rva,0);if(slot.stack)providers.push_back({c.caller_begin,slot});}
    for(const auto&c:calls){if(c.name!="CryptImportKey")continue;auto hp=resolve_win64_pointer_arg(d,pe,c.callsite_rva,0);auto bp=resolve_win64_pointer_arg(d,pe,c.callsite_rva,1);auto bl=resolve_win64_scalar_arg(d,pe,c.callsite_rva,2);auto pub=resolve_win64_scalar_arg(d,pe,c.callsite_rva,3);auto flags=resolve_win64_scalar_arg(d,pe,c.callsite_rva,4);auto outslot=resolve_win64_pointer_arg(d,pe,c.callsite_rva,5);if(!bl.ok||bl.value<12||bl.value>4096||!pub.ok||pub.value!=0||!flags.ok||flags.value!=0)continue;auto blob=resolve_blob(d,pe,c.callsite_rva,bp,static_cast<std::size_t>(bl.value));if(!blob.ok||blob.bytes.size()!=bl.value||blob.bytes.size()<12)continue;if(blob.bytes[0]!=8||blob.bytes[1]!=2||blob.bytes[2]!=0||blob.bytes[3]!=0)continue;auto alg=u32(blob.bytes,4),ks=u32(blob.bytes,8);auto ai=cryptoapi_aes_alg(alg);if(!ai||ks!=ai->second||bl.value!=12ull+ks)continue;
        CryptoKeyUse u;u.algorithm="CryptoAPI-"+ai->first;u.state="KEY_USE_CONFIRMED";u.function_rva=c.caller_begin;u.function_end_rva=c.caller_end;u.callsite_rva=c.callsite_rva;u.api_source="CryptImportKey";u.key_arg="PLAINTEXTKEYBLOB+12";u.key_length_arg="PLAINTEXTKEYBLOB.dwKeySize";u.key_length_resolved=true;u.key_length=ks;u.key_size=ks;u.key_resolved=true;u.key_rva=blob.rva?blob.rva+12:0;u.key_source="PLAINTEXTKEYBLOB:"+blob.source;u.key_section=blob.section;u.key_hex=hexbytes(std::span<const std::uint8_t>(blob.bytes).subspan(12,ks));u.evidence={"CryptImportKey call located through normalized import-call mapping","PLAINTEXTKEYBLOB header/version/reserved fields and exact blob length validate","AES ALG_ID and internal key length agree with the raw key bytes"};bool prov=false;for(const auto&ctx:providers)if(ctx.caller==c.caller_begin&&same_stack_slot(ctx.handle_slot,hp)){prov=true;break;}if(prov)u.evidence.push_back("CryptImportKey provider handle correlates to CryptAcquireContext output slot");if(outslot.stack)keys.push_back({std::move(u),c.caller_begin,outslot});else keys.push_back({std::move(u),c.caller_begin,{}});}
    for(const auto&c:calls){if(c.name!="CryptSetKeyParam")continue;auto hk=resolve_win64_pointer_arg(d,pe,c.callsite_rva,0);auto param=resolve_win64_scalar_arg(d,pe,c.callsite_rva,1);auto data=resolve_win64_pointer_arg(d,pe,c.callsite_rva,2);if(!hk.stack_load||!param.ok)continue;for(auto&k:keys){if(k.caller!=c.caller_begin||!same_stack_slot(k.handle_slot,hk))continue;if(param.value==1){auto b=resolve_blob(d,pe,c.callsite_rva,data,16);if(b.ok){k.use.iv_arg=win64_arg_name(2);k.use.iv_length_arg="AES block size";k.use.iv_length_resolved=true;k.use.iv_length=16;k.use.iv_resolved=true;k.use.iv_size=16;k.use.iv_rva=b.rva;k.use.iv_source=b.source;k.use.iv_section=b.section;k.use.iv_hex=b.hex;k.use.evidence.push_back("CryptSetKeyParam(KP_IV) on the imported AES key handle resolves a full 16-byte IV");}}else if(param.value==4){auto b=resolve_blob(d,pe,c.callsite_rva,data,4);if(b.ok&&b.bytes.size()==4){auto m=u32(b.bytes,0);auto nm=cryptoapi_mode(m);if(!nm.empty()){k.use.mode=nm;k.use.algorithm="CryptoAPI-AES-"+std::to_string(k.use.key_length*8)+"-"+nm;k.use.evidence.push_back("CryptSetKeyParam(KP_MODE) on the same key handle resolves mode "+nm);}}}break;}}
    for(const auto&c:calls){if(c.name!="CryptDecrypt"&&c.name!="CryptEncrypt")continue;auto hk=resolve_win64_pointer_arg(d,pe,c.callsite_rva,0);if(!hk.stack_load)continue;for(auto&k:keys){if(k.caller!=c.caller_begin||!same_stack_slot(k.handle_slot,hk))continue;k.use.operation=c.name=="CryptDecrypt"?"decrypt":"encrypt";k.use.evidence.push_back(c.name+" consumes the HCRYPTKEY produced by the correlated CryptImportKey call");break;}}
    std::vector<CryptoKeyUse>out;for(auto&k:keys)out.push_back(std::move(k.use));return out;}

struct ImportedReturnOrigin {std::string name;std::uint32_t callsite_rva=0;};
std::optional<ImportedReturnOrigin> imported_return_origin_info(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t callsite,int arg,const std::vector<ImportedCall>&calls){if(arg<0||arg>3)return{};const auto*rf=containing_func(pe,callsite);if(!rf)return{};auto ins=decode_to(d,pe,*rf,callsite);if(ins.empty())return{};std::map<std::uint32_t,const ImportedCall*>retcalls;for(const auto&c:calls)if(c.caller_begin==rf->begin_rva&&c.callsite_rva<callsite)retcalls[c.callsite_rva]=&c;auto cur=large(win64_arg_reg(arg));bool stack=false;ZydisRegister sb=ZYDIS_REGISTER_NONE;std::int64_t sd=0;std::size_t seen=0;for(std::size_t z=ins.size();z-->0&&seen<192;){const auto&x=ins[z];if(x.rva==callsite)continue;++seen;if(stack){if(x.zi.mnemonic==ZYDIS_MNEMONIC_MOV&&x.zi.operand_count_visible>=2&&x.ops[0].type==ZYDIS_OPERAND_TYPE_MEMORY&&(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)&&x.ops[0].mem.index==ZYDIS_REGISTER_NONE&&large(x.ops[0].mem.base)==sb&&(x.ops[0].mem.disp.has_displacement?x.ops[0].mem.disp.value:0)==sd){if(x.ops[1].type!=ZYDIS_OPERAND_TYPE_REGISTER)return{};cur=large(x.ops[1].reg.value);stack=false;}continue;}if(cur==ZYDIS_REGISTER_RAX){auto it=retcalls.find(x.rva);if(it!=retcalls.end())return ImportedReturnOrigin{it->second->name,it->second->callsite_rva};}if(!x.zi.operand_count_visible||x.ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||large(x.ops[0].reg.value)!=cur||(x.ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)continue;if(x.zi.mnemonic!=ZYDIS_MNEMONIC_MOV||x.zi.operand_count_visible<2)return{};const auto&q=x.ops[1];if(q.type==ZYDIS_OPERAND_TYPE_REGISTER){cur=large(q.reg.value);continue;}if(q.type==ZYDIS_OPERAND_TYPE_MEMORY&&q.mem.index==ZYDIS_REGISTER_NONE&&(large(q.mem.base)==ZYDIS_REGISTER_RSP||large(q.mem.base)==ZYDIS_REGISTER_RBP)){stack=true;sb=large(q.mem.base);sd=q.mem.disp.has_displacement?q.mem.disp.value:0;continue;}return{};}return{};}
struct EvpCipher {std::string algorithm,mode;std::uint32_t keylen=0,ivlen=0;bool variable_iv=false;};
std::optional<EvpCipher> evp_cipher_parts(int bits,std::string mode){if(bits!=128&&bits!=192&&bits!=256)return{};std::transform(mode.begin(),mode.end(),mode.begin(),[](unsigned char c){return char(std::tolower(c));});std::uint32_t iv=0;bool variable=false;if(mode=="cbc"||mode=="cfb"||mode=="cfb128"||mode=="cfb8"||mode=="cfb1"||mode=="ofb"||mode=="ctr")iv=16;else if(mode=="ecb")iv=0;else if(mode=="gcm"||mode=="ccm")variable=true;else return{};std::string up=mode;std::transform(up.begin(),up.end(),up.begin(),[](unsigned char c){return char(std::toupper(c));});return EvpCipher{"OpenSSL-EVP-AES-"+std::to_string(bits)+"-"+up,up,static_cast<std::uint32_t>(bits/8),iv,variable};}
std::optional<EvpCipher> evp_cipher(std::string_view n){std::string rest;if(n.rfind("EVP_aes_",0)==0){rest=std::string(n.substr(8));auto p=rest.find('_');if(p==std::string::npos)return{};int bits=0;try{bits=std::stoi(rest.substr(0,p));}catch(...){return{};}return evp_cipher_parts(bits,rest.substr(p+1));}std::string q(n);std::transform(q.begin(),q.end(),q.begin(),[](unsigned char c){return char(std::tolower(c));});if(q.rfind("aes-",0)!=0)return{};auto p=q.find('-',4);if(p==std::string::npos)return{};int bits=0;try{bits=std::stoi(q.substr(4,p-4));}catch(...){return{};}return evp_cipher_parts(bits,q.substr(p+1));}
struct EvpSelection {std::string selector,label;};
std::optional<EvpSelection> resolve_evp_selection(std::span<const std::uint8_t>d,const PeInfo&pe,const ImportedCall&init,const std::vector<ImportedCall>&calls){auto origin=imported_return_origin_info(d,pe,init.callsite_rva,1,calls);if(!origin)return{};if(evp_cipher(origin->name))return EvpSelection{origin->name,origin->name};const ImportedCall*src=nullptr;for(const auto&c:calls)if(c.callsite_rva==origin->callsite_rva){src=&c;break;}if(!src)return{};if(origin->name=="EVP_get_cipherbyname"){auto p=resolve_win64_pointer_arg(d,pe,src->callsite_rva,0);auto name=ascii_ptr(d,pe,p);if(!name||!evp_cipher(*name))return{};return EvpSelection{*name,"EVP_get_cipherbyname(\""+*name+"\")"};}if(origin->name=="EVP_CIPHER_fetch"){auto p=resolve_win64_pointer_arg(d,pe,src->callsite_rva,1);auto name=ascii_ptr(d,pe,p);if(!name||!evp_cipher(*name))return{};return EvpSelection{*name,"EVP_CIPHER_fetch(\""+*name+"\")"};}return{};}
struct EvpCtxState {std::string selector,label;std::optional<std::uint64_t> ivlen;};
struct EvpInitAbi {bool valid=false,engine_arg=false,cipher_direction=false;int key_arg=-1,iv_arg=-1,dir_arg=-1;std::string operation;};
EvpInitAbi evp_init_abi(std::string_view n){EvpInitAbi a;if(n=="EVP_EncryptInit_ex"){a.valid=true;a.engine_arg=true;a.key_arg=3;a.iv_arg=4;a.operation="encrypt";}else if(n=="EVP_DecryptInit_ex"){a.valid=true;a.engine_arg=true;a.key_arg=3;a.iv_arg=4;a.operation="decrypt";}else if(n=="EVP_CipherInit_ex"){a.valid=true;a.engine_arg=true;a.cipher_direction=true;a.key_arg=3;a.iv_arg=4;a.dir_arg=5;}else if(n=="EVP_EncryptInit_ex2"){a.valid=true;a.key_arg=2;a.iv_arg=3;a.operation="encrypt";}else if(n=="EVP_DecryptInit_ex2"){a.valid=true;a.key_arg=2;a.iv_arg=3;a.operation="decrypt";}else if(n=="EVP_CipherInit_ex2"){a.valid=true;a.cipher_direction=true;a.key_arg=2;a.iv_arg=3;a.dir_arg=4;}else if(n=="EVP_EncryptInit"){a.valid=true;a.key_arg=2;a.iv_arg=3;a.operation="encrypt";}else if(n=="EVP_DecryptInit"){a.valid=true;a.key_arg=2;a.iv_arg=3;a.operation="decrypt";}else if(n=="EVP_CipherInit"){a.valid=true;a.cipher_direction=true;a.key_arg=2;a.iv_arg=3;a.dir_arg=4;}return a;}
std::vector<CryptoKeyUse> detect_openssl_uses(std::span<const std::uint8_t>d,const PeInfo&pe){auto calls=find_openssl_calls(d,pe);std::vector<CryptoKeyUse>out;if(calls.empty())return out;std::map<std::uint32_t,EvpCtxState>ctx;
    auto ctx_id=[&](const ImportedCall&c)->std::optional<std::uint32_t>{auto x=imported_return_origin_info(d,pe,c.callsite_rva,0,calls);if(x&&x->name=="EVP_CIPHER_CTX_new")return x->callsite_rva;return{};};
    for(const auto&c:calls){
        if(c.name=="EVP_CIPHER_CTX_ctrl"){auto id=ctx_id(c);if(!id)continue;auto type=resolve_win64_scalar_arg(d,pe,c.callsite_rva,1),len=resolve_win64_scalar_arg(d,pe,c.callsite_rva,2),ptr=resolve_win64_scalar_arg(d,pe,c.callsite_rva,3);if(type.ok&&type.value==9&&len.ok&&len.value>0&&len.value<=4096&&ptr.ok&&ptr.value==0)ctx[*id].ivlen=len.value;continue;}
        auto abi=evp_init_abi(c.name);if(!abi.valid)continue;auto id=ctx_id(c);auto direct_sel=resolve_evp_selection(d,pe,c,calls);std::string selector,label;if(direct_sel){selector=direct_sel->selector;label=direct_sel->label;if(id){ctx[*id].selector=selector;ctx[*id].label=label;}}else if(id){auto it=ctx.find(*id);if(it!=ctx.end()){selector=it->second.selector;label=it->second.label;}}if(selector.empty())continue;auto ci=evp_cipher(selector);if(!ci)continue;if(abi.engine_arg){auto eng=resolve_win64_scalar_arg(d,pe,c.callsite_rva,2);if(!eng.ok||eng.value!=0)continue;}std::string operation=abi.operation;if(abi.cipher_direction){auto dir=resolve_win64_scalar_arg(d,pe,c.callsite_rva,abi.dir_arg);if(dir.ok&&dir.value==0)operation="decrypt";else if(dir.ok&&dir.value==1)operation="encrypt";}
        // A NULL key is a setup/reconfiguration call, not a key-use artifact. It may still establish context state above.
        auto key_scalar=resolve_win64_scalar_arg(d,pe,c.callsite_rva,abi.key_arg);if(key_scalar.ok&&key_scalar.value==0)continue;
        auto kp=resolve_win64_pointer_arg(d,pe,c.callsite_rva,abi.key_arg);auto kb=resolve_blob(d,pe,c.callsite_rva,kp,ci->keylen);CryptoKeyUse u;u.algorithm=ci->algorithm;u.mode=ci->mode;u.operation=operation;u.api_source=c.name;u.state="API_USE_CONFIRMED";u.function_rva=c.caller_begin;u.function_end_rva=c.caller_end;u.callsite_rva=c.callsite_rva;u.key_arg=win64_arg_name(abi.key_arg);u.key_length_arg=label.empty()?selector:label;u.key_length_resolved=true;u.key_length=ci->keylen;u.key_size=ci->keylen;u.evidence={"EVP Init-family import call located through normalized import-call mapping","cipher selection is tied to exact selector "+(label.empty()?selector:label)+(direct_sel?" by direct return-value flow":" by prior Init on the same EVP_CIPHER_CTX instance"),"selector fixes the AES key length and mode"};if(abi.engine_arg)u.evidence.push_back("ENGINE argument resolves to NULL");if(abi.cipher_direction){if(operation.empty())u.evidence.push_back("EVP_CipherInit direction argument is not proven as 0/1; operation left unlabeled");else u.evidence.push_back("EVP_CipherInit direction argument resolves to "+operation);}if(kb.ok){u.key_resolved=true;u.state="KEY_USE_CONFIRMED";u.key_rva=kb.rva;u.key_source=kb.source;u.key_section=kb.section;u.key_hex=kb.hex;u.evidence.push_back("EVP key pointer resolves to a complete bounded key object of selector-defined length");}
        if(ci->ivlen){auto ip=resolve_win64_pointer_arg(d,pe,c.callsite_rva,abi.iv_arg);auto ib=resolve_blob(d,pe,c.callsite_rva,ip,ci->ivlen);u.iv_arg=win64_arg_name(abi.iv_arg);u.iv_length_arg=selector+" IV size";u.iv_length_resolved=true;u.iv_length=ci->ivlen;u.iv_size=ci->ivlen;if(ib.ok){u.iv_resolved=true;u.iv_rva=ib.rva;u.iv_source=ib.source;u.iv_section=ib.section;u.iv_hex=ib.hex;u.evidence.push_back("EVP IV pointer resolves to the selector-defined IV length");}}
        else if(ci->variable_iv){u.iv_arg=win64_arg_name(abi.iv_arg);auto explicit_len=(id&&ctx.count(*id))?ctx[*id].ivlen:std::optional<std::uint64_t>{};if(explicit_len){u.iv_length_arg="EVP_CIPHER_CTX_ctrl(EVP_CTRL_AEAD_SET_IVLEN)";u.iv_length_resolved=true;u.iv_length=*explicit_len;u.iv_size=static_cast<std::uint32_t>(*explicit_len);auto ip=resolve_win64_pointer_arg(d,pe,c.callsite_rva,abi.iv_arg);auto ib=resolve_blob(d,pe,c.callsite_rva,ip,static_cast<std::size_t>(*explicit_len));if(ib.ok){u.iv_resolved=true;u.iv_rva=ib.rva;u.iv_source=ib.source;u.iv_section=ib.section;u.iv_hex=ib.hex;u.evidence.push_back("same EVP_CIPHER_CTX has explicit AEAD IV length "+std::to_string(*explicit_len)+" from EVP_CIPHER_CTX_ctrl; IV bytes resolve to that exact length");}}else{u.iv_length_arg="explicit AEAD IV-length control required";u.evidence.push_back("AEAD selector has configurable IV length; key is recoverable but IV bytes are deliberately not claimed without explicit IV-length evidence");}}
        out.push_back(std::move(u));}
    return out;}

struct AesNiSchedule {bool valid=false;std::uint32_t begin=0,end=0,bits=0,key_bytes=0;int key_arg=-1,round_arg=-1;std::vector<std::uint8_t>rcons;std::array<std::set<int>,4>reads,writes;};
struct AesNiConsumer {bool valid=false;std::uint32_t begin=0,end=0,bits=0;int round_arg=-1;std::string operation;std::uint32_t rounds=0,last=0,imc=0;std::array<std::set<int>,4>round_reads;};
void propagate_arg_origins(const ZydisDecodedInstruction&zi,const ZydisDecodedOperand*ops,std::map<ZydisRegister,Origin>&orig,std::map<std::pair<ZydisRegister,std::int64_t>,Origin>&stack_orig){
    if(zi.mnemonic==ZYDIS_MNEMONIC_MOV&&zi.operand_count_visible>=2&&ops[0].type==ZYDIS_OPERAND_TYPE_MEMORY&&ops[0].mem.index==ZYDIS_REGISTER_NONE&&(large(ops[0].mem.base)==ZYDIS_REGISTER_RSP||large(ops[0].mem.base)==ZYDIS_REGISTER_RBP)&&ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=orig.find(large(ops[1].reg.value));auto k=std::make_pair(large(ops[0].mem.base),ops[0].mem.disp.has_displacement?ops[0].mem.disp.value:0);if(it!=orig.end())stack_orig[k]=it->second;else stack_orig.erase(k);}
    if(!zi.operand_count_visible||ops[0].type!=ZYDIS_OPERAND_TYPE_REGISTER||(ops[0].actions&ZYDIS_OPERAND_ACTION_WRITE)==0)return;
    auto dst=large(ops[0].reg.value);std::optional<Origin>n;
    if(zi.mnemonic==ZYDIS_MNEMONIC_MOV&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=orig.find(large(ops[1].reg.value));if(it!=orig.end())n=it->second;}
    else if(zi.mnemonic==ZYDIS_MNEMONIC_MOV&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY&&ops[1].mem.index==ZYDIS_REGISTER_NONE&&(large(ops[1].mem.base)==ZYDIS_REGISTER_RSP||large(ops[1].mem.base)==ZYDIS_REGISTER_RBP)){auto k=std::make_pair(large(ops[1].mem.base),ops[1].mem.disp.has_displacement?ops[1].mem.disp.value:0);auto it=stack_orig.find(k);if(it!=stack_orig.end())n=it->second;}
    else if(zi.mnemonic==ZYDIS_MNEMONIC_LEA&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_MEMORY){auto it=orig.find(large(ops[1].mem.base));if(it!=orig.end()){n=it->second;n->delta+=ops[1].mem.disp.has_displacement?ops[1].mem.disp.value:0;if(ops[1].mem.index!=ZYDIS_REGISTER_NONE)n->dynamic=true;}}
    else if((zi.mnemonic==ZYDIS_MNEMONIC_ADD||zi.mnemonic==ZYDIS_MNEMONIC_SUB)&&zi.operand_count_visible>=2&&ops[1].type==ZYDIS_OPERAND_TYPE_REGISTER){auto it=orig.find(dst);if(it!=orig.end()){n=it->second;n->dynamic=true;}}
    if(n)orig[dst]=*n;else orig.erase(dst);
}
AesNiSchedule analyze_aesni_schedule(std::span<const std::uint8_t>d,const PeInfo&pe,const PeRuntimeFunction&rf){AesNiSchedule a;a.begin=rf.begin_rva;a.end=rf.end_rva;auto off=rvaoff(pe,rf.begin_rva,d.size());if(!off)return a;ZydisDecoder dec;if(!ZYAN_SUCCESS(ZydisDecoderInit(&dec,ZYDIS_MACHINE_MODE_LONG_64,ZYDIS_STACK_WIDTH_64)))return a;std::map<ZydisRegister,Origin>orig;orig[ZYDIS_REGISTER_RCX]={0,0,false};orig[ZYDIS_REGISTER_RDX]={1,0,false};orig[ZYDIS_REGISTER_R8]={2,0,false};orig[ZYDIS_REGISTER_R9]={3,0,false};std::map<std::pair<ZydisRegister,std::int64_t>,Origin>stack_orig;std::uint32_t cur=rf.begin_rva;
    while(cur<rf.end_rva){auto ro=rvaoff(pe,cur,d.size());if(!ro)break;ZydisDecodedInstruction zi{};ZydisDecodedOperand ops[ZYDIS_MAX_OPERAND_COUNT]{};if(!ZYAN_SUCCESS(ZydisDecoderDecodeFull(&dec,d.data()+*ro,std::min<std::size_t>(d.size()-*ro,rf.end_rva-cur),&zi,ops))||!zi.length)break;
        if(zi.mnemonic==ZYDIS_MNEMONIC_AESKEYGENASSIST){for(std::uint8_t i=0;i<zi.operand_count_visible;i++)if(ops[i].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&!ops[i].imm.is_relative)a.rcons.push_back(static_cast<std::uint8_t>(ops[i].imm.value.u));}
        for(std::uint8_t i=0;i<zi.operand_count_visible;i++)if(ops[i].type==ZYDIS_OPERAND_TYPE_MEMORY&&ops[i].size==128){auto it=orig.find(large(ops[i].mem.base));if(it==orig.end()||it->second.arg<0||it->second.dynamic||ops[i].mem.index!=ZYDIS_REGISTER_NONE)continue;auto disp=it->second.delta+(ops[i].mem.disp.has_displacement?ops[i].mem.disp.value:0);if(disp<0||disp>4096)continue;auto arg=it->second.arg;if(ops[i].actions&ZYDIS_OPERAND_ACTION_READ)a.reads[arg].insert(static_cast<int>(disp));if(ops[i].actions&ZYDIS_OPERAND_ACTION_WRITE)a.writes[arg].insert(static_cast<int>(disp));}
        propagate_arg_origins(zi,ops,orig,stack_orig);cur+=zi.length;}
    static constexpr std::array<std::uint8_t,10>R128={1,2,4,8,16,32,64,128,27,54};static constexpr std::array<std::uint8_t,13>R256={1,0,2,0,4,0,8,0,16,0,32,0,64};std::size_t round_count=0;if(a.rcons.size()==R128.size()&&std::equal(a.rcons.begin(),a.rcons.end(),R128.begin())){a.bits=128;a.key_bytes=16;round_count=11;}else if(a.rcons.size()==R256.size()&&std::equal(a.rcons.begin(),a.rcons.end(),R256.begin())){a.bits=256;a.key_bytes=32;round_count=15;}else return a;for(int k=0;k<4;k++){bool keyshape=a.reads[k].count(0);if(a.bits==256)keyshape=keyshape&&a.reads[k].count(16);if(keyshape&&a.key_arg<0)a.key_arg=k;}for(int k=0;k<4;k++){bool exact=a.writes[k].size()==round_count;for(std::size_t n=0;n<round_count&&exact;n++)if(!a.writes[k].count(static_cast<int>(n*16)))exact=false;if(exact){a.round_arg=k;break;}}a.valid=a.key_arg>=0&&a.round_arg>=0&&a.key_arg!=a.round_arg;return a;}
AesNiConsumer analyze_aesni_consumer(std::span<const std::uint8_t>d,const PeInfo&pe,const PeRuntimeFunction&rf){AesNiConsumer a;a.begin=rf.begin_rva;a.end=rf.end_rva;auto off=rvaoff(pe,rf.begin_rva,d.size());if(!off)return a;ZydisDecoder dec;if(!ZYAN_SUCCESS(ZydisDecoderInit(&dec,ZYDIS_MACHINE_MODE_LONG_64,ZYDIS_STACK_WIDTH_64)))return a;std::map<ZydisRegister,Origin>orig;orig[ZYDIS_REGISTER_RCX]={0,0,false};orig[ZYDIS_REGISTER_RDX]={1,0,false};orig[ZYDIS_REGISTER_R8]={2,0,false};orig[ZYDIS_REGISTER_R9]={3,0,false};std::map<std::pair<ZydisRegister,std::int64_t>,Origin>stack_orig;std::uint32_t enc=0,enclast=0,decnt=0,declast=0,cur=rf.begin_rva;
    while(cur<rf.end_rva){auto ro=rvaoff(pe,cur,d.size());if(!ro)break;ZydisDecodedInstruction zi{};ZydisDecodedOperand ops[ZYDIS_MAX_OPERAND_COUNT]{};if(!ZYAN_SUCCESS(ZydisDecoderDecodeFull(&dec,d.data()+*ro,std::min<std::size_t>(d.size()-*ro,rf.end_rva-cur),&zi,ops))||!zi.length)break;bool keyread=false;if(zi.mnemonic==ZYDIS_MNEMONIC_AESENC){++enc;keyread=true;}else if(zi.mnemonic==ZYDIS_MNEMONIC_AESENCLAST){++enclast;keyread=true;}else if(zi.mnemonic==ZYDIS_MNEMONIC_AESDEC){++decnt;keyread=true;}else if(zi.mnemonic==ZYDIS_MNEMONIC_AESDECLAST){++declast;keyread=true;}else if(zi.mnemonic==ZYDIS_MNEMONIC_AESIMC){++a.imc;keyread=true;}else if(zi.mnemonic==ZYDIS_MNEMONIC_PXOR)keyread=true;if(keyread){for(std::uint8_t i=0;i<zi.operand_count_visible;i++)if(ops[i].type==ZYDIS_OPERAND_TYPE_MEMORY&&ops[i].size==128&&(ops[i].actions&ZYDIS_OPERAND_ACTION_READ)){auto it=orig.find(large(ops[i].mem.base));if(it==orig.end()||it->second.arg<0||it->second.dynamic||ops[i].mem.index!=ZYDIS_REGISTER_NONE)continue;auto disp=it->second.delta+(ops[i].mem.disp.has_displacement?ops[i].mem.disp.value:0);if(disp>=0&&disp<=4096)a.round_reads[it->second.arg].insert(static_cast<int>(disp));}}
        propagate_arg_origins(zi,ops,orig,stack_orig);cur+=zi.length;}
    bool isenc=false;std::uint32_t rounds=0;if(enclast==1&&decnt==0&&declast==0&&a.imc==0&&(enc==9||enc==13)){isenc=true;rounds=enc;a.bits=enc==9?128:256;}else if(declast==1&&enc==0&&enclast==0&&(decnt==9||decnt==13)&&a.imc==decnt){rounds=decnt;a.bits=decnt==9?128:256;}else return a;auto lastoff=a.bits==128?160:224;for(int k=0;k<4;k++){bool exact=true;for(int off=0;off<=lastoff;off+=16)if(!a.round_reads[k].count(off)){exact=false;break;}if(exact){a.round_arg=k;break;}}if(a.round_arg<0)return a;a.valid=true;a.operation=isenc?"encrypt":"decrypt";a.rounds=rounds;a.last=1;return a;}

std::vector<AesNiSchedule> find_aesni_schedules(std::span<const std::uint8_t>d,const PeInfo&pe,const std::vector<std::uint64_t>&offs){std::set<std::uint32_t>starts;for(auto off:offs){auto r=offrva(pe,off);if(!r)continue;auto*sec=section_for_rva(pe,*r);if(!sec||!(sec->characteristics&0x20000000u))continue;if(auto*f=containing_func(pe,*r))starts.insert(f->begin_rva);}std::vector<AesNiSchedule>out;for(auto b:starts){auto*f=containing_func(pe,b);if(!f)continue;auto x=analyze_aesni_schedule(d,pe,*f);if(x.valid)out.push_back(std::move(x));}return out;}
std::vector<AesNiConsumer> find_aesni_consumers(std::span<const std::uint8_t>d,const PeInfo&pe,const std::vector<std::uint64_t>&offs){std::set<std::uint32_t>starts;for(auto off:offs){auto r=offrva(pe,off);if(!r)continue;auto*sec=section_for_rva(pe,*r);if(!sec||!(sec->characteristics&0x20000000u))continue;if(auto*f=containing_func(pe,*r))starts.insert(f->begin_rva);}std::vector<AesNiConsumer>out;for(auto b:starts){auto*f=containing_func(pe,b);if(!f)continue;auto x=analyze_aesni_consumer(d,pe,*f);if(x.valid)out.push_back(std::move(x));}return out;}
bool same_pointer_object(const Ptr&a,const Ptr&b){if(!a.ok||!b.ok)return false;if((a.stack||a.stack_load)&&(b.stack||b.stack_load))return a.stack_base==b.stack_base&&a.stack_disp==b.stack_disp;if(!a.stack&&!a.stack_load&&!b.stack&&!b.stack_load)return a.va==b.va;return false;}
std::optional<std::pair<std::string,std::uint32_t>> correlate_aesni_consumer(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t schedule_call,const Ptr&roundp,std::uint32_t bits,const std::vector<AesNiConsumer>&consumers){auto*caller=containing_func(pe,schedule_call);if(!caller)return{};for(const auto&c:consumers){if(c.bits!=bits)continue;std::vector<RangeRef>t={{c.begin,std::uint64_t(c.end)-c.begin,"AES-NI round consumer"}};auto refs=find_direct_control_refs(d,pe,t,64);for(const auto&r:refs){if(r.kind!="call"||r.target_rva!=c.begin||r.source_rva<=schedule_call||r.source_rva<caller->begin_rva||r.source_rva>=caller->end_rva)continue;auto p=resolve_win64_pointer_arg(d,pe,r.source_rva,c.round_arg);if(same_pointer_object(roundp,p))return std::pair<std::string,std::uint32_t>{c.operation,r.source_rva};}}return{};}
std::vector<FunctionSem> find_primitives(std::span<const std::uint8_t>d,const PeInfo&pe,const std::vector<std::uint64_t>&offs){std::set<std::uint32_t>starts;for(auto off:offs){auto r=offrva(pe,off);if(!r)continue;auto*sec=section_for_rva(pe,*r);if(!sec||!(sec->characteristics&0x20000000u))continue;if(auto*f=containing_func(pe,*r))starts.insert(f->begin_rva);}std::vector<FunctionSem>out;for(auto b:starts){auto*f=containing_func(pe,b);if(!f)continue;auto x=analyze_function(d,pe,*f);if(x.valid)out.push_back(std::move(x));}return out;}
}
bool has_crypto_api_imports(const PeInfo&pe){for(const auto&m:pe.imports)for(const auto&f:m.functions)if(!f.by_ordinal&&(bcrypt_name(f.name)||cryptoapi_name(f.name)||openssl_name(f.name)))return true;return false;}
CryptoInfo detect_crypto_key_uses(std::span<const std::uint8_t>d,const PeInfo&pe,const StaticScanReport&scan){CryptoInfo out;auto api=has_crypto_api_imports(pe);out.attempted=scan.hints.crypto||api;if(!out.attempted||!pe.valid||!pe.pe64||pe.machine!=0x8664||pe.exception.runtime_functions.empty())return out;auto funcs=find_primitives(d,pe,scan.crypto_delta_offsets);for(const auto&f:funcs){std::vector<RangeRef>target={{f.begin,std::uint64_t(f.end)-f.begin,"TEA-family function"}};auto refs=find_direct_control_refs(d,pe,target,128);bool emitted=false;for(const auto&r:refs){if(r.kind!="call"||r.target_rva!=f.begin)continue;CryptoKeyUse u;u.algorithm=f.algorithm;u.state="PRIMITIVE_CONFIRMED";u.function_rva=f.begin;u.function_end_rva=f.end;u.callsite_rva=r.source_rva;u.key_arg=argname(f.key_arg);u.fixed_key_offsets=f.fixed[f.key_arg].size();u.dynamic_key_accesses=f.dynamic[f.key_arg];u.shift4=f.shift4;u.shift5=f.shift5;u.xor_ops=f.xors;u.addsub_ops=f.addsub;u.back_edges=f.back;u.delta_constants=f.deltas;u.evidence={"TEA-family delta/sum constant used inside function","4-bit and 5-bit shifts plus XOR/add/sub loop semantics matched","key argument consumes four fixed 32-bit words or indexed key words","direct call into confirmed primitive located"};auto p=resolve_arg_pointer(d,pe,r.source_rva,f.key_arg);if(p.ok&&p.stack){auto sk=reconstruct_stack_key(d,pe,r.source_rva,p.stack_base,p.stack_disp);if(sk.ok){u.key_resolved=true;u.state="KEY_USE_CONFIRMED";u.key_size=16;u.key_source=sk.source;u.key_section="stack";u.key_hex=hexbytes(sk.bytes);u.evidence.push_back("callsite key argument resolves to a stack-local object whose 16 bytes are fully reconstructed from constant scalar/vector materialization");}}else if(p.ok&&p.va>=pe.image_base&&p.va-pe.image_base<=0xffffffffull){auto kr=static_cast<std::uint32_t>(p.va-pe.image_base);auto ko=rvaoff(pe,kr,d.size());auto*sec=section_for_rva(pe,kr);if(ko&&sec&&!(sec->characteristics&0x20000000u)&&kr>=sec->rva&&std::uint64_t(kr-sec->rva)+16<=sec->raw_size&&*ko+16<=d.size()){u.key_resolved=true;u.state="KEY_USE_CONFIRMED";u.key_rva=kr;u.key_size=16;u.key_source=p.source;u.key_section=sec->name;u.key_hex=hexbytes(d.subspan(*ko,16));u.evidence.push_back("callsite backward slice resolves key argument to a 16-byte non-executable PE object");}}
            out.uses.push_back(std::move(u));emitted=true;}
        if(!emitted){CryptoKeyUse u;u.algorithm=f.algorithm;u.state="PRIMITIVE_CONFIRMED";u.function_rva=f.begin;u.function_end_rva=f.end;u.key_arg=argname(f.key_arg);u.fixed_key_offsets=f.fixed[f.key_arg].size();u.dynamic_key_accesses=f.dynamic[f.key_arg];u.shift4=f.shift4;u.shift5=f.shift5;u.xor_ops=f.xors;u.addsub_ops=f.addsub;u.back_edges=f.back;u.delta_constants=f.deltas;u.evidence={"TEA-family primitive confirmed, but no direct caller/key pointer was resolved"};out.uses.push_back(std::move(u));}}
    auto aesni=find_aesni_schedules(d,pe,scan.crypto_aesni_schedule_offsets);auto aescons=find_aesni_consumers(d,pe,scan.crypto_aesni_round_offsets);for(const auto&s:aesni){std::vector<RangeRef>target={{s.begin,std::uint64_t(s.end)-s.begin,"AES-NI-128 key schedule"}};auto refs=find_direct_control_refs(d,pe,target,128);bool emitted=false;for(const auto&r:refs){if(r.kind!="call"||r.target_rva!=s.begin)continue;CryptoKeyUse u;u.algorithm="AES-NI-"+std::to_string(s.bits);u.state="PRIMITIVE_CONFIRMED";u.function_rva=s.begin;u.function_end_rva=s.end;u.callsite_rva=r.source_rva;u.key_arg=argname(s.key_arg);u.key_length_arg="AES-"+std::to_string(s.bits)+" Rcon schedule";u.key_length_resolved=true;u.key_length=s.key_bytes;u.key_size=s.key_bytes;std::string rcon=s.bits==128?"01,02,04,08,10,20,40,80,1b,36":"01,00,02,00,04,00,08,00,10,00,20,00,40";u.evidence={"AESKEYGENASSIST immediates match exact AES-"+std::to_string(s.bits)+" schedule sequence "+rcon,"raw-key argument provides the complete "+std::to_string(s.key_bytes)+"-byte AES key input","distinct round-key argument receives exactly "+std::to_string(s.bits==128?11:15)+" 128-bit round-key stores","direct caller into confirmed AES-NI key schedule located"};auto kp=resolve_win64_pointer_arg(d,pe,r.source_rva,s.key_arg);auto kb=resolve_blob(d,pe,r.source_rva,kp,s.key_bytes);if(kb.ok){u.key_resolved=true;u.state="KEY_USE_CONFIRMED";u.key_rva=kb.rva;u.key_source=kb.source;u.key_section=kb.section;u.key_hex=kb.hex;u.evidence.push_back("caller raw-key argument resolves to the complete AES key object");}auto rp=resolve_win64_pointer_arg(d,pe,r.source_rva,s.round_arg);if(auto op=correlate_aesni_consumer(d,pe,r.source_rva,rp,s.bits,aescons)){u.operation=op->first;std::ostringstream q;q<<"same round-key object flows to confirmed AES-NI "<<op->first<<" consumer at caller RVA 0x"<<std::hex<<op->second;u.evidence.push_back(q.str());}out.uses.push_back(std::move(u));emitted=true;}if(!emitted){CryptoKeyUse u;u.algorithm="AES-NI-"+std::to_string(s.bits);u.state="PRIMITIVE_CONFIRMED";u.function_rva=s.begin;u.function_end_rva=s.end;u.key_arg=argname(s.key_arg);u.key_length_arg="AES-"+std::to_string(s.bits)+" Rcon schedule";u.key_length_resolved=true;u.key_length=s.key_bytes;u.key_size=s.key_bytes;u.evidence={"exact AES-"+std::to_string(s.bits)+" AESKEYGENASSIST schedule and round-key layout confirmed, but no direct caller/raw key was resolved"};out.uses.push_back(std::move(u));}}
    auto rc4=find_rc4_primitives(d,pe,scan.crypto_rc4_offsets);for(const auto&f:rc4){std::vector<RangeRef>target={{f.begin,std::uint64_t(f.end)-f.begin,"RC4 KSA function"}};auto refs=find_direct_control_refs(d,pe,target,128);bool emitted=false;for(const auto&r:refs){if(r.kind!="call"||r.target_rva!=f.begin)continue;CryptoKeyUse u;u.algorithm="RC4-KSA";u.state="PRIMITIVE_CONFIRMED";u.function_rva=f.begin;u.function_end_rva=f.end;u.callsite_rva=r.source_rva;u.key_arg=argname(f.key_arg);u.key_length_arg=argname(f.keylen_arg);u.dynamic_key_accesses=f.indexed_byte_reads[f.key_arg];u.back_edges=f.back_edges;u.evidence={"256-byte identity S-box initialization recovered from native stores","KSA loop performs indexed key-byte reads, indexed state-byte reads/writes and byte swap semantics","key-length argument participates in DIV/IDIV modulo reduction","direct call into confirmed RC4 KSA located"};auto len=resolve_arg_scalar(d,pe,r.source_rva,f.keylen_arg);if(len.ok&&len.value>0&&len.value<=4096){u.key_length_resolved=true;u.key_length=len.value;u.key_size=static_cast<std::uint32_t>(len.value);u.evidence.push_back("caller backward slice resolves RC4 key length to "+std::to_string(len.value));auto ptr=resolve_arg_pointer(d,pe,r.source_rva,f.key_arg);if(ptr.ok&&!ptr.stack&&ptr.va>=pe.image_base&&ptr.va-pe.image_base<=0xffffffffull){auto kr=static_cast<std::uint32_t>(ptr.va-pe.image_base);auto ko=rvaoff(pe,kr,d.size());auto*sec=section_for_rva(pe,kr);if(ko&&sec&&!(sec->characteristics&0x20000000u)&&kr>=sec->rva&&std::uint64_t(kr-sec->rva)+len.value<=sec->raw_size&&*ko+len.value<=d.size()){u.key_resolved=true;u.state="KEY_USE_CONFIRMED";u.key_rva=kr;u.key_source=ptr.source;u.key_section=sec->name;u.key_hex=hexbytes(d.subspan(*ko,static_cast<std::size_t>(len.value)));u.evidence.push_back("caller key pointer and proven key length resolve to one non-executable PE object");}}}out.uses.push_back(std::move(u));emitted=true;}if(!emitted){CryptoKeyUse u;u.algorithm="RC4-KSA";u.state="PRIMITIVE_CONFIRMED";u.function_rva=f.begin;u.function_end_rva=f.end;u.key_arg=argname(f.key_arg);u.key_length_arg=argname(f.keylen_arg);u.dynamic_key_accesses=f.indexed_byte_reads[f.key_arg];u.back_edges=f.back_edges;u.evidence={"RC4 KSA primitive confirmed, but no direct caller/key pointer/key length was resolved"};out.uses.push_back(std::move(u));}}
    if(api){auto xs=detect_bcrypt_uses(d,pe);out.uses.insert(out.uses.end(),std::make_move_iterator(xs.begin()),std::make_move_iterator(xs.end()));auto ys=detect_cryptoapi_uses(d,pe);out.uses.insert(out.uses.end(),std::make_move_iterator(ys.begin()),std::make_move_iterator(ys.end()));auto zs=detect_openssl_uses(d,pe);out.uses.insert(out.uses.end(),std::make_move_iterator(zs.begin()),std::make_move_iterator(zs.end()));}
    out.valid=!out.uses.empty();return out;}
Finding crypto_finding(const CryptoInfo&i){Finding f;f.kind="crypto_key_use";f.family="Crypto key use";if(!i.valid){f.state="FAILED";return f;}auto confirmed=std::count_if(i.uses.begin(),i.uses.end(),[](const auto&u){return u.key_resolved;});auto api_count=std::count_if(i.uses.begin(),i.uses.end(),[](const auto&u){return !u.api_source.empty();});f.state=confirmed?"CONFIRMED":"LIKELY";f.variant=i.uses.front().algorithm;f.fields["primitive_count"]=std::to_string(i.uses.size());f.fields["resolved_key_uses"]=std::to_string(confirmed);f.fields["api_backed_uses"]=std::to_string(api_count);for(const auto&u:i.uses){std::ostringstream p;p<<u.algorithm<<" function RVA 0x"<<std::hex<<u.function_rva<<std::dec<<" key_arg="<<u.key_arg<<" state="<<u.state;if(u.callsite_rva)p<<" callsite=0x"<<std::hex<<u.callsite_rva<<std::dec;if(!u.api_source.empty())p<<" api="<<u.api_source;if(!u.mode.empty())p<<" mode="<<u.mode;if(!u.operation.empty())p<<" operation="<<u.operation;if(u.key_length_resolved)p<<" keylen="<<u.key_length;if(u.key_resolved){if(u.key_rva)p<<" key_rva=0x"<<std::hex<<u.key_rva<<std::dec;else p<<" key_source="<<u.key_source;p<<" key="<<u.key_hex;}if(u.iv_resolved)p<<" iv="<<u.iv_hex;f.evidence.push_back(p.str());f.ranges.push_back(rva_range(u.function_rva,std::uint64_t(u.function_end_rva)-u.function_rva,u.algorithm+" use/primitive"));if(u.key_resolved&&u.key_rva)f.ranges.push_back(rva_range(u.key_rva,u.key_size,"confirmed key object"));if(u.iv_resolved&&u.iv_rva)f.ranges.push_back(rva_range(u.iv_rva,u.iv_size,"confirmed IV object"));}f.suggested_actions.push_back("use recovered key/IV only with the identified primitive or API chain and recovered operation/mode/length; key use is structurally confirmed, not plaintext-validated");return f;}
}
