#!/usr/bin/env python3
import hashlib
import json
from pathlib import Path
import shutil
import struct
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
AUTO = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "build" / "auto-refirst"
PAK_MAGIC = 0x5A6F12E1
UTOC_MAGIC = b"-==--==--==--==-"


def analyze(path):
    cp = subprocess.run([str(AUTO), str(path), "--json"], text=True,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if cp.returncode:
        raise AssertionError((path, cp.returncode, cp.stdout[-1200:], cp.stderr[-2000:]))
    return json.loads(cp.stdout)


def analyze_text(path):
    cp = subprocess.run([str(AUTO), str(path)], text=True,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if cp.returncode:
        raise AssertionError((path, cp.returncode, cp.stdout[-1200:], cp.stderr[-2000:]))
    return cp.stdout



def pak_index(version, count=0, omit_modern_tail=False):
    mount = b"../../../Game/Content/\0"
    out = bytearray(struct.pack("<i", len(mount)) + mount + struct.pack("<I", count))
    if version >= 10:
        out += struct.pack("<QIII", 0, 0, 0, 0)
        if not omit_modern_tail:
            out += struct.pack("<I", 0)
    return bytes(out)


def build_pak(version, profile=None, encrypted=False, frozen=False, count=0,
              corrupt_hash=False, bad_range=False, omit_modern_tail=False,
              secondary=False, corrupt_secondary_hash=False,
              overlap_secondary=False):
    body = bytearray(b"source-generated-payload")
    index_offset = len(body)
    secondary_data = b""
    if secondary:
        assert version >= 10 and count == 0 and not omit_modern_tail
        mount = b"../../../Game/Content/\0"
        base = bytearray(struct.pack("<i", len(mount)) + mount + struct.pack("<I", 0))
        path_index = struct.pack("<I", 0)
        full_index = struct.pack("<I", 0)
        primary_size = len(base) + 8 + 40 + 40 + 4 + 4
        path_at = index_offset + primary_size
        full_at = path_at if overlap_secondary else path_at + len(path_index)
        path_hash = bytearray(hashlib.sha1(path_index).digest())
        if corrupt_secondary_hash:
            path_hash[0] ^= 0x80
        index = bytes(
            base + struct.pack("<Q", 0)
            + struct.pack("<IQQ", 1, path_at, len(path_index)) + path_hash
            + struct.pack("<IQQ", 1, full_at, len(full_index))
            + hashlib.sha1(full_index).digest()
            + struct.pack("<II", 0, 0)
        )
        secondary_data = path_index if overlap_secondary else path_index + full_index
        assert len(index) == primary_size
    else:
        index = pak_index(version, count, omit_modern_tail)
    body += index
    body += secondary_data
    digest = bytearray(hashlib.sha1(index).digest())
    if corrupt_hash:
        digest[0] ^= 0x80
    index_size = len(index)
    if bad_range:
        index_offset = 0xFFFFFFFFFFFFFF00
    if version <= 3:
        prefix = b""
        slots = 0
    elif version <= 6:
        prefix = bytes([int(encrypted)])
        slots = 0
    else:
        prefix = bytes(16) + bytes([int(encrypted)])
        slots = 0 if version == 7 else (4 if version == 8 and profile == "8A" else 5)
    footer = bytearray(prefix)
    footer += struct.pack("<IIQQ", PAK_MAGIC, version, index_offset, index_size)
    footer += digest
    if version == 9:
        footer += bytes([int(frozen)])
    names = [b"Zlib", b"Gzip", b"Oodle", b"LZ4", b"Zstd"]
    for name in names[:slots]:
        footer += name + bytes(32 - len(name))
    expected = {1: 44, 2: 44, 3: 44, 4: 45, 5: 45, 6: 45, 7: 61,
                9: 222, 10: 221, 11: 221, 12: 221}.get(version)
    if version == 8:
        expected = 189 if profile == "8A" else 221
    assert len(footer) == expected
    return bytes(body + footer)


def assert_pak_layout_oracle(blob, version, profile=None, secondary=False):
    # Independent byte-layout oracle derived from pinned repak footer.rs and
    # pak.rs. It decodes generated bytes instead of sharing builder offsets.
    profiles = {
        1: (44, 0, 0), 2: (44, 0, 0), 3: (44, 0, 0),
        4: (45, 1, 0), 5: (45, 1, 0), 6: (45, 1, 0),
        7: (61, 17, 0),
        9: (222, 17, 5), 10: (221, 17, 5),
        11: (221, 17, 5), 12: (221, 17, 5),
    }
    footer_size, magic_at, method_slots = (
        (189, 17, 4) if version == 8 and profile == "8A"
        else (221, 17, 5) if version == 8 and profile == "8B"
        else profiles[version]
    )
    footer_at = len(blob) - footer_size
    assert footer_at >= 0
    assert struct.unpack_from("<I", blob, footer_at + magic_at)[0] == PAK_MAGIC
    assert struct.unpack_from("<I", blob, footer_at + magic_at + 4)[0] == version
    index_at, index_size = struct.unpack_from("<QQ", blob, footer_at + magic_at + 8)
    assert index_at + index_size <= footer_at
    stored_sha1 = blob[footer_at + magic_at + 24:footer_at + magic_at + 44]
    assert stored_sha1 == hashlib.sha1(blob[index_at:index_at + index_size]).digest()

    if magic_at:
        encrypted_at = footer_at if version <= 6 else footer_at + 16
        assert blob[encrypted_at] in (0, 1)
    method_at = footer_at + magic_at + 44 + (1 if version == 9 else 0)
    assert len(blob[method_at:]) == method_slots * 32
    for slot in range(method_slots):
        raw = blob[method_at + slot * 32:method_at + (slot + 1) * 32]
        assert raw.rstrip(b"\0")

    cursor = index_at
    mount_len = struct.unpack_from("<i", blob, cursor)[0]
    cursor += 4
    assert mount_len > 1 and blob[cursor + mount_len - 1] == 0
    cursor += mount_len
    assert struct.unpack_from("<I", blob, cursor)[0] == 0
    cursor += 4
    if version >= 10:
        assert struct.unpack_from("<Q", blob, cursor)[0] == 0
        cursor += 8
        ranges = []
        for _ in range(2):
            present = struct.unpack_from("<I", blob, cursor)[0]
            cursor += 4
            assert present == int(secondary)
            if present:
                offset, size = struct.unpack_from("<QQ", blob, cursor)
                stored = blob[cursor + 16:cursor + 36]
                cursor += 36
                assert index_at + index_size <= offset < offset + size <= footer_at
                assert stored == hashlib.sha1(blob[offset:offset + size]).digest()
                ranges.append((offset, offset + size))
        encoded_size = struct.unpack_from("<I", blob, cursor)[0]
        cursor += 4 + encoded_size
        assert struct.unpack_from("<I", blob, cursor)[0] == 0
        cursor += 4
        assert not secondary or ranges[0][1] <= ranges[1][0]
    assert cursor == index_at + index_size
    assert secondary or cursor == footer_at


def be5(value):
    return value.to_bytes(5, "big")


def le5(value):
    return value.to_bytes(5, "little")


def le3(value):
    return value.to_bytes(3, "little")


def build_utoc(version=5, partitions=1, encrypted=False, signed=False,
               duplicate_ids=False, overlap=False, bad_method=False,
               budget=False, trailing=False):
    if budget:
        entry_count = 1_000_001
        block_count = 0
    else:
        entry_count = partitions
        block_count = partitions
    methods = [b"Zlib"]
    directory = bytes(16) if encrypted else b""
    flags = 1 | 8
    if encrypted:
        flags |= 2
    if signed:
        flags |= 4
    partition_size = 64
    header = bytearray(144)
    header[:16] = UTOC_MAGIC
    header[16] = version
    struct.pack_into("<IIIIIIII", header, 20, 144, entry_count, block_count, 12,
                     len(methods), 32, 65536, len(directory))
    struct.pack_into("<I", header, 52, partitions)
    struct.pack_into("<Q", header, 56, 0x1234)
    header[80] = flags
    seeds = entry_count if version >= 4 and not budget else 0
    overflow = 0
    struct.pack_into("<I", header, 84, seeds)
    struct.pack_into("<Q", header, 88, partition_size)
    struct.pack_into("<I", header, 96, overflow)
    if budget:
        return bytes(header)
    chunk_ids = bytearray()
    logical = bytearray()
    blocks = bytearray()
    for i in range(entry_count):
        identity = 0 if duplicate_ids else i + 1
        suffix = 0 if duplicate_ids else i & 0xFF
        chunk_ids += struct.pack("<Q", identity) + bytes([suffix, 0, 0, 1])
        logical += be5(i * 65536) + be5(16)
    for i in range(block_count):
        offset = i * partition_size
        if overlap and i == 1:
            offset = 8
        method = 2 if bad_method and i == 0 else 1
        blocks += le5(offset) + le3(16) + le3(16) + bytes([method])
    seed_data = bytes(seeds * 4)
    method_data = b"".join(name + bytes(32 - len(name)) for name in methods)
    signed_data = b""
    if signed:
        signed_data = struct.pack("<I", 20) + bytes(40) + bytes(block_count * 20)
    meta_width = 24 if version >= 8 else 33
    toc = bytes(header + chunk_ids + logical + seed_data + blocks + method_data +
                signed_data + directory + bytes(entry_count * meta_width))
    return toc + (b"X" if trailing else b"")


def assert_state(path, kind, state):
    report = analyze(path)
    u = report["unreal_container"]
    assert u["kind"] == kind and u["state"] == state, (path, u)
    return report


def main():
    with tempfile.TemporaryDirectory(prefix="auto-refirst-unreal-") as td:
        td = Path(td)

        profiles = [(version, None) for version in range(1, 8)]
        profiles += [(8, "8A"), (8, "8B")]
        profiles += [(version, None) for version in range(9, 13)]
        for version, profile in profiles:
            path = td / f"good-v{version}-{profile or 'core'}.pak"
            data = build_pak(version, profile)
            assert_pak_layout_oracle(data, version, profile)
            path.write_bytes(data)
            r = assert_state(path, "pak", "CONFIRMED")
            p = r["unreal_container"]["pak"]
            assert p["valid"] and p["index_hash_matches"] and p["index_header_valid"]
            assert p["footer_profile"] != "" and p["entry_count"] == 0
            f = next(x for x in r["findings"] if x["family"] == "Unreal Engine Pak")
            assert f["state"] == "CONFIRMED"
            assert f["fields"]["asset_semantics_enumerated"] == "false"

        secondary_pak = td / "secondary-v11.pak"
        secondary_data = build_pak(11, secondary=True)
        assert_pak_layout_oracle(secondary_data, 11, secondary=True)
        secondary_pak.write_bytes(secondary_data)
        sr = assert_state(secondary_pak, "pak", "CONFIRMED")
        sp = sr["unreal_container"]["pak"]
        assert sp["secondary_index_count"] == 2
        assert sp["secondary_index_hashes_checked"]
        assert sp["secondary_index_hashes_match"]
        secondary_bad_hash = td / "secondary-bad-hash.pak"
        secondary_bad_hash.write_bytes(
            build_pak(11, secondary=True, corrupt_secondary_hash=True)
        )
        assert_state(secondary_bad_hash, "pak", "FAILED")
        secondary_overlap = td / "secondary-overlap.pak"
        secondary_overlap.write_bytes(
            build_pak(11, secondary=True, overlap_secondary=True)
        )
        assert_state(secondary_overlap, "pak", "FAILED")

        bad_sha = td / "bad-sha.pak"
        bad_sha.write_bytes(build_pak(11, corrupt_hash=True))
        assert_state(bad_sha, "pak", "FAILED")
        bad_range = td / "bad-range.pak"
        bad_range.write_bytes(build_pak(3, bad_range=True))
        truncated_index = td / "truncated-modern-index.pak"
        truncated_index.write_bytes(build_pak(11, omit_modern_tail=True))
        rt = assert_state(truncated_index, "pak", "FAILED")
        tp = rt["unreal_container"]["pak"]
        assert tp["index_hash_matches"] and not tp["index_header_valid"]

        assert_state(bad_range, "pak", "FAILED")
        encrypted_pak = td / "encrypted.pak"
        encrypted_pak.write_bytes(build_pak(7, encrypted=True))
        rp = assert_state(encrypted_pak, "pak", "PARTIAL")
        assert rp["unreal_container"]["pak"]["encrypted_index"]
        frozen_pak = td / "frozen.pak"
        frozen_pak.write_bytes(build_pak(9, frozen=True))
        assert_state(frozen_pak, "pak", "PARTIAL")
        budget_pak = td / "budget.pak"
        budget_pak.write_bytes(build_pak(3, count=1_000_001))
        rb = assert_state(budget_pak, "pak", "PARTIAL")
        assert rb["unreal_container"]["pak"]["budget_exhausted"]
        bait = td / "bait.bin"
        bait.write_bytes(b"x" * 300 + struct.pack("<I", PAK_MAGIC) + b"not-a-footer")
        assert analyze(bait)["unreal_container"]["candidate"] is False
        unknown_pak = bytearray(build_pak(12))
        struct.pack_into("<I", unknown_pak, len(unknown_pak) - 221 + 21, 13)
        unknown_pak_path = td / "unknown-version.bin"
        unknown_pak_path.write_bytes(unknown_pak)
        up = assert_state(unknown_pak_path, "pak", "PARTIAL")
        assert up["unreal_container"]["pak"]["version"] == 13
        assert not up["unreal_container"]["pak"]["supported_version"]
        renamed = td / "renamed.utoc"
        renamed.write_bytes(build_pak(3))
        assert_state(renamed, "pak", "CONFIRMED")

        pair_dir = td / "single"
        pair_dir.mkdir()
        toc = pair_dir / "game.utoc"
        ucas = pair_dir / "game.ucas"
        toc.write_bytes(build_utoc(version=5))
        ucas.write_bytes(bytes(16))
        ri = assert_state(toc, "iostore-utoc", "CONFIRMED")
        io = ri["unreal_container"]["iostore"]
        assert io["toc_valid"] and io["pair_valid"] and io["partition_count"] == 1
        assert io["content_readable"] is False
        rels = [x for x in ri["artifact_relationships"]
                if x["kind"] == "unreal_iostore_partition"]
        assert len(rels) == 1 and rels[0]["state"] == "CONFIRMED"
        assert rels[0]["evidence_level"] == "R2_STRUCTURAL_RELATION"
        assert rels[0]["priority_eligible"] is False

        directory_report = analyze(pair_dir)
        drels = [x for x in directory_report["directory_plan"]["relationships"]
                 if x["kind"] == "unreal_iostore_partition"]
        assert len(drels) == 1 and drels[0]["state"] == "CONFIRMED"
        toc_report = next(x for x in directory_report["reports"]
                          if x["input"].endswith("game.utoc"))
        assert toc_report["unreal_container"]["iostore"]["pair_valid"]

        split_dir = td / "split"
        split_dir.mkdir()
        split_toc = split_dir / "global.utoc"
        split_toc.write_bytes(build_utoc(version=8, partitions=2, signed=True))
        (split_dir / "global.ucas").write_bytes(bytes(16))
        (split_dir / "global_s1.ucas").write_bytes(bytes(16))
        rs = assert_state(split_toc, "iostore-utoc", "CONFIRMED")
        assert len(rs["unreal_container"]["iostore"]["partitions"]) == 2
        sio = rs["unreal_container"]["iostore"]
        assert sio["signed_flag"]
        assert sio["signature_table_structurally_present"]
        assert sio["signature_verification_performed"] is False
        sf = next(x for x in rs["findings"] if x["family"] == "Unreal Engine IoStore")
        assert sf["fields"]["signature_verification_performed"] == "false"
        assert sf["fields"]["content_readable"] == "false"
        text_report = analyze_text(split_toc)
        assert "signature_table=STRUCTURALLY_PRESENT" in text_report
        assert "cryptographic_verification=NOT_PERFORMED" in text_report

        (split_dir / "global_s1.ucas").unlink()
        missing = assert_state(split_toc, "iostore-utoc", "PARTIAL")
        assert missing["unreal_container"]["iostore"]["toc_valid"]
        assert not missing["unreal_container"]["iostore"]["pair_valid"]
        (split_dir / "global_s1.ucas").write_bytes(bytes(16))
        (split_dir / "global_s2.ucas").write_bytes(b"")
        assert_state(split_toc, "iostore-utoc", "PARTIAL")
        (split_dir / "global_s2.ucas").unlink()

        encrypted_dir = td / "encrypted-io"
        encrypted_dir.mkdir()
        etoc = encrypted_dir / "enc.utoc"
        etoc.write_bytes(build_utoc(encrypted=True))
        (encrypted_dir / "enc.ucas").write_bytes(bytes(16))
        re = assert_state(etoc, "iostore-utoc", "PARTIAL")
        assert re["unreal_container"]["iostore"]["toc_valid"]
        assert re["unreal_container"]["iostore"]["pair_valid"]
        erel = next(x for x in re["artifact_relationships"]
                    if x["kind"] == "unreal_iostore_partition")
        assert erel["state"] == "BOUNDED"

        mutation_dir = td / "mutations"
        mutation_dir.mkdir()
        (mutation_dir / "bad.ucas").write_bytes(bytes(256))
        mutations = {
            "duplicate.utoc": build_utoc(partitions=2, duplicate_ids=True),
            "overlap.utoc": build_utoc(partitions=2, overlap=True),
            "method.utoc": build_utoc(bad_method=True),
            "trailing.utoc": build_utoc(trailing=True),
            "truncated.utoc": UTOC_MAGIC + bytes(20),
        }
        for name, data in mutations.items():
            path = mutation_dir / name
            path.write_bytes(data)
            report = assert_state(path, "iostore-utoc", "FAILED")
            assert not report["unreal_container"]["valid"]
        unknown = mutation_dir / "unknown.utoc"
        unknown.write_bytes(build_utoc(version=5)[:16] + bytes([9]) +
                            build_utoc(version=5)[17:])
        assert_state(unknown, "iostore-utoc", "PARTIAL")
        over_budget = mutation_dir / "budget.utoc"
        over_budget.write_bytes(build_utoc(budget=True))
        rb = assert_state(over_budget, "iostore-utoc", "PARTIAL")
        assert rb["unreal_container"]["iostore"]["budget_exhausted"]

        standalone = td / "standalone.ucas"
        standalone.write_bytes(b"opaque-cas-data")
        ra = assert_state(standalone, "iostore-ucas", "PARTIAL")
        assert not ra["unreal_container"]["iostore"]["toc_valid"]

        case_dir = td / "case"
        case_dir.mkdir()
        ctoc = case_dir / "case.utoc"
        ctoc.write_bytes(build_utoc())
        (case_dir / "case.ucas").write_bytes(bytes(16))
        (case_dir / "CASE.UCAS").write_bytes(bytes(16))
        assert_state(ctoc, "iostore-utoc", "PARTIAL")

    print("[PASS] source-generated Unreal Pak exact footer/index/hash profiles + IoStore UTOC/UCAS bounded pair geometry and malformed/budget negatives")


if __name__ == "__main__":
    main()
