#include "prts/dotnet.hpp"
#include <algorithm>
#include <array>
#include <cctype>
#include <cstring>
#include <fstream>
#include <functional>
#include <iomanip>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string_view>
namespace prts { namespace {
std::uint16_t u16(std::span<const std::uint8_t>d,std::size_t o){if(o+2>d.size())return 0;return std::uint16_t(d[o])|(std::uint16_t(d[o+1])<<8);}
std::uint32_t u32(std::span<const std::uint8_t>d,std::size_t o){if(o+4>d.size())return 0;return std::uint32_t(d[o])|(std::uint32_t(d[o+1])<<8)|(std::uint32_t(d[o+2])<<16)|(std::uint32_t(d[o+3])<<24);}
std::uint64_t u64(std::span<const std::uint8_t>d,std::size_t o){if(o+8>d.size())return 0;std::uint64_t v=0;for(int i=7;i>=0;--i)v=(v<<8)|d[o+i];return v;}
std::optional<std::size_t> rvaoff(const PeInfo&pe,std::uint32_t rva,std::size_t n){if(rva<pe.headers_size&&rva<n)return std::size_t(rva);for(const auto&s:pe.sections){auto span=std::max(s.vsize,s.raw_size);if(rva>=s.rva&&std::uint64_t(rva)<std::uint64_t(s.rva)+span){auto delta=std::uint64_t(rva)-s.rva;if(delta>=s.raw_size)return{};auto o=std::uint64_t(s.raw_offset)+delta;if(o<n)return std::size_t(o);}}return{};}
std::string zstr(std::span<const std::uint8_t>d,std::size_t o,std::size_t end){if(o>=end||end>d.size())return{};auto q=o;while(q<end&&d[q])++q;return std::string(reinterpret_cast<const char*>(d.data()+o),q-o);}
std::uint32_t idxval(std::span<const std::uint8_t>d,std::size_t&p,std::uint32_t w){auto v=w==2?u16(d,p):u32(d,p);p+=w;return v;}
std::uint32_t tis(const std::array<std::uint32_t,64>&rows,int table){return rows[table]<65536?2:4;}
std::uint32_t coded(const std::array<std::uint32_t,64>&rows,std::initializer_list<int>tabs,int tagbits){std::uint32_t m=0;for(auto t:tabs)if(t>=0)m=std::max(m,rows[t]);return m<(1u<<(16-tagbits))?2:4;}
std::uint32_t token(int table,std::uint32_t rid){return rid?(std::uint32_t(table)<<24)|rid:0;}
std::uint32_t coded_token(std::uint32_t v,std::initializer_list<int>tabs,int tagbits){if(!v)return 0;auto tag=v&((1u<<tagbits)-1),rid=v>>tagbits;if(!rid)return 0;std::size_t i=0;for(auto t:tabs){if(i++==tag)return t>=0?token(t,rid):0;}return 0;}
std::string csvq(const std::string&s){std::string r="\"";for(char c:s){if(c=='\"')r+="\"\"";else r+=c;}return r+'\"';}
std::string join(const std::vector<std::string>&v,std::string_view sep){std::string o;for(const auto&s:v){if(!o.empty())o+=sep;o+=s;}return o;}
bool contains_icase(std::string a,std::string b){std::transform(a.begin(),a.end(),a.begin(),[](unsigned char c){return char(std::tolower(c));});std::transform(b.begin(),b.end(),b.begin(),[](unsigned char c){return char(std::tolower(c));});return a.find(b)!=std::string::npos;}
std::string hex32(std::uint32_t v){std::ostringstream o;o<<"0x"<<std::hex<<std::setw(8)<<std::setfill('0')<<v;return o.str();}

struct HeapView {
    std::span<const std::uint8_t>d;
    std::size_t strings=0,strings_end=0,blob=0,blob_end=0;
    bool has_blob=false;
    bool get_string(std::uint32_t idx,std::string&out)const{out.clear();if(!idx)return true;if(idx>=strings_end-strings)return false;auto p=strings+idx,q=p;while(q<strings_end&&d[q])++q;if(q==strings_end)return false;out.assign(reinterpret_cast<const char*>(d.data()+p),q-p);return true;}
    static bool compressed_len(std::span<const std::uint8_t>d,std::size_t&p,std::size_t end,std::uint32_t&v){if(p>=end)return false;auto a=d[p++];if(!(a&0x80)){v=a;return true;}if((a&0xc0)==0x80){if(p>=end)return false;v=(std::uint32_t(a&0x3f)<<8)|d[p++];return true;}if((a&0xe0)==0xc0){if(p+3>end)return false;v=(std::uint32_t(a&0x1f)<<24)|(std::uint32_t(d[p])<<16)|(std::uint32_t(d[p+1])<<8)|d[p+2];p+=3;return true;}return false;}
    bool get_blob(std::uint32_t idx,std::span<const std::uint8_t>&out)const{out={};if(!idx)return true;if(!has_blob||idx>=blob_end-blob)return false;auto p=blob+idx;std::uint32_t n=0;if(!compressed_len(d,p,blob_end,n)||n>blob_end-p)return false;out=d.subspan(p,n);return true;}
};

struct SigReader {
    std::span<const std::uint8_t>d;std::size_t p=0;std::string error;
    explicit SigReader(std::span<const std::uint8_t>x):d(x){}
    bool byte(std::uint8_t&v){if(p>=d.size()){error="signature truncated";return false;}v=d[p++];return true;}
    bool compressed(std::uint32_t&v){if(p>=d.size()){error="compressed integer truncated";return false;}auto a=d[p++];if(!(a&0x80)){v=a;return true;}if((a&0xc0)==0x80){if(p>=d.size()){error="compressed integer truncated";return false;}v=(std::uint32_t(a&0x3f)<<8)|d[p++];return true;}if((a&0xe0)==0xc0){if(p+3>d.size()){error="compressed integer truncated";return false;}v=(std::uint32_t(a&0x1f)<<24)|(std::uint32_t(d[p])<<16)|(std::uint32_t(d[p+1])<<8)|d[p+2];p+=3;return true;}error="invalid compressed integer prefix";return false;}
};
using TypeResolver=std::function<std::string(std::uint32_t)>;
std::string generic_name(const std::vector<std::string>*v,std::uint32_t i,bool method){if(v&&i<v->size()&&!(*v)[i].empty())return (method?"!!":"!")+(*v)[i];return std::string(method?"!!":"!")+std::to_string(i);}

bool decode_type(SigReader&r,const TypeResolver&resolve,const std::vector<std::string>*type_generics,const std::vector<std::string>*method_generics,std::string&out,int depth=0){
    if(depth>48){r.error="signature type nesting too deep";return false;}std::uint8_t et=0;if(!r.byte(et))return false;
    switch(et){
    case 0x01:out="System.Void";return true;case 0x02:out="System.Boolean";return true;case 0x03:out="System.Char";return true;case 0x04:out="System.SByte";return true;case 0x05:out="System.Byte";return true;case 0x06:out="System.Int16";return true;case 0x07:out="System.UInt16";return true;case 0x08:out="System.Int32";return true;case 0x09:out="System.UInt32";return true;case 0x0a:out="System.Int64";return true;case 0x0b:out="System.UInt64";return true;case 0x0c:out="System.Single";return true;case 0x0d:out="System.Double";return true;case 0x0e:out="System.String";return true;case 0x16:out="System.TypedReference";return true;case 0x18:out="System.IntPtr";return true;case 0x19:out="System.UIntPtr";return true;case 0x1c:out="System.Object";return true;
    case 0x0f:{std::string t;if(!decode_type(r,resolve,type_generics,method_generics,t,depth+1))return false;out=t+"*";return true;}
    case 0x10:{std::string t;if(!decode_type(r,resolve,type_generics,method_generics,t,depth+1))return false;out=t+"&";return true;}
    case 0x11:case 0x12:{std::uint32_t c=0;if(!r.compressed(c))return false;auto tok=coded_token(c,{2,1,27,-1},2);if(!tok){r.error="invalid TypeDefOrRefOrSpec encoded token";return false;}out=resolve(tok);if(out.empty())out=hex32(tok);return true;}
    case 0x13:{std::uint32_t n=0;if(!r.compressed(n))return false;out=generic_name(type_generics,n,false);return true;}
    case 0x14:{std::string t;if(!decode_type(r,resolve,type_generics,method_generics,t,depth+1))return false;std::uint32_t rank=0,n=0,x=0;if(!r.compressed(rank)||!r.compressed(n))return false;for(std::uint32_t i=0;i<n;i++)if(!r.compressed(x))return false;if(!r.compressed(n))return false;for(std::uint32_t i=0;i<n;i++)if(!r.compressed(x))return false;out=t+"[";if(rank>1)out+=std::string(rank-1,',');out+="]";return true;}
    case 0x15:{std::string base;if(!decode_type(r,resolve,type_generics,method_generics,base,depth+1))return false;std::uint32_t n=0;if(!r.compressed(n)||n>65535){if(r.error.empty())r.error="generic argument count unreasonable";return false;}std::vector<std::string>a;for(std::uint32_t i=0;i<n;i++){std::string t;if(!decode_type(r,resolve,type_generics,method_generics,t,depth+1))return false;a.push_back(std::move(t));}out=base+"<"+join(a,",")+">";return true;}
    case 0x1b:{std::uint8_t h=0;if(!r.byte(h))return false;bool gen=h&0x10;std::uint32_t g=0,n=0;if(gen&&!r.compressed(g))return false;if(!r.compressed(n))return false;std::string ret;if(!decode_type(r,resolve,type_generics,method_generics,ret,depth+1))return false;std::vector<std::string>p;for(std::uint32_t i=0;i<n;i++){if(r.p<r.d.size()&&r.d[r.p]==0x41)++r.p;std::string t;if(!decode_type(r,resolve,type_generics,method_generics,t,depth+1))return false;p.push_back(std::move(t));}out="methodptr("+join(p,",")+")->"+ret;return true;}
    case 0x1d:{std::string t;if(!decode_type(r,resolve,type_generics,method_generics,t,depth+1))return false;out=t+"[]";return true;}
    case 0x1e:{std::uint32_t n=0;if(!r.compressed(n))return false;out=generic_name(method_generics,n,true);return true;}
    case 0x1f:case 0x20:{std::uint32_t c=0;if(!r.compressed(c))return false;auto tok=coded_token(c,{2,1,27,-1},2);std::string t;if(!decode_type(r,resolve,type_generics,method_generics,t,depth+1))return false;auto mod=resolve(tok);out=(et==0x1f?"modreq(":"modopt(")+(mod.empty()?hex32(tok):mod)+") "+t;return true;}
    case 0x45:{std::string t;if(!decode_type(r,resolve,type_generics,method_generics,t,depth+1))return false;out="pinned "+t;return true;}
    default:{std::ostringstream o;o<<"unsupported signature element type 0x"<<std::hex<<unsigned(et);r.error=o.str();return false;}
    }
}
struct MethodSig {bool ok=false,has_this=false,explicit_this=false;std::uint32_t generic_arity=0;std::string callconv,ret,signature,error;std::vector<std::string>params;};
std::string callconv_name(std::uint8_t k){switch(k){case 0:return"default";case 1:return"cdecl";case 2:return"stdcall";case 3:return"thiscall";case 4:return"fastcall";case 5:return"vararg";case 8:return"property";default:return"callconv-"+std::to_string(k);}}
MethodSig decode_method(std::span<const std::uint8_t>b,const TypeResolver&resolve,const std::vector<std::string>*tg,const std::vector<std::string>*mg,bool property=false){MethodSig o;SigReader r{b};std::uint8_t h=0;if(!r.byte(h)){o.error=r.error;return o;}const auto k=static_cast<std::uint8_t>(h&0x0f);if((property&&k!=8)||(!property&&(k>5))){o.error="unexpected method/property signature header";return o;}o.has_this=h&0x20;o.explicit_this=h&0x40;o.callconv=callconv_name(k);if(h&0x10){if(!r.compressed(o.generic_arity)){o.error=r.error;return o;}}std::uint32_t n=0;if(!r.compressed(n)||n>1000000){o.error=r.error.empty()?"parameter count unreasonable":r.error;return o;}if(!decode_type(r,resolve,tg,mg,o.ret)){o.error=r.error;return o;}for(std::uint32_t i=0;i<n;i++){if(r.p<r.d.size()&&r.d[r.p]==0x41)++r.p;std::string t;if(!decode_type(r,resolve,tg,mg,t)){o.error=r.error;return o;}o.params.push_back(std::move(t));}if(r.p!=r.d.size()){o.error="signature has trailing bytes";return o;}o.signature="("+join(o.params,",")+") -> "+o.ret;o.ok=true;return o;}
bool decode_field(std::span<const std::uint8_t>b,const TypeResolver&resolve,const std::vector<std::string>*tg,std::string&type,std::string&err){SigReader r{b};std::uint8_t h=0;if(!r.byte(h)||((h&0x0f)!=6)){err=r.error.empty()?"unexpected field signature header":r.error;return false;}if(!decode_type(r,resolve,tg,nullptr,type)||r.p!=r.d.size()){err=r.error.empty()?"field signature has trailing bytes":r.error;return false;}return true;}
bool decode_method_spec(std::span<const std::uint8_t>b,const TypeResolver&resolve,std::vector<std::string>&args,std::string&err){SigReader r{b};std::uint8_t h=0;if(!r.byte(h)||((h&0x0f)!=0x0a)){err=r.error.empty()?"unexpected MethodSpec signature header":r.error;return false;}std::uint32_t n=0;if(!r.compressed(n)||n>65535){err=r.error.empty()?"MethodSpec argument count unreasonable":r.error;return false;}for(std::uint32_t i=0;i<n;i++){std::string t;if(!decode_type(r,resolve,nullptr,nullptr,t)){err=r.error;return false;}args.push_back(std::move(t));}if(r.p!=r.d.size()){err="MethodSpec signature has trailing bytes";return false;}return true;}

std::uint32_t row_size(int t,const std::array<std::uint32_t,64>&r,std::uint32_t sw,std::uint32_t gw,std::uint32_t bw){switch(t){
case 0:return 2+sw+gw*3;case 1:return coded(r,{0,26,35,1},2)+sw*2;case 2:return 4+sw*2+coded(r,{2,1,27},2)+tis(r,4)+tis(r,6);case 3:return tis(r,4);case 4:return 2+sw+bw;case 5:return tis(r,6);case 6:return 4+2+2+sw+bw+tis(r,8);case 7:return tis(r,8);case 8:return 4+sw;case 9:return tis(r,2)+coded(r,{2,1,27},2);case 10:return coded(r,{2,1,26,6,27},3)+sw+bw;case 11:return 2+coded(r,{4,8,23},2)+bw;case 12:return coded(r,{6,4,1,2,8,9,10,0,14,23,20,17,26,27,32,35,38,39,40,42,44,43},5)+coded(r,{6,10},3)+bw;case 13:return coded(r,{4,8},1)+bw;case 14:return 2+coded(r,{2,6,32},2)+bw;case 15:return 6+tis(r,2);case 16:return 4+tis(r,4);case 17:return bw;case 18:return tis(r,2)+tis(r,20);case 19:return tis(r,20);case 20:return 2+sw+coded(r,{2,1,27},2);case 21:return tis(r,2)+tis(r,23);case 22:return tis(r,23);case 23:return 2+sw+bw;case 24:return 2+tis(r,6)+coded(r,{20,23},1);case 25:return tis(r,2)+coded(r,{6,10},1)*2;case 26:return sw;case 27:return bw;case 28:return 2+coded(r,{4,6},1)+sw+tis(r,26);case 29:return 4+tis(r,4);case 30:return 8;case 31:return 4;case 32:return 16+bw+sw*2;case 33:return 4;case 34:return 12;case 35:return 12+bw*2+sw*2;case 36:return 4+tis(r,35);case 37:return 12+tis(r,35);case 38:return 4+sw+bw;case 39:return 8+sw*2+coded(r,{38,35,39},2);case 40:return 8+sw+coded(r,{38,35,39},2);case 41:return tis(r,2)*2;case 42:return 4+coded(r,{2,6},1)+sw;case 43:return coded(r,{6,10},1)+bw;case 44:return tis(r,42)+coded(r,{2,1,27},2);default:return 0;}}

bool weird_identifier(std::string_view s){if(s.empty()||s.size()>512)return !s.empty();std::size_t odd=0;for(unsigned char c:s)if(c<0x20||c>=0x7f)++odd;return odd*2>s.size();}
}

DotNetInfo detect_dotnet(std::span<const std::uint8_t>d,const PeInfo&pe,const std::filesystem::path&path){
    DotNetInfo out;if(!pe.valid||!pe.clr.present)return out;auto ps=path.string();out.unity_path_hint=contains_icase(ps,"/managed/")||contains_icase(ps,"\\managed\\")||contains_icase(path.filename().string(),"assembly-csharp");auto co=rvaoff(pe,pe.clr.rva,d.size());if(!co||*co+0x20>d.size()){out.error="CLR header RVA cannot be mapped";return out;}out.clr_flags=u32(d,*co+16);out.entry_point_token_or_rva=u32(d,*co+20);out.entry_point_native=(out.clr_flags&0x10u)!=0;if(!out.entry_point_native)out.managed_entry_method_token=out.entry_point_token_or_rva;auto md_rva=u32(d,*co+8),md_sz=u32(d,*co+12),res_rva=u32(d,*co+24),res_sz=u32(d,*co+28);auto mo=rvaoff(pe,md_rva,d.size());if(!mo||md_sz<20||md_sz>d.size()-*mo){out.error="CLR metadata root cannot be mapped";return out;}out.metadata_offset=*mo;out.metadata_size=md_sz;if(res_rva&&res_sz){if(auto ro=rvaoff(pe,res_rva,d.size());ro&&res_sz<=d.size()-*ro){out.resources_offset=*ro;out.resources_size=res_sz;}else out.anomalies.push_back("CLR managed resources directory cannot be mapped completely");}
    auto md_end=*mo+md_sz;std::size_t p=*mo;if(u32(d,p)!=0x424a5342){out.error="CLR metadata signature BSJB missing";return out;}p+=4;p+=4;p+=4;if(p+4>md_end){out.error="CLR metadata header truncated";return out;}auto vl=u32(d,p);p+=4;if(vl>4096||vl>md_end-p){out.error="CLR version string length invalid";return out;}out.runtime_version=zstr(d,p,p+vl);p+=vl;p=(*mo)+((p-*mo+3)&~std::size_t(3));if(p+4>md_end){out.error="CLR stream header truncated";return out;}p+=2;auto streams=u16(d,p);p+=2;if(streams>64){out.error="CLR stream count unreasonable";return out;}struct Stream{std::uint32_t off=0,size=0;std::string name;};std::map<std::string,Stream>sm;for(std::uint16_t i=0;i<streams;i++){if(p+8>md_end){out.error="CLR stream descriptor truncated";return out;}Stream s;s.off=u32(d,p);s.size=u32(d,p+4);p+=8;auto ns=p;while(p<md_end&&p-ns<32&&d[p])++p;if(p>=md_end||p-ns>=32){out.error="CLR stream name invalid";return out;}s.name.assign(reinterpret_cast<const char*>(d.data()+ns),p-ns);++p;p=(*mo)+((p-*mo+3)&~std::size_t(3));if(s.off>md_sz||s.size>md_sz-s.off){out.error="CLR stream bounds invalid";return out;}if(!sm.emplace(s.name,s).second)out.anomalies.push_back("duplicate CLR metadata stream name: "+s.name);}
    auto itT=sm.find("#~");if(itT==sm.end())itT=sm.find("#-");auto itS=sm.find("#Strings");if(itT==sm.end()||itS==sm.end()){out.error="CLR tables/#Strings stream missing";return out;}auto itB=sm.find("#Blob");auto ts=*mo+itT->second.off,te=ts+itT->second.size,ss=*mo+itS->second.off,se=ss+itS->second.size;if(te>d.size()||se>d.size()||ts+24>te){out.error="CLR metadata streams truncated";return out;}HeapView heap{d,ss,se,0,0,false};if(itB!=sm.end()){heap.blob=*mo+itB->second.off;heap.blob_end=heap.blob+itB->second.size;heap.has_blob=heap.blob_end<=d.size();out.blob_heap_size=itB->second.size;if(!heap.has_blob){out.error="CLR #Blob stream truncated";return out;}}
    std::size_t q=ts;q+=4;q+=2;auto heaps=d[q++];q++;auto valid=u64(d,q);q+=8;q+=8;for(int t=0;t<64;t++)if(valid&(1ull<<t)){if(q+4>te){out.error="CLR row-count table truncated";return out;}out.table_rows[t]=u32(d,q);q+=4;}
    auto sw=(heaps&1)?4u:2u,gw=(heaps&2)?4u:2u,bw=(heaps&4)?4u:2u;std::array<std::size_t,64>toff{};std::array<std::uint32_t,64>rs{};std::size_t cur=q;for(int t=0;t<64;t++){toff[t]=cur;if(!out.table_rows[t])continue;rs[t]=row_size(t,out.table_rows,sw,gw,bw);if(!rs[t]){std::ostringstream e;e<<"unsupported CLR metadata table 0x"<<std::hex<<t;out.error=e.str();return out;}auto bytes=std::uint64_t(out.table_rows[t])*rs[t];if(cur>te||bytes>te-cur){out.error="CLR table geometry invalid at table "+std::to_string(t);return out;}cur+=std::size_t(bytes);}
    auto getstr=[&](std::uint32_t idx,std::string&v,const char*what)->bool{if(heap.get_string(idx,v))return true;out.error=std::string("CLR #Strings index invalid for ")+what;return false;};
    auto readidx=[&](int table,std::uint32_t rid,std::size_t fieldoff,std::uint32_t width){auto x=toff[table]+std::size_t(rid-1)*rs[table]+fieldoff;return width==2?std::uint32_t(u16(d,x)):u32(d,x);};
    // AssemblyRef first, so TypeRef scope names can resolve immediately.
    out.assembly_refs.reserve(out.table_rows[35]);for(std::uint32_t rid=1;rid<=out.table_rows[35];rid++){auto x=toff[35]+std::size_t(rid-1)*rs[35];DotNetAssemblyRef a;a.rid=rid;a.token=token(35,rid);a.major=u16(d,x);a.minor=u16(d,x+2);a.build=u16(d,x+4);a.revision=u16(d,x+6);x+=12;x+=bw;auto ni=idxval(d,x,sw),ci=idxval(d,x,sw);x+=bw;if(!getstr(ni,a.name,"AssemblyRef.Name")||!getstr(ci,a.culture,"AssemblyRef.Culture"))return out;a.version=std::to_string(a.major)+"."+std::to_string(a.minor)+"."+std::to_string(a.build)+"."+std::to_string(a.revision);out.assembly_refs.push_back(std::move(a));}
    std::vector<std::string>module_refs(out.table_rows[26]+1);for(std::uint32_t rid=1;rid<=out.table_rows[26];rid++){auto ni=readidx(26,rid,0,sw);if(!getstr(ni,module_refs[rid],"ModuleRef.Name"))return out;}
    out.type_refs.reserve(out.table_rows[1]);for(std::uint32_t rid=1;rid<=out.table_rows[1];rid++){auto x=toff[1]+std::size_t(rid-1)*rs[1];auto cw=coded(out.table_rows,{0,26,35,1},2),scope=idxval(d,x,cw),ni=idxval(d,x,sw),nsi=idxval(d,x,sw);DotNetTypeRef t;t.rid=rid;t.token=token(1,rid);t.resolution_scope=coded_token(scope,{0,26,35,1},2);if(!getstr(ni,t.name,"TypeRef.Name")||!getstr(nsi,t.namespc,"TypeRef.Namespace"))return out;t.full_name=t.namespc.empty()?t.name:t.namespc+"."+t.name;out.type_refs.push_back(std::move(t));}
    std::function<std::string(std::uint32_t,int)> typeref_name=[&](std::uint32_t rid,int depth)->std::string{if(!rid||rid>out.type_refs.size()||depth>32)return{};auto&t=out.type_refs[rid-1];auto st=t.resolution_scope>>24,sr=t.resolution_scope&0xffffff;if(st==1&&sr&&sr!=rid){auto pfx=typeref_name(sr,depth+1);if(!pfx.empty())return pfx+"/"+t.name;}return t.full_name;};for(auto&t:out.type_refs){t.full_name=typeref_name(t.rid,0);auto st=t.resolution_scope>>24,sr=t.resolution_scope&0xffffff;if(st==35&&sr&&sr<=out.assembly_refs.size())t.scope_name=out.assembly_refs[sr-1].name;else if(st==26&&sr<module_refs.size())t.scope_name=module_refs[sr];else if(st==1)t.scope_name=typeref_name(sr,0);else if(st==0)t.scope_name="module";}
    out.types.reserve(out.table_rows[2]);for(std::uint32_t rid=1;rid<=out.table_rows[2];rid++){auto x=toff[2]+std::size_t(rid-1)*rs[2];DotNetType t;t.rid=rid;t.token=token(2,rid);t.flags=u32(d,x);x+=4;auto ni=idxval(d,x,sw),nsi=idxval(d,x,sw);auto ec=idxval(d,x,coded(out.table_rows,{2,1,27},2));t.extends_token=coded_token(ec,{2,1,27,-1},2);t.field_start=idxval(d,x,tis(out.table_rows,4));t.method_start=idxval(d,x,tis(out.table_rows,6));if(!getstr(ni,t.name,"TypeDef.Name")||!getstr(nsi,t.namespc,"TypeDef.Namespace"))return out;t.full_name=t.namespc.empty()?t.name:t.namespc+"."+t.name;out.types.push_back(std::move(t));}
    // NestedClass changes canonical managed full names before member association.
    for(std::uint32_t rid=1;rid<=out.table_rows[41];rid++){auto x=toff[41]+std::size_t(rid-1)*rs[41];auto w=tis(out.table_rows,2);auto n=idxval(d,x,w),e=idxval(d,x,w);if(n&&n<=out.types.size()&&e&&e<=out.types.size())out.types[n-1].enclosing_token=token(2,e);else out.anomalies.push_back("NestedClass row references an invalid TypeDef RID");}
    std::function<std::string(std::uint32_t,int)> typedef_name=[&](std::uint32_t rid,int depth)->std::string{if(!rid||rid>out.types.size()||depth>32)return{};auto&t=out.types[rid-1];if(t.enclosing_token){auto e=t.enclosing_token&0xffffff;auto pfx=typedef_name(e,depth+1);if(!pfx.empty())return pfx+"/"+t.name;}return t.namespc.empty()?t.name:t.namespc+"."+t.name;};for(auto&t:out.types){t.full_name=typedef_name(t.rid,0);if(t.enclosing_token)t.enclosing_type=typedef_name(t.enclosing_token&0xffffff,0);}
    out.params.reserve(out.table_rows[8]);for(std::uint32_t rid=1;rid<=out.table_rows[8];rid++){auto x=toff[8]+std::size_t(rid-1)*rs[8];DotNetParam a;a.rid=rid;a.token=token(8,rid);a.flags=u16(d,x);a.sequence=u16(d,x+2);x+=4;auto ni=idxval(d,x,sw);if(!getstr(ni,a.name,"Param.Name"))return out;out.params.push_back(std::move(a));}
    out.fields.reserve(out.table_rows[4]);for(std::uint32_t rid=1;rid<=out.table_rows[4];rid++){auto x=toff[4]+std::size_t(rid-1)*rs[4];DotNetField f;f.rid=rid;f.token=token(4,rid);f.flags=u16(d,x);x+=2;auto ni=idxval(d,x,sw);f.signature_blob=idxval(d,x,bw);if(!getstr(ni,f.name,"Field.Name"))return out;out.fields.push_back(std::move(f));}
    out.methods.reserve(out.table_rows[6]);for(std::uint32_t rid=1;rid<=out.table_rows[6];rid++){auto x=toff[6]+std::size_t(rid-1)*rs[6];DotNetMethod m;m.rid=rid;m.token=token(6,rid);m.metadata_row_offset=x;m.rva=u32(d,x);m.impl_flags=u16(d,x+4);m.flags=u16(d,x+6);x+=8;auto ni=idxval(d,x,sw);m.signature_blob=idxval(d,x,bw);m.param_start=idxval(d,x,tis(out.table_rows,8));if(!getstr(ni,m.name,"MethodDef.Name"))return out;out.methods.push_back(std::move(m));}
    // GenericParam rows are needed before signature decoding so !T / !!T can use recovered names.
    out.generic_params.reserve(out.table_rows[42]);for(std::uint32_t rid=1;rid<=out.table_rows[42];rid++){auto x=toff[42]+std::size_t(rid-1)*rs[42];DotNetGenericParam g;g.rid=rid;g.token=token(42,rid);g.number=u16(d,x);g.flags=u16(d,x+2);x+=4;auto oc=idxval(d,x,coded(out.table_rows,{2,6},1));g.owner_token=coded_token(oc,{2,6},1);auto ni=idxval(d,x,sw);if(!getstr(ni,g.name,"GenericParam.Name"))return out;out.generic_params.push_back(std::move(g));}
    for(auto&g:out.generic_params){auto tab=g.owner_token>>24,rid=g.owner_token&0xffffff;if(tab==2&&rid&&rid<=out.types.size()){auto&t=out.types[rid-1];if(t.generic_params.size()<=g.number)t.generic_params.resize(g.number+1);t.generic_params[g.number]=g.name;g.owner=t.full_name;}else if(tab==6&&rid&&rid<=out.methods.size()){auto&m=out.methods[rid-1];if(m.generic_params.size()<=g.number)m.generic_params.resize(g.number+1);m.generic_params[g.number]=g.name;g.owner=m.name;}else out.anomalies.push_back("GenericParam owner token is invalid");}
    auto ptr_rid=[&](int ptr_table,int target_table,std::uint32_t list_rid)->std::uint32_t{
        if(!list_rid)return 0;
        if(!out.table_rows[ptr_table])return list_rid;
        if(list_rid>out.table_rows[ptr_table])return 0;
        return readidx(ptr_table,list_rid,0,tis(out.table_rows,target_table));
    };
    auto list_rows=[&](int ptr_table,int target_table){return out.table_rows[ptr_table]?out.table_rows[ptr_table]:out.table_rows[target_table];};
    // Associate field/method/param list ranges using original RID order, including empty names.
    for(std::size_t ti=0;ti<out.types.size();ti++){auto fb=out.types[ti].field_start,fe=list_rows(3,4)+1,mb=out.types[ti].method_start,me=list_rows(5,6)+1;if(ti+1<out.types.size()){if(out.types[ti+1].field_start)fe=out.types[ti+1].field_start;if(out.types[ti+1].method_start)me=out.types[ti+1].method_start;}if(fb&&fb<=fe)for(std::uint32_t r=fb;r<fe&&r<=list_rows(3,4);r++){auto fr=ptr_rid(3,4,r);if(fr&&fr<=out.fields.size()){auto&f=out.fields[fr-1];f.declaring_type=out.types[ti].full_name;f.full_name=f.declaring_type.empty()?f.name:f.declaring_type+"::"+f.name;}else out.anomalies.push_back("FieldList/FieldPtr references invalid Field RID");}if(mb&&mb<=me)for(std::uint32_t r=mb;r<me&&r<=list_rows(5,6);r++){auto mr=ptr_rid(5,6,r);if(mr&&mr<=out.methods.size())out.methods[mr-1].type_name=out.types[ti].full_name;else out.anomalies.push_back("MethodList/MethodPtr references invalid MethodDef RID");}}
    for(auto&m:out.methods)m.full_name=m.type_name.empty()?m.name:m.type_name+"::"+m.name;
    for(std::size_t mi=0;mi<out.methods.size();mi++){auto pb=out.methods[mi].param_start,param_end=list_rows(7,8)+1;if(mi+1<out.methods.size()&&out.methods[mi+1].param_start)param_end=out.methods[mi+1].param_start;std::uint16_t maxseq=0;if(pb&&pb<=param_end)for(std::uint32_t r=pb;r<param_end&&r<=list_rows(7,8);r++){auto pr=ptr_rid(7,8,r);if(pr&&pr<=out.params.size())maxseq=std::max(maxseq,out.params[pr-1].sequence);}out.methods[mi].param_names.resize(maxseq);if(pb&&pb<=param_end)for(std::uint32_t r=pb;r<param_end&&r<=list_rows(7,8);r++){auto pr=ptr_rid(7,8,r);if(!pr||pr>out.params.size())continue;const auto&a=out.params[pr-1];if(a.sequence&&a.sequence<=out.methods[mi].param_names.size())out.methods[mi].param_names[a.sequence-1]=a.name;}}
    // TypeSpec blob indices for lazy signature-backed type resolution.
    std::vector<std::uint32_t>typespec_blob(out.table_rows[27]+1);for(std::uint32_t rid=1;rid<=out.table_rows[27];rid++)typespec_blob[rid]=readidx(27,rid,0,bw);
    std::function<std::string(std::uint32_t,std::set<std::uint32_t>&,int)> resolve_rec;resolve_rec=[&](std::uint32_t tok,std::set<std::uint32_t>&seen,int depth)->std::string{if(!tok||depth>48)return{};auto tab=tok>>24,rid=tok&0xffffff;if(tab==1)return rid&&rid<=out.type_refs.size()?out.type_refs[rid-1].full_name:std::string();if(tab==2)return rid&&rid<=out.types.size()?out.types[rid-1].full_name:std::string();if(tab==27&&rid<typespec_blob.size()){if(!seen.insert(tok).second)return"<recursive-typespec>";std::span<const std::uint8_t>b;if(!heap.get_blob(typespec_blob[rid],b)){seen.erase(tok);return{};}SigReader sr{b};TypeResolver rr=[&](std::uint32_t x){return resolve_rec(x,seen,depth+1);};std::string t;if(!decode_type(sr,rr,nullptr,nullptr,t,depth+1)||sr.p!=b.size())t="<typespec "+hex32(tok)+">";seen.erase(tok);return t;}return{};};TypeResolver resolve=[&](std::uint32_t tok){std::set<std::uint32_t>s;return resolve_rec(tok,s,0);};
    for(auto&t:out.types)if(t.extends_token)t.base_type=resolve(t.extends_token);
    for(std::uint32_t rid=1;rid<=out.table_rows[9];rid++){auto x=toff[9]+std::size_t(rid-1)*rs[9];auto c=idxval(d,x,tis(out.table_rows,2)),ic=idxval(d,x,coded(out.table_rows,{2,1,27},2));auto itok=coded_token(ic,{2,1,27,-1},2);if(c&&c<=out.types.size())out.types[c-1].interfaces.push_back(resolve(itok));else out.anomalies.push_back("InterfaceImpl Class RID invalid");}
    for(std::uint32_t rid=1;rid<=out.table_rows[16];rid++){auto x=toff[16]+std::size_t(rid-1)*rs[16];auto off=u32(d,x);x+=4;auto fr=idxval(d,x,tis(out.table_rows,4));if(fr&&fr<=out.fields.size()){out.fields[fr-1].has_layout=true;out.fields[fr-1].offset=off;}else out.anomalies.push_back("FieldLayout Field RID invalid");}
    for(std::uint32_t rid=1;rid<=out.table_rows[29];rid++){auto x=toff[29]+std::size_t(rid-1)*rs[29];auto rv=u32(d,x);x+=4;auto fr=idxval(d,x,tis(out.table_rows,4));if(fr&&fr<=out.fields.size()){out.fields[fr-1].has_rva=true;out.fields[fr-1].rva=rv;}else out.anomalies.push_back("FieldRVA Field RID invalid");}
    // P/Invoke ImplMap.
    for(std::uint32_t rid=1;rid<=out.table_rows[28];rid++){auto x=toff[28]+std::size_t(rid-1)*rs[28];x+=2;auto mc=idxval(d,x,coded(out.table_rows,{4,6},1)),mtok=coded_token(mc,{4,6},1),ni=idxval(d,x,sw),mr=idxval(d,x,tis(out.table_rows,26));std::string entry;if(!getstr(ni,entry,"ImplMap.ImportName"))return out;if((mtok>>24)==6){auto r=mtok&0xffffff;if(r&&r<=out.methods.size()){auto&m=out.methods[r-1];m.pinvoke=true;m.import_name=entry;if(mr<module_refs.size())m.import_module=module_refs[mr];}}}
    auto sigfail=[&](std::string what,std::uint32_t tok,std::uint32_t bi,const std::string&e){out.signature_parse_complete=false;if(out.anomalies.size()<128)out.anomalies.push_back(std::move(what)+" "+hex32(tok)+" blob "+std::to_string(bi)+": "+e);};
    if(!heap.has_blob&&(out.table_rows[4]||out.table_rows[6]||out.table_rows[10]||out.table_rows[23]||out.table_rows[27]||out.table_rows[43])){out.signature_parse_complete=false;out.anomalies.push_back("#Blob heap missing; managed signatures cannot be decoded");}
    for(auto&f:out.fields){std::span<const std::uint8_t>b;if(!heap.get_blob(f.signature_blob,b)){sigfail("Field signature index invalid",f.token,f.signature_blob,"blob bounds");continue;}const std::vector<std::string>*tg=nullptr;if(!f.declaring_type.empty())for(const auto&t:out.types)if(t.full_name==f.declaring_type){tg=&t.generic_params;break;}std::string err;if(!decode_field(b,resolve,tg,f.type_name,err))sigfail("Field signature decode failed",f.token,f.signature_blob,err);else f.signature=f.type_name;}
    for(auto&m:out.methods){std::span<const std::uint8_t>b;if(!heap.get_blob(m.signature_blob,b)){sigfail("MethodDef signature index invalid",m.token,m.signature_blob,"blob bounds");continue;}const std::vector<std::string>*tg=nullptr;if(!m.type_name.empty())for(const auto&t:out.types)if(t.full_name==m.type_name){tg=&t.generic_params;break;}auto ms=decode_method(b,resolve,tg,&m.generic_params,false);if(!ms.ok){sigfail("MethodDef signature decode failed",m.token,m.signature_blob,ms.error);continue;}m.has_this=ms.has_this;m.explicit_this=ms.explicit_this;m.generic_arity=ms.generic_arity;m.calling_convention=ms.callconv;m.return_type=ms.ret;m.param_types=std::move(ms.params);m.signature=ms.signature;if(m.param_names.size()<m.param_types.size())m.param_names.resize(m.param_types.size());m.full_name=(m.type_name.empty()?m.name:m.type_name+"::"+m.name)+"("+join(m.param_types,",")+") -> "+m.return_type;}
    // PropertyMap/Property rows.
    out.properties.reserve(out.table_rows[23]);for(std::uint32_t rid=1;rid<=out.table_rows[23];rid++){auto x=toff[23]+std::size_t(rid-1)*rs[23];DotNetProperty a;a.rid=rid;a.token=token(23,rid);a.flags=u16(d,x);x+=2;auto ni=idxval(d,x,sw);a.signature_blob=idxval(d,x,bw);if(!getstr(ni,a.name,"Property.Name"))return out;out.properties.push_back(std::move(a));}
    for(std::uint32_t r=1;r<=out.table_rows[21];r++){auto x=toff[21]+std::size_t(r-1)*rs[21];auto tr=idxval(d,x,tis(out.table_rows,2)),pb=idxval(d,x,tis(out.table_rows,23)),property_end=list_rows(22,23)+1;if(r<out.table_rows[21]){auto nx=toff[21]+std::size_t(r)*rs[21]+tis(out.table_rows,2);property_end=nx<te?(tis(out.table_rows,23)==2?u16(d,nx):u32(d,nx)):property_end;}if(tr&&tr<=out.types.size())for(std::uint32_t pr=pb;pr<property_end&&pr<=list_rows(22,23);pr++){auto rr=ptr_rid(22,23,pr);if(rr&&rr<=out.properties.size())out.properties[rr-1].declaring_type=out.types[tr-1].full_name;}}
    for(auto&a:out.properties){std::span<const std::uint8_t>b;if(!heap.get_blob(a.signature_blob,b)){sigfail("Property signature index invalid",a.token,a.signature_blob,"blob bounds");continue;}const std::vector<std::string>*tg=nullptr;for(const auto&t:out.types)if(t.full_name==a.declaring_type){tg=&t.generic_params;break;}auto ms=decode_method(b,resolve,tg,nullptr,true);if(!ms.ok)sigfail("Property signature decode failed",a.token,a.signature_blob,ms.error);else{a.type_name=ms.ret;a.signature=ms.signature;}}
    // EventMap/Event rows.
    out.events.reserve(out.table_rows[20]);for(std::uint32_t rid=1;rid<=out.table_rows[20];rid++){auto x=toff[20]+std::size_t(rid-1)*rs[20];DotNetEvent a;a.rid=rid;a.token=token(20,rid);a.flags=u16(d,x);x+=2;auto ni=idxval(d,x,sw),ec=idxval(d,x,coded(out.table_rows,{2,1,27},2));a.event_type_token=coded_token(ec,{2,1,27,-1},2);if(!getstr(ni,a.name,"Event.Name"))return out;a.event_type=resolve(a.event_type_token);out.events.push_back(std::move(a));}
    for(std::uint32_t r=1;r<=out.table_rows[18];r++){auto x=toff[18]+std::size_t(r-1)*rs[18];auto tr=idxval(d,x,tis(out.table_rows,2)),eb=idxval(d,x,tis(out.table_rows,20)),ee=list_rows(19,20)+1;if(r<out.table_rows[18]){auto nx=toff[18]+std::size_t(r)*rs[18]+tis(out.table_rows,2);ee=tis(out.table_rows,20)==2?u16(d,nx):u32(d,nx);}if(tr&&tr<=out.types.size())for(std::uint32_t er=eb;er<ee&&er<=list_rows(19,20);er++){auto rr=ptr_rid(19,20,er);if(rr&&rr<=out.events.size())out.events[rr-1].declaring_type=out.types[tr-1].full_name;}}
    // MemberRef needs parent names and either field or method signatures.
    out.member_refs.reserve(out.table_rows[10]);for(std::uint32_t rid=1;rid<=out.table_rows[10];rid++){auto x=toff[10]+std::size_t(rid-1)*rs[10];auto pc=idxval(d,x,coded(out.table_rows,{2,1,26,6,27},3));DotNetMemberRef a;a.rid=rid;a.token=token(10,rid);a.parent_token=coded_token(pc,{2,1,26,6,27,-1,-1,-1},3);auto ni=idxval(d,x,sw);a.signature_blob=idxval(d,x,bw);if(!getstr(ni,a.name,"MemberRef.Name"))return out;auto tab=a.parent_token>>24,pr=a.parent_token&0xffffff;if(tab==1||tab==2||tab==27)a.parent=resolve(a.parent_token);else if(tab==26&&pr<module_refs.size())a.parent=module_refs[pr];else if(tab==6&&pr&&pr<=out.methods.size())a.parent=out.methods[pr-1].full_name;std::span<const std::uint8_t>b;if(!heap.get_blob(a.signature_blob,b)){sigfail("MemberRef signature index invalid",a.token,a.signature_blob,"blob bounds");out.member_refs.push_back(std::move(a));continue;}if(!b.empty()&&((b[0]&0x0f)==6)){std::string err,t;if(decode_field(b,resolve,nullptr,t,err)){a.kind="field";a.signature=t;}else sigfail("MemberRef field signature decode failed",a.token,a.signature_blob,err);}else{auto ms=decode_method(b,resolve,nullptr,nullptr,false);if(ms.ok){a.kind="method";a.signature=ms.signature;}else sigfail("MemberRef method signature decode failed",a.token,a.signature_blob,ms.error);}out.member_refs.push_back(std::move(a));}
    // MethodSemantics ties properties/events back to their managed accessor methods.
    for(std::uint32_t rid=1;rid<=out.table_rows[24];rid++){auto x=toff[24]+std::size_t(rid-1)*rs[24];auto sem=u16(d,x);x+=2;auto mr=idxval(d,x,tis(out.table_rows,6)),ac=idxval(d,x,coded(out.table_rows,{20,23},1)),atok=coded_token(ac,{20,23},1);std::string mn;if(mr&&mr<=out.methods.size())mn=out.methods[mr-1].full_name;auto tab=atok>>24,ar=atok&0xffffff;if(tab==23&&ar&&ar<=out.properties.size()){auto&a=out.properties[ar-1];if(sem&0x1)a.setter=mn;if(sem&0x2)a.getter=mn;}else if(tab==20&&ar&&ar<=out.events.size()){auto&a=out.events[ar-1];if(sem&0x8)a.adder=mn;if(sem&0x10)a.remover=mn;if(sem&0x20)a.raiser=mn;}}
    // Generic parameter constraints can resolve through TypeSpec as well.
    for(std::uint32_t rid=1;rid<=out.table_rows[44];rid++){auto x=toff[44]+std::size_t(rid-1)*rs[44];auto gr=idxval(d,x,tis(out.table_rows,42)),cc=idxval(d,x,coded(out.table_rows,{2,1,27},2)),ct=coded_token(cc,{2,1,27,-1},2);if(gr&&gr<=out.generic_params.size())out.generic_params[gr-1].constraints.push_back(resolve(ct));else out.anomalies.push_back("GenericParamConstraint owner RID invalid");}
    // Re-label generic-param owners now that MethodDef full signatures are available.
    for(auto&g:out.generic_params){auto tab=g.owner_token>>24,rid=g.owner_token&0xffffff;if(tab==6&&rid&&rid<=out.methods.size())g.owner=out.methods[rid-1].full_name;}
    out.method_specs.reserve(out.table_rows[43]);for(std::uint32_t rid=1;rid<=out.table_rows[43];rid++){auto x=toff[43]+std::size_t(rid-1)*rs[43];auto mc=idxval(d,x,coded(out.table_rows,{6,10},1));DotNetMethodSpec a;a.rid=rid;a.token=token(43,rid);a.method_token=coded_token(mc,{6,10},1);a.signature_blob=idxval(d,x,bw);auto tab=a.method_token>>24,mr=a.method_token&0xffffff;if(tab==6&&mr&&mr<=out.methods.size())a.method=out.methods[mr-1].full_name;else if(tab==10&&mr&&mr<=out.member_refs.size())a.method=out.member_refs[mr-1].parent+"::"+out.member_refs[mr-1].name;std::span<const std::uint8_t>b;std::string err;if(!heap.get_blob(a.signature_blob,b)||!decode_method_spec(b,resolve,a.type_args,err))sigfail("MethodSpec signature decode failed",a.token,a.signature_blob,err.empty()?"blob bounds":err);else a.signature=a.method+"<"+join(a.type_args,",")+">";out.method_specs.push_back(std::move(a));}
    // ManifestResource: implementation=0 means embedded in the CLI resources directory.
    out.resources.reserve(out.table_rows[40]);for(std::uint32_t rid=1;rid<=out.table_rows[40];rid++){auto x=toff[40]+std::size_t(rid-1)*rs[40];DotNetResource a;a.rid=rid;a.token=token(40,rid);a.offset=u32(d,x);a.flags=u32(d,x+4);x+=8;auto ni=idxval(d,x,sw),ic=idxval(d,x,coded(out.table_rows,{38,35,39},2));a.implementation_token=coded_token(ic,{38,35,39,-1},2);if(!getstr(ni,a.name,"ManifestResource.Name"))return out;if(!a.implementation_token&&out.resources_size&&a.offset+4<=out.resources_size){auto ro=std::size_t(out.resources_offset+a.offset);auto n=u32(d,ro);if(n<=out.resources_size-a.offset-4&&ro+4+n<=d.size()){a.embedded=true;a.size_known=true;a.data_offset=ro+4;a.size=n;}else out.anomalies.push_back("embedded ManifestResource length exceeds CLR resources directory: "+a.name);}else if((a.implementation_token>>24)==35){auto rr=a.implementation_token&0xffffff;if(rr&&rr<=out.assembly_refs.size())a.implementation=out.assembly_refs[rr-1].name;}out.resources.push_back(std::move(a));}

    // Bounded MethodDef body geometry for implicit-init localization only. This does not decode or execute IL.
    for(auto&m:out.methods){
        if(!m.rva)continue;
        auto bo=rvaoff(pe,m.rva,d.size());if(!bo)continue;
        const auto first=d[*bo];
        if((first&0x3u)==0x2u){
            const auto n=std::uint64_t(first>>2);if(*bo+1<=d.size()&&n<=d.size()-(*bo+1)){m.body_file_backed=true;m.body_file_offset=*bo;m.body_header_size=1;m.code_file_offset=*bo+1;m.code_size=n;}
        }else if((first&0x3u)==0x3u){
            if(*bo+12>d.size())continue;
            const auto fs=u16(d,*bo);const auto dwords=std::uint32_t(fs>>12);if(dwords<3||dwords>15)continue;const auto hs=std::uint64_t(dwords)*4;const auto n=std::uint64_t(u32(d,*bo+4));if(hs<=d.size()-*bo&&n<=d.size()-(*bo+hs)){m.body_file_backed=true;m.body_file_offset=*bo;m.body_header_size=hs;m.code_file_offset=*bo+hs;m.code_size=n;}
        }
    }
    bool managed_entry_method_supported=false;
    if(out.managed_entry_method_token){
        const auto tab=out.managed_entry_method_token>>24,er=out.managed_entry_method_token&0xffffffu;
        if(tab==6&&er&&er<=out.methods.size()){
            const auto&m=out.methods[er-1];
            const bool params_ok=m.param_types.empty()||(m.param_types.size()==1&&m.param_types[0]=="System.String[]");
            const bool ret_ok=m.return_type=="System.Void"||m.return_type=="System.Int32";
            managed_entry_method_supported=(m.flags&0x10u)&&!m.has_this&&!m.explicit_this&&m.generic_arity==0&&params_ok&&ret_ok;
            if(managed_entry_method_supported){out.managed_entry_method=m.full_name;out.managed_entry_type=m.type_name;}
        }
    }
    {
        auto&im=out.implicit_exec;constexpr std::size_t max_facts=65536;bool partial=false;std::string partial_error;
        auto add=[&](ImplicitExecutionFact f){if(im.facts.size()>=max_facts){im.analysis_limited=true;partial=true;if(partial_error.empty())partial_error=".NET implicit execution fact budget exceeded";return;}f.index=static_cast<std::uint32_t>(im.facts.size());if(f.priority=="HIGH")++im.high_priority_count;else if(f.priority=="REVIEW")++im.review_count;else ++im.informational_count;if(!f.anomaly_class.empty()&&f.anomaly_class!="NONE")++im.anomaly_count;if(f.evidence_state=="UNRESOLVED_RUNTIME_SEMANTICS")++im.unresolved_runtime_semantics;im.facts.push_back(std::move(f));};
        auto type_flags=[&](std::string_view n)->std::uint32_t{for(const auto&t:out.types)if(t.full_name==n)return t.flags;return 0;};
        for(const auto&m:out.methods){
            if(m.name!=".cctor"||m.signature!="() -> System.Void"||!(m.flags&0x10u))continue;
            ImplicitExecutionFact f;f.format=".NET";f.ecosystem="ECMA-335/CLR";f.relation="implicit_callback";f.source_kind="MethodDef";f.source_index=m.rid;f.source_file_backed=true;f.source_file_offset=m.metadata_row_offset;f.source_size=rs[6];f.target_kind="managed_method";f.target_token=m.token;f.target_function_index=m.rid;f.target_name=m.full_name;f.target_file_backed=m.body_file_backed;if(m.body_file_backed)f.target_file_offset=m.code_file_offset;f.evidence_state=m.body_file_backed?"EXACT":"METHOD_BODY_UNAVAILABLE";f.mutability="IMMUTABLE_MANAGED_IMAGE";f.priority="INFORMATIONAL";const auto tf=type_flags(m.type_name);const bool beforefieldinit=(tf&0x00100000u)!=0;std::ostringstream detail;detail<<"method_rva=0x"<<std::hex<<m.rva<<std::dec<<";beforefieldinit="<<(beforefieldinit?"true":"false")<<";body_file_backed="<<(m.body_file_backed?"true":"false");if(m.body_file_backed)detail<<";body_header_size="<<m.body_header_size<<";code_file_offset=0x"<<std::hex<<m.code_file_offset<<std::dec<<";code_size="<<m.code_size;f.detail=detail.str();
            if(m.type_name=="<Module>"){
                f.phase="module_load";f.trigger="DOTNET_MODULE_CCTOR";f.execution_condition="CLR module initialization may invoke <Module>::.cctor before managed module code that depends on it; IL is not executed by analysis";f.priority_reason="module type initializer is an implicit module-level execution surface; source-language ModuleInitializer methods, when present, normally dispatch through this body but individual IL calls are not reconstructed";
            }else if(!out.managed_entry_type.empty()&&m.type_name==out.managed_entry_type){
                f.phase="runtime_initialization";f.trigger="DOTNET_ENTRY_TYPE_CCTOR";f.execution_condition=beforefieldinit?"entry method declaring type has beforefieldinit; CLR may run its .cctor any time before a static field defined by the type is first accessed, so exact pre-entry ordering is not claimed":"managed entry method belongs to this type; normal CLR type-initialization rules require its .cctor before first triggering static use, but IL reachability is not simulated";f.priority_reason="entry method declaring type has an implicit type initializer; inspect it alongside the entry method without assuming stronger ordering than CLR rules";
            }else{
                f.phase="runtime_initialization";f.trigger="DOTNET_TYPE_CCTOR";f.execution_condition=beforefieldinit?"beforefieldinit type initializer may run at CLR-chosen time before first static-field access; it is not labeled pre-main":"CLR invokes this type initializer before the first triggering static member use; application startup reachability is not inferred";f.priority_reason="ordinary first-use type initialization surface; not every type .cctor runs before the managed entry point";
            }
            if(!m.body_file_backed){partial=true;if(partial_error.empty())partial_error="one or more .cctor MethodDef bodies could not be bounded as tiny/fat IL bodies";}
            add(std::move(f));
        }
        if(out.managed_entry_method_token&&!out.managed_entry_method.empty()&&out.managed_entry_type.empty()){partial=true;if(partial_error.empty())partial_error="managed entry MethodDef has no declaring TypeDef association";}
        if(out.managed_entry_method_token&&out.managed_entry_method.empty()){
            const auto tab=out.managed_entry_method_token>>24,er=out.managed_entry_method_token&0xffffffu;
            if(tab!=0&&tab!=6){partial=true;if(partial_error.empty())partial_error="CLR managed entry-point token is not a MethodDef and is outside current single-module entry-type correlation";}
            else if(tab==6&&(!er||er>out.methods.size())){partial=true;if(partial_error.empty())partial_error="CLR managed entry-point MethodDef token is out of range";}
            else if(tab==6&&!managed_entry_method_supported){partial=true;if(partial_error.empty())partial_error="CLR managed entry-point MethodDef does not satisfy supported static Main-compatible signature semantics";}
        }
        if(im.facts.empty())im.state=partial?"PARTIAL":"NOT_PRESENT";else im.state=partial?"PARTIAL":"RESOLVED";if(partial)im.error=partial_error;
    }
    // Marker-only obfuscator hints are deliberately not promoted to CONFIRMED tooling claims.
    auto sheap=std::string_view(reinterpret_cast<const char*>(d.data()+ss),se-ss);for(const auto&marker:std::array<std::pair<std::string_view,std::string_view>,6>{{{"ConfusedByAttribute","Confuser/ConfuserEx marker"},{"BabelObfuscator","Babel marker"},{"Dotfuscator","Dotfuscator marker"},{"Eazfuscator","Eazfuscator marker"},{"AgileDotNet","Agile.NET marker"},{"SecureTeam","Agile.NET/SecureTeam marker"}}})if(sheap.find(marker.first)!=std::string_view::npos)out.obfuscation_hints.emplace_back(marker.second);
    std::size_t ids=0,weird=0;for(const auto&t:out.types)if(t.name!="<Module>"){++ids;if(weird_identifier(t.name))++weird;}for(const auto&m:out.methods){++ids;if(weird_identifier(m.name))++weird;}if(ids>=20&&weird>=5&&weird*5>=ids)out.obfuscation_hints.push_back("unusual non-ASCII/control-heavy managed identifier distribution");
    out.unity_engine_reference=std::any_of(out.assembly_refs.begin(),out.assembly_refs.end(),[](const auto&a){return a.name=="UnityEngine"||a.name.rfind("UnityEngine.",0)==0;});
    out.unity_managed=out.unity_path_hint&&out.unity_engine_reference;
    out.valid=true;return out;
}

Finding dotnet_finding(const DotNetInfo&i){Finding f;f.kind="runtime";f.family=i.unity_mono?"Unity Mono/.NET":(i.unity_managed?"Unity managed/.NET":".NET metadata");if(!i.valid){f.state="FAILED";if(!i.error.empty())f.negative_evidence.push_back(i.error);return f;}f.state="CONFIRMED";f.evidence={"CLR header and BSJB metadata root validated","complete ECMA-335 table geometry validated through supported standard tables","TypeDef/TypeRef/MethodDef/Field/Param relationships recovered"};if(i.signature_parse_complete)f.evidence.push_back("#Blob method/field/property/generic signatures decoded");else f.negative_evidence.push_back("one or more managed signatures could not be decoded; see anomaly list");f.fields["runtime_version"]=i.runtime_version;f.fields["types"]=std::to_string(i.types.size());f.fields["type_refs"]=std::to_string(i.type_refs.size());f.fields["methods"]=std::to_string(i.methods.size());f.fields["fields"]=std::to_string(i.fields.size());f.fields["params"]=std::to_string(i.params.size());f.fields["member_refs"]=std::to_string(i.member_refs.size());f.fields["properties"]=std::to_string(i.properties.size());f.fields["events"]=std::to_string(i.events.size());f.fields["generic_params"]=std::to_string(i.generic_params.size());f.fields["method_specs"]=std::to_string(i.method_specs.size());f.fields["assembly_refs"]=std::to_string(i.assembly_refs.size());f.fields["resources"]=std::to_string(i.resources.size());if(i.unity_managed){f.fields["unity_payload"]="validated";f.evidence.push_back("validated CLR/ECMA-335 payload is in a Unity managed route and references UnityEngine managed assemblies");f.negative_evidence.push_back("this managed file alone does not prove the Mono backend; backend confirmation requires independent runtime/directory evidence");}if(i.unity_mono){f.fields["unity_backend"]="Mono";f.evidence.push_back("directory correlation independently validated a Unity executable, this Unity-managed payload, and an exact Mono runtime export surface");}for(const auto&h:i.obfuscation_hints)f.negative_evidence.push_back("obfuscation hint only: "+h);for(std::size_t n=0;n<std::min<std::size_t>(i.anomalies.size(),16);n++)f.negative_evidence.push_back(i.anomalies[n]);f.suggested_actions={"extract:dotnet-symbols-and-types","inspect user TypeDef methods with recovered signatures","open in dnSpy/ILSpy/dotPeek for IL-level analysis"};return f;}

DotNetExtractResult extract_dotnet_symbols(const DotNetInfo&i,const std::filesystem::path&out){DotNetExtractResult r;if(!i.valid){r.error=".NET metadata not valid";return r;}std::ofstream f(out,std::ios::binary|std::ios::trunc);if(!f){r.error="cannot create .NET symbols CSV";return r;}f<<"token,rva,type,method,signature,return_type,parameter_types,parameter_names,full_name,pinvoke_module,pinvoke_name\n";for(const auto&m:i.methods)f<<hex32(m.token)<<",0x"<<std::hex<<m.rva<<std::dec<<','<<csvq(m.type_name)<<','<<csvq(m.name)<<','<<csvq(m.signature)<<','<<csvq(m.return_type)<<','<<csvq(join(m.param_types,"|"))<<','<<csvq(join(m.param_names,"|"))<<','<<csvq(m.full_name)<<','<<csvq(m.import_module)<<','<<csvq(m.import_name)<<"\n";if(!f){r.error="write .NET symbols CSV failed";return r;}r.symbols_csv=out;r.symbol_count=i.methods.size();auto tp=out;tp.replace_filename(out.stem().string()+"-types.csv");std::ofstream t(tp,std::ios::binary|std::ios::trunc);if(!t){r.error="cannot create .NET types CSV";return r;}t<<"token,namespace,name,full_name,base_type,enclosing_type,interfaces,generic_params,flags\n";for(const auto&x:i.types)t<<hex32(x.token)<<','<<csvq(x.namespc)<<','<<csvq(x.name)<<','<<csvq(x.full_name)<<','<<csvq(x.base_type)<<','<<csvq(x.enclosing_type)<<','<<csvq(join(x.interfaces,"|"))<<','<<csvq(join(x.generic_params,"|"))<<','<<hex32(x.flags)<<"\n";if(!t){r.error="write .NET types CSV failed";return r;}r.types_csv=tp;r.type_count=i.types.size();auto mp=out;mp.replace_filename(out.stem().string()+"-members.csv");std::ofstream m(mp,std::ios::binary|std::ios::trunc);if(!m){r.error="cannot create .NET members CSV";return r;}m<<"kind,token,owner,name,signature,extra\n";for(const auto&x:i.fields){std::string e;if(x.has_layout)e="offset="+std::to_string(x.offset);if(x.has_rva){if(!e.empty())e+=';';e+="rva="+hex32(x.rva);}m<<"field,"<<hex32(x.token)<<','<<csvq(x.declaring_type)<<','<<csvq(x.name)<<','<<csvq(x.signature)<<','<<csvq(e)<<"\n";}for(const auto&x:i.properties)m<<"property,"<<hex32(x.token)<<','<<csvq(x.declaring_type)<<','<<csvq(x.name)<<','<<csvq(x.signature)<<','<<csvq("get="+x.getter+";set="+x.setter)<<"\n";for(const auto&x:i.events)m<<"event,"<<hex32(x.token)<<','<<csvq(x.declaring_type)<<','<<csvq(x.name)<<','<<csvq(x.event_type)<<','<<csvq("add="+x.adder+";remove="+x.remover)<<"\n";for(const auto&x:i.member_refs)m<<"memberref,"<<hex32(x.token)<<','<<csvq(x.parent)<<','<<csvq(x.name)<<','<<csvq(x.signature)<<','<<csvq(x.kind)<<"\n";for(const auto&x:i.method_specs)m<<"methodspec,"<<hex32(x.token)<<','<<csvq(x.method)<<",\"\","<<csvq(x.signature)<<",\"\"\n";if(!m){r.error="write .NET members CSV failed";return r;}r.members_csv=mp;r.member_count=i.fields.size()+i.properties.size()+i.events.size()+i.member_refs.size()+i.method_specs.size();r.success=true;return r;}
}
