#include "prts/lua.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <limits>
#include <optional>
#include <sstream>
#include <string_view>
namespace prts { namespace {
#include "lua_opnames.inc"
struct Reader {
    std::span<const std::uint8_t>d; std::size_t p=0; LuaInfo*out=nullptr; int ver=0; bool le=true;std::vector<std::string>saved_strings;
    bool fail(std::string s){if(out&&out->error.empty()){out->error=std::move(s);out->error_offset=p;}return false;}
    bool need(std::size_t n){return n<=d.size()-std::min(p,d.size())||fail("truncated chunk");}
    std::uint8_t b(){if(!need(1))return 0;return d[p++];}
    std::uint64_t rawu(std::size_t n){if(!need(n)||n>8)return 0;std::uint64_t v=0;if(le){for(std::size_t i=0;i<n;++i)v|=std::uint64_t(d[p+i])<<(8*i);}else{for(std::size_t i=0;i<n;++i)v=(v<<8)|d[p+i];}p+=n;return v;}
    std::int64_t raws(std::size_t n){auto v=rawu(n);if(n&&n<8&&(v&(1ull<<(n*8-1))))v|=(~0ull)<<(n*8);return static_cast<std::int64_t>(v);}
    double number(std::size_t n){if(!need(n))return 0;if(n==8){std::uint64_t u=rawu(8);double x;std::memcpy(&x,&u,8);return x;}if(n==4){std::uint32_t u=static_cast<std::uint32_t>(rawu(4));float x;std::memcpy(&x,&u,4);return x;}fail("unsupported lua_Number size");return 0;}
    std::optional<std::uint64_t> var54(){std::uint64_t x=0;for(int i=0;i<10;++i){auto z=b();if(!out->error.empty())return{};if(x>(std::numeric_limits<std::uint64_t>::max()>>7)){fail("varint overflow");return{};}x=(x<<7)|(z&0x7f);if(z&0x80)return x;}fail("unterminated Lua 5.4 varint");return{};}
    std::optional<std::uint64_t> var55(){std::uint64_t x=0;for(int i=0;i<10;++i){auto z=b();if(!out->error.empty())return{};if(x>(std::numeric_limits<std::uint64_t>::max()>>7)){fail("varint overflow");return{};}x=(x<<7)|(z&0x7f);if(!(z&0x80))return x;}fail("unterminated Lua 5.5 varint");return{};}
    std::optional<std::uint64_t> count(){if(ver<=53)return rawu(out->int_size);return ver==54?var54():var55();}
    bool align(std::size_t n){if(n<=1)return true;auto pad=(n-(p%n))%n;if(!need(pad))return false;p+=pad;return true;}
    std::optional<std::string> str(){
        if(ver<=52){auto n=rawu(out->size_t_size);if(!n)return std::string();if(n>d.size()-p||n>(1ull<<31)){fail("string length out of range");return{};}std::string s(reinterpret_cast<const char*>(d.data()+p),std::size_t(n? n-1:0));p+=std::size_t(n);return s;}
        if(ver==53){std::uint64_t n=b();if(n==0xff)n=rawu(out->size_t_size);if(!n)return std::string();--n;if(n>d.size()-p||n>(1ull<<31)){fail("string length out of range");return{};}std::string s(reinterpret_cast<const char*>(d.data()+p),std::size_t(n));p+=std::size_t(n);return s;}
        if(ver==54){auto no=var54();if(!no)return{};auto n=*no;if(!n)return std::string();--n;if(n>d.size()-p||n>(1ull<<31)){fail("string length out of range");return{};}std::string s(reinterpret_cast<const char*>(d.data()+p),std::size_t(n));p+=std::size_t(n);return s;}
        auto no=var55();if(!no)return{};auto n=*no;if(n==0){auto io=var55();if(!io)return{};auto idx=*io;if(idx==0)return std::string();if(idx>saved_strings.size()){fail("invalid Lua 5.5 saved-string index");return{};}return saved_strings[idx-1];}--n;if(n+1>d.size()-p||n>(1ull<<31)){fail("string length out of range");return{};}std::string s(reinterpret_cast<const char*>(d.data()+p),std::size_t(n));p+=std::size_t(n)+1;saved_strings.push_back(s);return s;
    }
};
std::string numrepr(double x){std::ostringstream o;o<<std::setprecision(17)<<x;return o.str();}
const char* opname(int ver,std::uint32_t op){if(ver==51&&op<std::size(kLuaOps_5_1_5))return kLuaOps_5_1_5[op];if(ver==52&&op<std::size(kLuaOps_5_2_4))return kLuaOps_5_2_4[op];if(ver==53&&op<std::size(kLuaOps_5_3_6))return kLuaOps_5_3_6[op];if(ver==54&&op<std::size(kLuaOps_5_4_8))return kLuaOps_5_4_8[op];if(ver==55&&op<std::size(kLuaOps_5_5_0))return kLuaOps_5_5_0[op];return nullptr;}
bool read_code(Reader&r,LuaProto&p){auto no=r.count();if(!no)return false;auto n=*no;if(n>2000000)return r.fail("instruction count too large");if(r.ver==55&&!r.align(r.out->instruction_size))return false;if(n*r.out->instruction_size>r.d.size()-r.p)return r.fail("instruction vector out of range");p.instructions.reserve(std::size_t(n));for(std::uint64_t i=0;i<n;++i){auto raw=static_cast<std::uint32_t>(r.rawu(r.out->instruction_size));LuaInstruction x;x.pc=static_cast<std::uint32_t>(i);x.raw=raw;if(r.out->instruction_size==4){if(r.ver<=53){x.opcode=raw&0x3f;x.a=(raw>>6)&0xff;x.c=(raw>>14)&0x1ff;x.b=(raw>>23)&0x1ff;x.bx=(raw>>14)&0x3ffff;}else{x.opcode=raw&0x7f;x.a=(raw>>7)&0xff;x.b=(raw>>16)&0xff;x.c=(raw>>24)&0xff;x.bx=(raw>>15)&0x1ffff;}if(auto n=opname(r.ver,x.opcode))x.name=n;else{x.name="OP_"+std::to_string(x.opcode);r.out->modified_header=true;}}p.instructions.push_back(std::move(x));}return r.out->error.empty();}
bool read_constants(Reader&r,LuaProto&p){auto no=r.count();if(!no)return false;auto n=*no;if(n>1000000)return r.fail("constant count too large");p.constants.reserve(std::size_t(n));for(std::uint64_t i=0;i<n;++i){auto t=r.b();if(!r.out->error.empty())return false;switch(t){case 0:p.constants.push_back("nil");break;case 1:if(r.ver<=53){auto bv=r.b();p.constants.push_back(bv?"true":"false");}else p.constants.push_back("false");break;case 17:p.constants.push_back("true");break;case 3:{if(r.ver>=54){std::int64_t v;if(r.ver==55){auto x=r.var55();if(!x)return false;auto u=*x;v=(u&1)?static_cast<std::int64_t>(~(u>>1)):static_cast<std::int64_t>(u>>1);}else v=r.raws(r.out->integer_size);p.constants.push_back("int:"+std::to_string(v));}else p.constants.push_back("float:"+numrepr(r.number(r.out->number_size)));break;}case 19:{if(r.ver>=54)p.constants.push_back("float:"+numrepr(r.number(r.out->number_size)));else{auto v=r.raws(r.out->integer_size);p.constants.push_back("int:"+std::to_string(v));}break;}case 4:case 20:{auto s=r.str();if(!s)return false;p.constants.push_back("str:"+*s);break;}default:return r.fail("unknown/modified constant tag "+std::to_string(t));}}return true;}
bool read_proto(Reader&r,const std::string&path,std::optional<std::string>parent_source,int depth){if(depth>256)return r.fail("prototype nesting too deep");LuaProto p;p.path=path;
    if(r.ver==51){auto s=r.str();if(!s)return false;p.source=s->empty()&&parent_source?*parent_source:*s;p.line_defined=static_cast<std::uint32_t>(r.rawu(r.out->int_size));p.last_line_defined=static_cast<std::uint32_t>(r.rawu(r.out->int_size));auto nups=r.b();p.num_params=r.b();p.vararg_or_flags=r.b();p.max_stack=r.b();(void)nups;}
    else if(r.ver==52){p.line_defined=static_cast<std::uint32_t>(r.rawu(r.out->int_size));p.last_line_defined=static_cast<std::uint32_t>(r.rawu(r.out->int_size));p.num_params=r.b();p.vararg_or_flags=r.b();p.max_stack=r.b();}
    else if(r.ver==53){auto s=r.str();if(!s)return false;p.source=s->empty()&&parent_source?*parent_source:*s;p.line_defined=static_cast<std::uint32_t>(r.rawu(r.out->int_size));p.last_line_defined=static_cast<std::uint32_t>(r.rawu(r.out->int_size));p.num_params=r.b();p.vararg_or_flags=r.b();p.max_stack=r.b();}
    else if(r.ver==54){auto s=r.str();if(!s)return false;p.source=s->empty()&&parent_source?*parent_source:*s;auto a=r.count(),b=r.count();if(!a||!b)return false;p.line_defined=*a;p.last_line_defined=*b;p.num_params=r.b();p.vararg_or_flags=r.b();p.max_stack=r.b();}
    else {auto a=r.var55(),b=r.var55();if(!a||!b)return false;p.line_defined=*a;p.last_line_defined=*b;p.num_params=r.b();p.vararg_or_flags=r.b();p.max_stack=r.b();}
    if(!read_code(r,p)||!read_constants(r,p))return false;
    std::uint64_t upn=0,proton=0;
    if(r.ver==51){auto n=r.count();if(!n)return false;proton=*n;for(std::uint64_t i=0;i<proton;++i)if(!read_proto(r,path+"."+std::to_string(i),p.source,depth+1))return false;}
    else if(r.ver==52){
        auto pn=r.count();if(!pn)return false;proton=*pn;if(proton>100000)return r.fail("prototype count too large");for(std::uint64_t i=0;i<proton;++i)if(!read_proto(r,path+"."+std::to_string(i),p.source,depth+1))return false;
        auto un=r.count();if(!un)return false;upn=*un;if(upn>100000)return r.fail("upvalue count too large");for(std::uint64_t i=0;i<upn;++i){r.b();r.b();}
    } else {
        auto un=r.count();if(!un)return false;upn=*un;if(upn>100000)return r.fail("upvalue count too large");for(std::uint64_t i=0;i<upn;++i){r.b();r.b();if(r.ver>=54)r.b();}
        auto pn=r.count();if(!pn)return false;proton=*pn;if(proton>100000)return r.fail("prototype count too large");for(std::uint64_t i=0;i<proton;++i)if(!read_proto(r,path+"."+std::to_string(i),p.source,depth+1))return false;
    }
    if(r.ver==55){auto s=r.str();if(!s)return false;p.source=*s;}
    // debug data
    if(r.ver==51){auto n=r.count();if(!n)return false;if(*n*r.out->int_size>r.d.size()-r.p)return r.fail("lineinfo out of range");r.p+=std::size_t(*n*r.out->int_size);auto ln=r.count();if(!ln)return false;for(std::uint64_t i=0;i<*ln;++i){auto s=r.str();if(!s)return false;p.local_names.push_back(*s);r.rawu(r.out->int_size);r.rawu(r.out->int_size);}auto un=r.count();if(!un)return false;for(std::uint64_t i=0;i<*un;++i){auto s=r.str();if(!s)return false;p.upvalue_names.push_back(*s);}}
    else if(r.ver==52){auto s=r.str();if(!s)return false;p.source=*s;auto n=r.count();if(!n)return false;if(*n*r.out->int_size>r.d.size()-r.p)return r.fail("lineinfo out of range");r.p+=std::size_t(*n*r.out->int_size);auto ln=r.count();if(!ln)return false;for(std::uint64_t i=0;i<*ln;++i){auto x=r.str();if(!x)return false;p.local_names.push_back(*x);r.rawu(r.out->int_size);r.rawu(r.out->int_size);}auto un=r.count();if(!un)return false;for(std::uint64_t i=0;i<*un;++i){auto x=r.str();if(!x)return false;p.upvalue_names.push_back(*x);}}
    else if(r.ver==53){auto n=r.count();if(!n)return false;if(*n*r.out->int_size>r.d.size()-r.p)return r.fail("lineinfo out of range");r.p+=std::size_t(*n*r.out->int_size);auto ln=r.count();if(!ln)return false;for(std::uint64_t i=0;i<*ln;++i){auto x=r.str();if(!x)return false;p.local_names.push_back(*x);r.rawu(r.out->int_size);r.rawu(r.out->int_size);}auto un=r.count();if(!un)return false;for(std::uint64_t i=0;i<*un;++i){auto x=r.str();if(!x)return false;p.upvalue_names.push_back(*x);}}
    else if(r.ver==54){auto n=r.count();if(!n)return false;if(*n>r.d.size()-r.p)return r.fail("lineinfo out of range");r.p+=std::size_t(*n);auto an=r.count();if(!an)return false;for(std::uint64_t i=0;i<*an;++i){if(!r.count()||!r.count())return false;}auto ln=r.count();if(!ln)return false;for(std::uint64_t i=0;i<*ln;++i){auto x=r.str();if(!x)return false;p.local_names.push_back(*x);if(!r.count()||!r.count())return false;}auto un=r.count();if(!un)return false;if(*un)for(std::uint64_t i=0;i<upn;++i){auto x=r.str();if(!x)return false;p.upvalue_names.push_back(*x);}}
    else {auto n=r.var55();if(!n)return false;if(*n>r.d.size()-r.p)return r.fail("lineinfo out of range");r.p+=std::size_t(*n);auto an=r.var55();if(!an)return false;if(*an){if(!r.align(r.out->int_size))return false;auto bytes=*an*2*r.out->int_size;if(bytes>r.d.size()-r.p)return r.fail("abslineinfo out of range");r.p+=std::size_t(bytes);}auto ln=r.var55();if(!ln)return false;for(std::uint64_t i=0;i<*ln;++i){auto x=r.str();if(!x)return false;p.local_names.push_back(*x);if(!r.var55()||!r.var55())return false;}auto un=r.var55();if(!un)return false;if(*un)for(std::uint64_t i=0;i<upn;++i){auto x=r.str();if(!x)return false;p.upvalue_names.push_back(*x);}}
    r.out->protos.push_back(std::move(p));return r.out->error.empty();
}
bool lit(Reader&r,std::string_view s){if(!r.need(s.size()))return false;if(std::memcmp(r.d.data()+r.p,s.data(),s.size())!=0)return r.fail("header literal mismatch");r.p+=s.size();return true;}
bool parse_header(Reader&r){auto&o=*r.out;if(r.d.size()<6||std::memcmp(r.d.data(),"\x1bLua",4)!=0)return r.fail("not a Lua binary chunk");r.p=4;o.version_byte=r.b();o.format=r.b();if(o.format!=0)return r.fail("nonstandard Lua chunk format");int minor=o.version_byte&0xf,major=o.version_byte>>4;if(major!=5||minor<1||minor>5)return r.fail("unsupported Lua version byte");r.ver=50+minor;o.version="5."+std::to_string(minor);constexpr std::string_view data("\x19\x93\r\n\x1a\n",6);
    if(r.ver==51||r.ver==52){o.little_endian=r.b()!=0;r.le=o.little_endian;o.int_size=r.b();o.size_t_size=r.b();o.instruction_size=r.b();o.number_size=r.b();auto integral=r.b();o.integer_size=o.number_size;if(r.ver==52&&!lit(r,data))return false;if(o.int_size<2||o.int_size>8||o.size_t_size<4||o.size_t_size>8||o.instruction_size!=4||(o.number_size!=4&&o.number_size!=8)||integral>1)return r.fail("incompatible Lua 5.1/5.2 header sizes");}
    else if(r.ver==53){if(!lit(r,data))return false;o.int_size=r.b();o.size_t_size=r.b();o.instruction_size=r.b();o.integer_size=r.b();o.number_size=r.b();if(o.int_size<2||o.int_size>8||o.size_t_size<4||o.size_t_size>8||o.instruction_size!=4||o.integer_size>8||o.number_size>8)return r.fail("invalid Lua 5.3 size header");auto pos=r.p;auto li=r.rawu(o.integer_size);if(li!=0x5678){r.le=false;r.p=pos;li=r.rawu(o.integer_size);if(li!=0x5678)return r.fail("Lua 5.3 integer/endianness marker mismatch");}r.number(o.number_size);}
    else if(r.ver==54){if(!lit(r,data))return false;o.instruction_size=r.b();o.integer_size=r.b();o.number_size=r.b();o.int_size=4;o.size_t_size=0;if(o.instruction_size!=4||o.integer_size>8||o.number_size>8)return r.fail("invalid Lua 5.4 size header");if(r.rawu(o.integer_size)!=0x5678)return r.fail("Lua 5.4 integer marker mismatch");r.number(o.number_size);}
    else {if(!lit(r,data))return false;auto is=r.b();if(is<2||is>8)return r.fail("Lua 5.5 int size invalid");o.int_size=is;if(r.raws(is)!=-0x5678)return r.fail("Lua 5.5 int marker mismatch");auto ins=r.b();o.instruction_size=ins;if(ins!=4||r.rawu(ins)!=0x12345678)return r.fail("Lua 5.5 instruction marker mismatch");auto li=r.b();o.integer_size=li;if(li>8||r.raws(li)!=-0x5678)return r.fail("Lua 5.5 integer marker mismatch");auto ns=r.b();o.number_size=ns;if(ns!=4&&ns!=8)return r.fail("Lua 5.5 number size invalid");auto nv=r.number(ns);if(std::fabs(nv+370.5)>1e-6)return r.fail("Lua 5.5 float marker mismatch");}
    o.header_valid=true;return true;}
std::string disasm(const LuaInfo&i){std::ostringstream o;o<<"Lua "<<i.version<<" bytecode\n";for(const auto&p:i.protos){o<<"\nProto "<<p.path<<" source="<<p.source<<" lines="<<p.line_defined<<"-"<<p.last_line_defined<<" params="<<unsigned(p.num_params)<<" stack="<<unsigned(p.max_stack)<<"\n";if(!p.constants.empty()){o<<"Constants:\n";for(std::size_t n=0;n<p.constants.size();++n)o<<"  K"<<n<<" = "<<p.constants[n]<<"\n";}o<<"Instructions:\n";for(const auto&x:p.instructions)o<<"  "<<std::setw(5)<<x.pc<<"  0x"<<std::hex<<std::setw(8)<<std::setfill('0')<<x.raw<<std::setfill(' ')<<std::dec<<"  "<<x.name<<" A="<<x.a<<" B="<<x.b<<" C="<<x.c<<" Bx="<<x.bx<<"\n";}return o.str();}
}
LuaInfo parse_luac(std::span<const std::uint8_t>d){LuaInfo o;Reader r{d,0,&o,0,true,{}};if(!parse_header(r))return o;if(r.ver>=53)r.b();if(!read_proto(r,"0",std::nullopt,0))return o;o.parsed_bytes=r.p;o.valid=o.error.empty()&&!o.protos.empty();if(r.p<d.size())o.modified_header=true;return o;}
Finding lua_finding(const LuaInfo&i){Finding f;f.kind="bytecode";f.family="Lua bytecode";if(!i.valid){f.state="FAILED";if(!i.error.empty()){std::ostringstream eo;eo<<i.error<<" at 0x"<<std::hex<<i.error_offset;f.negative_evidence.push_back(eo.str());}return f;}f.state="CONFIRMED";f.variant=i.version;f.evidence={"Lua chunk header/number format validated","prototype tree and constants/instructions structurally parsed"};f.fields["prototypes"]=std::to_string(i.protos.size());std::size_t ins=0,ks=0;for(const auto&p:i.protos){ins+=p.instructions.size();ks+=p.constants.size();}f.fields["instructions"]=std::to_string(ins);f.fields["constants"]=std::to_string(ks);if(i.modified_header)f.negative_evidence.push_back("trailing bytes or nonstandard opcode evidence present");return f;}
LuaExtractResult extract_lua_disasm(const LuaInfo&i,const std::filesystem::path&out){LuaExtractResult r;if(!i.valid){r.error="Lua chunk not valid";return r;}std::ofstream f(out,std::ios::binary);if(!f){r.error="cannot create Lua disassembly";return r;}auto s=disasm(i);f.write(s.data(),static_cast<std::streamsize>(s.size()));r.success=bool(f);r.disasm_path=out;if(!r.success)r.error="write failed";return r;}
}
