#include "prts/renpy.hpp"
#include "miniz.h"
#include <algorithm>
#include <array>
#include <cctype>
#include <cstring>
#include <fstream>
#include <memory>
#include <optional>
#include <set>
#include <sstream>
namespace prts { namespace {
std::uint32_t u32(std::span<const std::uint8_t>d,std::size_t o){if(o+4>d.size())return 0;return std::uint32_t(d[o])|(std::uint32_t(d[o+1])<<8)|(std::uint32_t(d[o+2])<<16)|(std::uint32_t(d[o+3])<<24);}
std::optional<std::vector<std::uint8_t>> zdec(std::span<const std::uint8_t>in){for(std::size_t cap=4096;cap<=256ull*1024*1024;cap*=2){std::vector<std::uint8_t>out(cap);mz_ulong n=static_cast<mz_ulong>(out.size());auto rc=mz_uncompress(out.data(),&n,in.data(),static_cast<mz_ulong>(in.size()));if(rc==MZ_OK){out.resize(n);return out;}if(rc!=MZ_BUF_ERROR)return{};}return{};}
bool pickle_like(std::span<const std::uint8_t>d,std::uint32_t&proto){if(d.size()<3)return false;proto=0;if(d[0]==0x80){proto=d[1];if(proto>5)return false;}auto e=d.size();while(e&&std::isspace(d[e-1]))--e;if(!e||d[e-1]!='.')return false;bool clue=false;constexpr std::array<std::string_view,5> clues={"renpy.","collections", "__builtin__", "builtins", "deferred_parse_errors"};for(auto s:clues)if(std::search(d.begin(),d.end(),s.begin(),s.end())!=d.end()){clue=true;break;}return clue;}
void pickle_hints(std::span<const std::uint8_t>d,RenpyRpycInfo&o){std::set<std::string>g,s;for(std::size_t i=0;i+3<d.size();i++){
        if(d[i]=='c'){auto a=i+1,b=a;while(b<d.size()&&b-a<256&&d[b]!='\n'&&d[b]>=0x20&&d[b]<0x7f)++b;if(b>=d.size()||d[b]!='\n')continue;auto c=b+1,e=c;while(e<d.size()&&e-c<256&&d[e]!='\n'&&d[e]>=0x20&&d[e]<0x7f)++e;if(e<d.size()&&d[e]=='\n'){std::string x(reinterpret_cast<const char*>(d.data()+a),b-a);x+=' ';x.append(reinterpret_cast<const char*>(d.data()+c),e-c);if(x.find("renpy")!=std::string::npos||x.find("collections")!=std::string::npos||x.find("builtin")!=std::string::npos)g.insert(x);}}
        if(d[i]=='X'&&i+5<=d.size()){auto n=u32(d,i+1);if(n&&n<1024&&i+5+n<=d.size()){std::string x(reinterpret_cast<const char*>(d.data()+i+5),n);std::size_t ok=0;for(unsigned char c:x)if(c>=0x20&&c<0x7f)++ok;if(ok*100/x.size()>90&&(x.find("renpy")!=std::string::npos||x.find("flag")!=std::string::npos||x.find("label")!=std::string::npos||x.find("version")!=std::string::npos))s.insert(x);}}
    }o.globals.assign(g.begin(),g.end());o.string_hints.assign(s.begin(),s.end());}
std::optional<std::vector<RenpySlot>> parse_slots(std::span<const std::uint8_t>d,std::size_t pos){std::vector<RenpySlot>s;std::set<std::uint32_t>ids;for(std::size_t n=0;n<4096&&pos+12<=d.size();n++,pos+=12){auto id=u32(d,pos),st=u32(d,pos+4),ln=u32(d,pos+8);if(id==0&&st==0&&ln==0)return s.empty()?std::optional<std::vector<RenpySlot>>{}:s;if(!id||ids.count(id)||st>d.size()||ln>d.size()-st)return{};ids.insert(id);s.push_back({id,st,ln});}return{};}
std::optional<std::size_t> header_scan(std::span<const std::uint8_t>d){for(std::size_t p=0;p+36<=d.size();p++){auto a=u32(d,p),b=u32(d,p+4),c=u32(d,p+8),dd=u32(d,p+12),e=u32(d,p+16),g=u32(d,p+24);if(a==1&&dd==2&&g==0&&std::uint64_t(b)+c==e){if(auto s=parse_slots(d,p);s&&std::any_of(s->begin(),s->end(),[](auto&x){return x.id==1;}))return p;}}return{};}
std::optional<std::vector<std::uint8_t>> slot_one(std::span<const std::uint8_t>d,const std::vector<RenpySlot>&s){auto it=std::find_if(s.begin(),s.end(),[](auto&x){return x.id==1;});if(it==s.end())return{};return std::vector<std::uint8_t>(d.begin()+it->start,d.begin()+it->start+it->length);}
bool ishex(std::span<const std::uint8_t>d){return !d.empty()&&std::all_of(d.begin(),d.end(),[](auto c){return std::isxdigit(c)!=0;});}
std::optional<std::vector<std::uint8_t>> hexdec(std::span<const std::uint8_t>d){if(d.size()%2||!ishex(d))return{};auto val=[](std::uint8_t c){if(c>='0'&&c<='9')return c-'0';c=std::uint8_t(std::tolower(c));return c-'a'+10;};std::vector<std::uint8_t>o(d.size()/2);for(std::size_t i=0;i<o.size();i++)o[i]=std::uint8_t((val(d[i*2])<<4)|val(d[i*2+1]));return o;}
std::optional<std::vector<std::uint8_t>> b64dec(std::span<const std::uint8_t>d){static const std::string abc="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";std::array<int,256>map;map.fill(-1);for(int i=0;i<64;i++)map[static_cast<unsigned char>(abc[i])]=i;std::vector<std::uint8_t>o;int val=0,bits=-8;for(auto c:d){if(std::isspace(c))continue;if(c=='=')break;if(map[c]<0)return{};val=(val<<6)+map[c];bits+=6;if(bits>=0){o.push_back(std::uint8_t((val>>bits)&0xff));bits-=8;}}return o.empty()?std::optional<std::vector<std::uint8_t>>{}:o;}
bool unwrap(std::vector<std::uint8_t>&raw,RenpyRpycInfo&o){for(int layer=0;layer<10;layer++){std::uint32_t proto=0;if(pickle_like(raw,proto)){o.pickle_protocol=proto;o.pickle_payload=raw;pickle_hints(raw,o);return true;}if(auto z=zdec(raw)){raw=std::move(*z);o.layers.push_back("zlib");continue;}if(auto h=hexdec(raw)){raw=std::move(*h);o.layers.push_back("hex");continue;}if(auto b=b64dec(raw)){raw=std::move(*b);o.layers.push_back("base64");continue;}break;}return false;}
}
RenpyRpycInfo detect_rpyc(std::span<const std::uint8_t>d,const std::filesystem::path&path){RenpyRpycInfo o;auto ext=path.extension().string();std::transform(ext.begin(),ext.end(),ext.begin(),[](unsigned char c){return char(std::tolower(c));});bool ext_hint=ext==".rpyc"||ext==".rpymc";
    if(d.size()>=10&&std::memcmp(d.data(),"RENPY RPC2",10)==0){auto slots=parse_slots(d,10);if(!slots){o.error="RENPY RPC2 header present but slot table invalid";return o;}o.slots=*slots;auto raw=slot_one(d,o.slots);if(!raw){o.error="RPYC2 slot 1 missing";return o;}o.variant="RPYC2";o.extractor="normal-header";if(!unwrap(*raw,o)){o.error="RPYC2 slot 1 recovered but known decode layers did not produce a Ren'Py pickle";return o;}o.valid=true;return o;}
    // Legacy RPYC v1 is simply zlib(pickle). Only accept without extension if the decompressed payload has Ren'Py pickle clues.
    {std::vector<std::uint8_t>raw(d.begin(),d.end());RenpyRpycInfo x;x.legacy=true;x.variant="RPYC1";x.extractor="legacy-zlib";if(unwrap(raw,x)&&(!x.layers.empty()&&x.layers.front()=="zlib")&&(ext_hint||!x.globals.empty())){x.valid=true;return x;}}
    // Mutation-resistant slot header scan.
    if(auto hp=header_scan(d)){auto slots=parse_slots(d,*hp);if(slots){o.slots=*slots;auto raw=slot_one(d,o.slots);if(raw){o.modified_header=true;o.variant="RPYC2-modified-header";o.extractor="slot-table-scan";if(unwrap(*raw,o)){o.valid=true;return o;}}}}
    // Last resort: find zlib streams and accept only if they decode to a Ren'Py pickle.
    for(std::size_t p=0;p+2<d.size();p++){if(d[p]!=0x78||((std::uint32_t(d[p])<<8)+d[p+1])%31)continue;auto z=zdec(d.subspan(p));if(!z)continue;std::vector<std::uint8_t>raw=*z;o.layers={"zlib-scan"};std::uint32_t proto=0;if(pickle_like(raw,proto)){o.modified_header=true;o.variant="RPYC-recovered-zlib";o.extractor="zlib-scan";o.pickle_protocol=proto;o.pickle_payload=std::move(raw);pickle_hints(o.pickle_payload,o);o.valid=true;return o;}}
    if(ext_hint)o.error=".rpyc/.rpymc extension present but no supported RPYC layout decoded";
    return o;}
Finding renpy_rpyc_finding(const RenpyRpycInfo&i){Finding f;f.kind="ecosystem";f.family="Ren'Py RPYC";if(!i.valid){f.state="FAILED";if(!i.error.empty())f.negative_evidence.push_back(i.error);return f;}f.state="CONFIRMED";f.variant=i.variant;f.evidence.push_back("RPYC storage layer recovered using "+i.extractor);f.evidence.push_back("decoded slot payload terminates as a Ren'Py-compatible pickle");f.fields["pickle_protocol"]=std::to_string(i.pickle_protocol);f.fields["pickle_size"]=std::to_string(i.pickle_payload.size());f.fields["global_refs"]=std::to_string(i.globals.size());if(i.modified_header)f.evidence.push_back("standard RPYC header was modified/absent but payload was structurally recovered");if(!i.layers.empty()){std::string x;for(auto&s:i.layers){if(!x.empty())x+=",";x+=s;}f.fields["decode_layers"]=x;}for(const auto&g:i.globals)if(g.rfind("renpy",0)==0)f.evidence.push_back("pickle class ref: "+g);f.suggested_actions={"extract decoded pickle","optional Ren'Py runtime-assisted decompile"};return f;}
RenpyExtractResult extract_rpyc(const RenpyRpycInfo&i,const std::filesystem::path&out){RenpyExtractResult r;if(!i.valid||i.pickle_payload.empty()){r.error="no decoded RPYC pickle";return r;}std::ofstream f(out,std::ios::binary);if(!f){r.error="cannot create RPYC pickle artifact";return r;}f.write(reinterpret_cast<const char*>(i.pickle_payload.data()),static_cast<std::streamsize>(i.pickle_payload.size()));r.success=bool(f);r.pickle_path=out;if(!r.success)r.error="write failed";return r;}
namespace {
struct PNode { enum K{Null,Mark,Int,Str,List,Tuple,Dict} k=Null; std::int64_t i=0; std::string s; std::vector<std::shared_ptr<PNode>> a; std::vector<std::pair<std::shared_ptr<PNode>,std::shared_ptr<PNode>>> m; };
using NP=std::shared_ptr<PNode>;
NP pn(PNode::K k){auto n=std::make_shared<PNode>();n->k=k;return n;}
std::uint64_t le64(std::span<const std::uint8_t>d,std::size_t o,std::size_t n){if(o+n>d.size()||n>8)return 0;std::uint64_t v=0;for(std::size_t i=0;i<n;i++)v|=std::uint64_t(d[o+i])<<(8*i);return v;}
std::optional<NP> restricted_unpickle(std::span<const std::uint8_t>d,std::string&err){std::vector<NP>st,memo;std::size_t p=0;auto pop=[&]()->NP{if(st.empty())return{};auto x=st.back();st.pop_back();return x;};auto markpos=[&]()->std::optional<std::size_t>{for(std::size_t i=st.size();i>0;i--)if(st[i-1]->k==PNode::Mark)return i-1;return{};};auto readstr=[&](std::size_t n)->std::optional<std::string>{if(n>d.size()-p)return{};std::string x(reinterpret_cast<const char*>(d.data()+p),n);p+=n;return x;};auto memo_set=[&](std::size_t idx){if(st.empty())return false;if(memo.size()<=idx)memo.resize(idx+1);memo[idx]=st.back();return true;};
    while(p<d.size()){auto op=d[p++];switch(op){
      case 0x80: if(p>=d.size()){err="PROTO truncated";return{};} if(d[p++]>5){err="pickle protocol >5 unsupported";return{};} break;
      case 0x95: if(p+8>d.size()){err="FRAME truncated";return{};} p+=8; break;
      case '}': st.push_back(pn(PNode::Dict));break; case ']':st.push_back(pn(PNode::List));break;case ')':st.push_back(pn(PNode::Tuple));break;case '(':st.push_back(pn(PNode::Mark));break;case 'N':st.push_back(pn(PNode::Null));break;
      case 0x88:{auto n=pn(PNode::Int);n->i=1;st.push_back(n);break;}case 0x89:{auto n=pn(PNode::Int);n->i=0;st.push_back(n);break;}
      case 'K':{if(p>=d.size()){err="BININT1 truncated";return{};}auto n=pn(PNode::Int);n->i=d[p++];st.push_back(n);break;}
      case 'M':{if(p+2>d.size()){err="BININT2 truncated";return{};}auto n=pn(PNode::Int);n->i=std::int64_t(d[p]|(d[p+1]<<8));p+=2;st.push_back(n);break;}
      case 'J':{if(p+4>d.size()){err="BININT truncated";return{};}auto n=pn(PNode::Int);std::uint32_t v=u32(d,p);p+=4;n->i=static_cast<std::int32_t>(v);st.push_back(n);break;}
      case 0x8a:{if(p>=d.size()){err="LONG1 truncated";return{};}auto nbytes=d[p++];if(!nbytes||nbytes>8||p+nbytes>d.size()){err="LONG1 width unsupported";return{};}auto v=le64(d,p,nbytes);bool neg=d[p+nbytes-1]&0x80;p+=nbytes;if(neg&&nbytes<8)v|=(~0ull)<<(nbytes*8);auto n=pn(PNode::Int);n->i=static_cast<std::int64_t>(v);st.push_back(n);break;}
      case 0x8b:{if(p+4>d.size()){err="LONG4 truncated";return{};}auto nb=u32(d,p);p+=4;if(!nb||nb>8||p+nb>d.size()){err="LONG4 width unsupported";return{};}auto v=le64(d,p,nb);bool neg=d[p+nb-1]&0x80;p+=nb;if(neg&&nb<8)v|=(~0ull)<<(nb*8);auto n=pn(PNode::Int);n->i=static_cast<std::int64_t>(v);st.push_back(n);break;}
      case 'X':case 'T':case 'B':{if(p+4>d.size()){err="length string truncated";return{};}auto n=u32(d,p);p+=4;auto x=readstr(n);if(!x){err="string payload truncated";return{};}auto z=pn(PNode::Str);z->s=std::move(*x);st.push_back(z);break;}
      case 'U':case 'C':case 0x8c:{if(p>=d.size()){err="short string truncated";return{};}auto n=d[p++];auto x=readstr(n);if(!x){err="short string payload truncated";return{};}auto z=pn(PNode::Str);z->s=std::move(*x);st.push_back(z);break;}
      case 0x8d:case 0x8e:{if(p+8>d.size()){err="64-bit string length truncated";return{};}auto n=le64(d,p,8);p+=8;if(n>(1ull<<31)){err="string too large";return{};}auto x=readstr(std::size_t(n));if(!x){err="string payload truncated";return{};}auto z=pn(PNode::Str);z->s=std::move(*x);st.push_back(z);break;}
      case 'V':{auto e=std::find(d.begin()+static_cast<std::ptrdiff_t>(p),d.end(),std::uint8_t('\n'));if(e==d.end()){err="UNICODE newline missing";return{};}auto n=std::size_t(e-(d.begin()+static_cast<std::ptrdiff_t>(p)));auto x=readstr(n);++p;auto z=pn(PNode::Str);z->s=std::move(*x);st.push_back(z);break;}
      case 'q': if(p>=d.size()||!memo_set(d[p++])){err="BINPUT invalid";return{};}break;case 'r':if(p+4>d.size()){err="LONG_BINPUT truncated";return{};}else{auto i=u32(d,p);p+=4;if(!memo_set(i)){err="LONG_BINPUT invalid";return{};}}break;
      case 0x94: if(!memo_set(memo.size())){err="MEMOIZE invalid";return{};}break;
      case 'h':{if(p>=d.size()){err="BINGET truncated";return{};}auto i=d[p++];if(i>=memo.size()||!memo[i]){err="BINGET bad index";return{};}st.push_back(memo[i]);break;}case 'j':{if(p+4>d.size()){err="LONG_BINGET truncated";return{};}auto i=u32(d,p);p+=4;if(i>=memo.size()||!memo[i]){err="LONG_BINGET bad index";return{};}st.push_back(memo[i]);break;}
      case 0x85:case 0x86:case 0x87:{int n=op-0x84;if(st.size()<std::size_t(n)){err="TUPLEn underflow";return{};}auto t=pn(PNode::Tuple);t->a.assign(st.end()-n,st.end());st.resize(st.size()-n);st.push_back(t);break;}
      case 't':{auto m=markpos();if(!m){err="TUPLE mark missing";return{};}auto t=pn(PNode::Tuple);t->a.assign(st.begin()+*m+1,st.end());st.resize(*m);st.push_back(t);break;}
      case 'a':{auto v=pop();if(!v||st.empty()||st.back()->k!=PNode::List){err="APPEND invalid";return{};}st.back()->a.push_back(v);break;}
      case 'e':{auto m=markpos();if(!m||*m==0||st[*m-1]->k!=PNode::List){err="APPENDS invalid";return{};}auto l=st[*m-1];l->a.insert(l->a.end(),st.begin()+*m+1,st.end());st.resize(*m);break;}
      case 's':{auto v=pop(),k=pop();if(!v||!k||st.empty()||st.back()->k!=PNode::Dict){err="SETITEM invalid";return{};}st.back()->m.emplace_back(k,v);break;}
      case 'u':{auto m=markpos();if(!m||*m==0||st[*m-1]->k!=PNode::Dict||(st.size()-*m-1)%2){err="SETITEMS invalid";return{};}auto di=st[*m-1];for(std::size_t i=*m+1;i+1<st.size();i+=2)di->m.emplace_back(st[i],st[i+1]);st.resize(*m);break;}
      case '0':if(!pop()){err="POP underflow";return{};}break;case '1':{auto m=markpos();if(!m){err="POP_MARK missing";return{};}st.resize(*m);break;}case '2':if(st.empty()){err="DUP underflow";return{};}else st.push_back(st.back());break;
      case '.': if(st.empty()){err="STOP empty stack";return{};} return st.back();
      default:{std::ostringstream o;o<<"restricted pickle rejected opcode 0x"<<std::hex<<unsigned(op)<<" at 0x"<<(p-1);err=o.str();return{};}
    }}err="pickle STOP missing";return{};}
std::optional<std::uint64_t> parse_hex(std::string_view s){std::uint64_t v=0;if(s.empty()||s.size()>16)return{};for(char c:s){unsigned x;if(c>='0'&&c<='9')x=c-'0';else if(c>='a'&&c<='f')x=c-'a'+10;else if(c>='A'&&c<='F')x=c-'A'+10;else return{};v=(v<<4)|x;}return v;}
std::string rpa_clean(std::string s){std::replace(s.begin(),s.end(),'\\','/');while(!s.empty()&&s.front()=='/')s.erase(s.begin());return s;}
}
RenpyRpaInfo detect_rpa(std::span<const std::uint8_t>d,const std::filesystem::path&path){(void)path;RenpyRpaInfo r;if(d.size()<16)return r;auto nl=std::find(d.begin(),d.begin()+std::min<std::size_t>(d.size(),256),std::uint8_t('\n'));if(nl==d.begin()+std::min<std::size_t>(d.size(),256))return r;std::string line(reinterpret_cast<const char*>(d.data()),nl-d.begin());std::istringstream in(line);std::vector<std::string>v;for(std::string x;in>>x;)v.push_back(x);if(v.empty()||(v[0]!="RPA-2.0"&&v[0]!="RPA-3.0"&&v[0]!="RPA-3.2"))return r;r.version=v[0];if(v.size()<2){r.error="RPA header index offset missing";return r;}auto off=parse_hex(v[1]);if(!off||*off>=d.size()){r.error="RPA index offset invalid";return r;}r.index_offset=*off;if(r.version=="RPA-3.0"){for(std::size_t i=2;i<v.size();i++){auto k=parse_hex(v[i]);if(!k){r.error="RPA3 key invalid";return r;}r.key^=static_cast<std::uint32_t>(*k);}}else if(r.version=="RPA-3.2"){for(std::size_t i=3;i<v.size();i++){auto k=parse_hex(v[i]);if(!k){r.error="RPA3.2 key invalid";return r;}r.key^=static_cast<std::uint32_t>(*k);}}
    auto dec=zdec(d.subspan(r.index_offset));if(!dec){r.error="RPA zlib index decompression failed";return r;}std::string perr;auto root=restricted_unpickle(*dec,perr);if(!root||(*root)->k!=PNode::Dict){r.error="RPA restricted pickle parse failed: "+perr;return r;}for(const auto&kv:(*root)->m){if(!kv.first||kv.first->k!=PNode::Str||!kv.second||kv.second->k!=PNode::List||kv.second->a.empty())continue;auto t=kv.second->a.front();if(!t||t->k!=PNode::Tuple||(t->a.size()!=2&&t->a.size()!=3)||!t->a[0]||!t->a[1]||t->a[0]->k!=PNode::Int||t->a[1]->k!=PNode::Int)continue;auto o=std::uint64_t(t->a[0]->i),ln2=std::uint64_t(t->a[1]->i);if(r.version!="RPA-2.0"){o^=r.key;ln2^=r.key;}RenpyRpaEntry e;e.name=kv.first->s;e.offset=o;e.length=ln2;if(t->a.size()==3&&t->a[2]&&t->a[2]->k==PNode::Str)e.prefix.assign(t->a[2]->s.begin(),t->a[2]->s.end());if(o>d.size()||ln2<e.prefix.size()||ln2-e.prefix.size()>d.size()-o){r.error="RPA entry range invalid for "+e.name;return r;}r.entries.push_back(std::move(e));}if(r.entries.empty()){r.error="RPA index contained no supported file entries";return r;}r.valid=true;return r;}
Finding renpy_rpa_finding(const RenpyRpaInfo&i){Finding f;f.kind="container";f.family="Ren'Py RPA";if(!i.valid){f.state="FAILED";if(!i.error.empty())f.negative_evidence.push_back(i.error);return f;}f.state="CONFIRMED";f.variant=i.version;f.evidence={"RPA header/index offset validated","zlib index decoded with restricted non-executable pickle parser","all extracted file offset/length ranges validated"};f.fields["files"]=std::to_string(i.entries.size());f.fields["index_offset"]=std::to_string(i.index_offset);if(i.version!="RPA-2.0")f.fields["xor_key"]="0x"+std::to_string(i.key);f.suggested_actions={"extract RPA files","recursively analyze extracted RPYC"};return f;}
RenpyRpaExtractResult extract_rpa(std::span<const std::uint8_t>d,const RenpyRpaInfo&i,const std::filesystem::path&outdir,bool core_only,std::uint64_t max_output_bytes,std::uint32_t max_output_files){RenpyRpaExtractResult r;r.core_only=core_only;if(!i.valid){r.error="RPA not valid";return r;}std::error_code ec;std::filesystem::create_directories(outdir,ec);if(ec){r.error=ec.message();return r;}auto script=[](std::string name){std::transform(name.begin(),name.end(),name.begin(),[](unsigned char c){return char(std::tolower(c));});return name.size()>=4&&(name.ends_with(".rpyc")||name.ends_with(".rpymc")||name.ends_with(".rpy"));};std::uint64_t eligible=0;for(const auto&e:i.entries)if(!core_only||script(e.name))++eligible;for(const auto&e:i.entries){if(core_only&&!script(e.name))continue;auto n=rpa_clean(e.name);if(n.empty()||n.find("..")!=std::string::npos)continue;if(r.file_count>=max_output_files||e.length>max_output_bytes-r.output_bytes){r.budget_exhausted=true;++r.omitted_count;r.omitted_bytes=e.length>std::numeric_limits<std::uint64_t>::max()-r.omitted_bytes?std::numeric_limits<std::uint64_t>::max():r.omitted_bytes+e.length;continue;}auto p=outdir/std::filesystem::path(n);std::filesystem::create_directories(p.parent_path(),ec);ec.clear();std::ofstream o(p,std::ios::binary|std::ios::trunc);if(!o)continue;if(!e.prefix.empty())o.write(reinterpret_cast<const char*>(e.prefix.data()),e.prefix.size());auto remain=e.length-e.prefix.size();o.write(reinterpret_cast<const char*>(d.data()+e.offset),static_cast<std::streamsize>(remain));if(o){++r.file_count;r.output_bytes+=e.length;r.files.push_back(p);}}r.success=core_only?(r.file_count>0||eligible==0):(r.file_count==i.entries.size()&&r.file_count>0&&!r.budget_exhausted);r.output_dir=outdir;if(!r.success)r.error=core_only?"no Ren'Py script entries materialized":"not all RPA entries extracted";return r;}

}
