#include "prts/wxapkg.hpp"
#include "prts/sha1.hpp"
#include "prts/path_utf8.hpp"
extern "C" {
#include "aes.h"
}
#include <algorithm>
#include <array>
#include <cctype>
#include <cstring>
#include <fstream>
#include <optional>
namespace prts { namespace {
std::uint32_t be32(std::span<const std::uint8_t>d,std::size_t o){if(o+4>d.size())return 0;return std::uint32_t(d[o])<<24|std::uint32_t(d[o+1])<<16|std::uint32_t(d[o+2])<<8|d[o+3];}
bool safe_name(const std::string&s){if(s.empty()||s.size()>4096||s.find("..")!=std::string::npos)return false;std::size_t ok=0;for(unsigned char c:s)if(c>=0x20&&c<0x7f)++ok;return ok*100/s.size()>90;}
std::string infer_wxid(const std::filesystem::path&p){for(auto it=p.end();it!=p.begin();){--it;auto s=path_utf8(*it);if(s.size()!=18||s.rfind("wx",0)!=0)continue;bool ok=true;for(std::size_t i=2;i<s.size();++i)if(!std::isalnum(static_cast<unsigned char>(s[i]))){ok=false;break;}if(ok)return s;}return{};}
WxapkgInfo parse_plain(std::span<const std::uint8_t>d){WxapkgInfo w;if(d.size()<18||d[0]!=0xbe||d[13]!=0xed){w.error="wxapkg header markers missing";return w;}auto info=be32(d,1),index=be32(d,5),body=be32(d,9);(void)info;auto count=be32(d,14);if(index<4){w.error="wxapkg index length smaller than file-count field";return w;}if(!count){w.error="wxapkg file count is zero";return w;}if(count>100000){w.error="wxapkg file count unreasonable";return w;}auto body_start=std::uint64_t(14)+index;if(body_start>d.size()||body>std::uint64_t(d.size())-body_start){w.error="wxapkg index/body geometry exceeds file";return w;}auto body_end=body_start+body;std::size_t p=18;w.entries.reserve(count);for(std::uint32_t i=0;i<count;i++){if(p+4>d.size()){w.error="wxapkg index truncated";return w;}auto nl=be32(d,p);p+=4;if(!nl||nl>4096||nl>d.size()-p){w.error="wxapkg filename length invalid";return w;}std::string name(reinterpret_cast<const char*>(d.data()+p),nl);p+=nl;if(!safe_name(name)||p+8>d.size()){w.error="wxapkg filename/index invalid";return w;}auto off=be32(d,p),sz=be32(d,p+4);p+=8;if(off<body_start||off>body_end||sz>body_end-off){w.error="wxapkg file range falls outside declared body";return w;}w.entries.push_back({std::move(name),off,sz});}if(p!=body_start){ // index length includes the 4-byte fileCount
        auto delta=p>body_start?p-body_start:body_start-p;if(delta>16){w.error="wxapkg index length does not match entry table";return w;}}
    w.valid=true;w.index_length=index;w.body_length=body;return w;}
std::optional<std::vector<std::uint8_t>> decrypt_pc(std::span<const std::uint8_t>d,const std::string&wxid){if(d.size()<6+1024||std::memcmp(d.data(),"V1MMWX",6)!=0||wxid.empty())return{};std::array<std::uint8_t,32>key{};pbkdf2_hmac_sha1(wxid,"saltiest",1000,key);std::array<std::uint8_t,16>iv{};constexpr std::string_view ivs="the iv: 16 bytes";std::copy(ivs.begin(),ivs.end(),iv.begin());std::array<std::uint8_t,1024>head{};std::copy_n(d.begin()+6,1024,head.begin());AES_ctx ctx;AES_init_ctx_iv(&ctx,key.data(),iv.data());AES_CBC_decrypt_buffer(&ctx,head.data(),head.size());std::vector<std::uint8_t>out;out.reserve(d.size()-6);out.insert(out.end(),head.begin(),head.begin()+1023);auto xor_key=std::uint8_t(0x66);if(wxid.size()>=2)xor_key=std::uint8_t(wxid[wxid.size()-2]);for(std::size_t i=6+1024;i<d.size();i++)out.push_back(d[i]^xor_key);return out;}
std::string clean(std::string s){std::replace(s.begin(),s.end(),'\\','/');while(!s.empty()&&s.front()=='/')s.erase(s.begin());return s;}
}
WxapkgInfo detect_wxapkg(std::span<const std::uint8_t>d,const std::filesystem::path&path,std::string wxid){if(wxid.empty())wxid=infer_wxid(path);if(d.size()>=6&&std::memcmp(d.data(),"V1MMWX",6)==0){WxapkgInfo w;w.valid=true;w.encrypted=true;w.wxid=wxid;if(wxid.empty()){w.error="PC encrypted wxapkg confirmed; wxid required for decryption";return w;}auto dec=decrypt_pc(d,wxid);if(!dec){w.error="encrypted wxapkg decryption setup failed";return w;}auto plain=parse_plain(*dec);if(!plain.valid){w.error="wxid/decryption did not produce a structurally valid wxapkg: "+plain.error;return w;}plain.encrypted=true;plain.decrypted=true;plain.wxid=wxid;plain.plaintext=std::move(*dec);return plain;}auto w=parse_plain(d);w.wxid=wxid;return w;}
Finding wxapkg_finding(const WxapkgInfo&w){Finding f;f.kind="ecosystem";f.family="WeChat Mini Program";if(!w.valid){f.state="FAILED";if(!w.error.empty())f.negative_evidence.push_back(w.error);return f;}f.state="CONFIRMED";if(w.encrypted&&!w.decrypted){f.variant="encrypted wxapkg";f.evidence={"V1MMWX PC-cache encryption marker matched"};f.negative_evidence.push_back(w.error);f.suggested_actions.push_back("provide --wxid=<appid> to decrypt and unpack");}else{f.variant=w.encrypted?"decrypted wxapkg":"wxapkg";f.evidence={"wxapkg 0xBE/0xED header and file index structurally validated"};if(w.decrypted)f.evidence.push_back("PBKDF2/AES-CBC/XOR decryption produced a validated wxapkg");f.fields["files"]=std::to_string(w.entries.size());}if(!w.wxid.empty())f.fields["wxid"]=w.wxid;return f;}
WxapkgExtractResult extract_wxapkg(std::span<const std::uint8_t>original,const WxapkgInfo&w,const std::filesystem::path&outdir,bool core_only,std::uint64_t max_output_bytes,std::uint32_t max_output_files){WxapkgExtractResult r;r.core_only=core_only;if(!w.valid||w.entries.empty()){r.error=w.encrypted&&!w.decrypted?"encrypted wxapkg requires correct wxid":"no validated wxapkg entries";return r;}auto data=w.decrypted?std::span<const std::uint8_t>(w.plaintext):original;auto score=[](std::string name){std::replace(name.begin(),name.end(),'\\','/');std::transform(name.begin(),name.end(),name.begin(),[](unsigned char c){return char(std::tolower(c));});auto slash=name.find_last_of('/');auto base=slash==std::string::npos?name:name.substr(slash+1);if(base=="app.js"||base=="app.json"||base=="app-config.json"||base=="app-service.js")return 1000;auto dot=base.find_last_of('.');auto ext=dot==std::string::npos?std::string{}:base.substr(dot);if(ext==".js"||ext==".wxs")return 900;if(ext==".wxml"||ext==".wxss")return 800;if(ext==".json")return 700;return 0;};std::vector<const WxapkgEntry*>selected;for(const auto&e:w.entries)if(!core_only||score(e.name))selected.push_back(&e);if(core_only)std::stable_sort(selected.begin(),selected.end(),[&](auto*a,auto*b){auto as=score(a->name),bs=score(b->name);return as!=bs?as>bs:a->name<b->name;});if(core_only&&selected.empty()){r.success=true;r.output_dir=outdir;return r;}std::error_code ec;std::filesystem::create_directories(outdir,ec);if(ec){r.error=ec.message();return r;}for(const auto*ep:selected){const auto&e=*ep;if(e.offset>data.size()||e.size>data.size()-e.offset)continue;if(r.file_count>=max_output_files||e.size>max_output_bytes-r.output_bytes){r.budget_exhausted=true;++r.omitted_count;r.omitted_bytes=e.size>std::numeric_limits<std::uint64_t>::max()-r.omitted_bytes?std::numeric_limits<std::uint64_t>::max():r.omitted_bytes+e.size;continue;}auto n=clean(e.name);if(n.empty()||n.find("..")!=std::string::npos)continue;auto p=outdir/std::filesystem::path(n);std::filesystem::create_directories(p.parent_path(),ec);ec.clear();std::ofstream o(p,std::ios::binary|std::ios::trunc);if(!o)continue;o.write(reinterpret_cast<const char*>(data.data()+e.offset),e.size);if(o){++r.file_count;r.output_bytes+=e.size;r.files.push_back(p);}}r.success=core_only?(r.file_count>0):(r.file_count==w.entries.size()&&r.file_count>0&&!r.budget_exhausted);r.output_dir=outdir;if(!r.success)r.error=core_only?"no wxapkg script/config artifacts materialized":"not all wxapkg files were written";return r;}
}
