#include "prts/x86_semantic.hpp"
extern "C" {
#include "Zydis.h"
}
#include <algorithm>
#include <array>
#include <deque>
#include <map>
#include <optional>
#include <set>
#include <unordered_map>
namespace prts { namespace {
std::optional<std::size_t> rvaoff(const PeInfo&pe,std::uint32_t rva,std::size_t n){if(rva<pe.headers_size&&rva<n)return std::size_t(rva);for(const auto&s:pe.sections){auto span=std::max(s.vsize,s.raw_size);if(rva>=s.rva&&std::uint64_t(rva)<std::uint64_t(s.rva)+span){auto delta=std::uint64_t(rva)-s.rva;if(delta>=s.raw_size)return{};auto o=std::uint64_t(s.raw_offset)+delta;if(o<n)return std::size_t(o);}}return{};}
std::uint64_t mix(std::uint64_t h,std::uint64_t v){h^=v+0x9e3779b97f4a7c15ull+(h<<6)+(h>>2);h*=0x100000001b3ull;return h;}
int regclass(ZydisRegister r,ZydisMachineMode mode){if(r==ZYDIS_REGISTER_NONE)return 0;auto large=ZydisRegisterGetLargestEnclosing(mode,r);if(large==ZYDIS_REGISTER_RSP||large==ZYDIS_REGISTER_ESP)return 100;if(large==ZYDIS_REGISTER_RBP||large==ZYDIS_REGISTER_EBP)return 101;if(large==ZYDIS_REGISTER_RIP||large==ZYDIS_REGISTER_EIP)return 102;auto c=ZydisRegisterGetClass(r);switch(c){case ZYDIS_REGCLASS_GPR8:case ZYDIS_REGCLASS_GPR16:case ZYDIS_REGCLASS_GPR32:case ZYDIS_REGCLASS_GPR64:return 1;case ZYDIS_REGCLASS_IP:return 2;case ZYDIS_REGCLASS_FLAGS:return 3;case ZYDIS_REGCLASS_SEGMENT:return 4;case ZYDIS_REGCLASS_XMM:case ZYDIS_REGCLASS_YMM:case ZYDIS_REGCLASS_ZMM:return 5;case ZYDIS_REGCLASS_MMX:case ZYDIS_REGCLASS_X87:return 6;case ZYDIS_REGCLASS_MASK:return 7;default:return 8;}}
std::uint64_t immclass(const ZydisDecodedOperand&o){if(o.imm.is_relative)return 1;auto v=o.imm.value.u;if(v==0)return 2;if(v==1)return 3;if(v<=0xff)return 4;if(v<=0xffff)return 5;if((v&(v-1))==0)return 6;return 7;}
std::uint64_t insn_hash(const ZydisDecodedInstruction&i,const ZydisDecodedOperand*ops,ZydisMachineMode mode){std::uint64_t h=1469598103934665603ull;h=mix(h,static_cast<std::uint64_t>(i.mnemonic));h=mix(h,static_cast<std::uint64_t>(i.meta.category));h=mix(h,i.operand_count_visible);for(std::uint8_t oi=0;oi<i.operand_count_visible;oi++){const auto&o=ops[oi];h=mix(h,o.type);h=mix(h,o.size);switch(o.type){case ZYDIS_OPERAND_TYPE_REGISTER:h=mix(h,regclass(o.reg.value,mode));break;case ZYDIS_OPERAND_TYPE_MEMORY:h=mix(h,10+regclass(o.mem.base,mode));h=mix(h,20+regclass(o.mem.index,mode));h=mix(h,o.mem.scale);h=mix(h,o.mem.disp.has_displacement?(regclass(o.mem.base,mode)==102?31:(o.mem.disp.value>=-128&&o.mem.disp.value<=127?32:33)):30);break;case ZYDIS_OPERAND_TYPE_IMMEDIATE:h=mix(h,40+immclass(o));break;case ZYDIS_OPERAND_TYPE_POINTER:h=mix(h,50);break;default:break;}}return h;}
bool branch_target(const ZydisDecodedInstruction&i,const ZydisDecodedOperand*ops,std::uint64_t ip,std::uint64_t&out){for(std::uint8_t n=0;n<i.operand_count_visible;n++)if(ops[n].type==ZYDIS_OPERAND_TYPE_IMMEDIATE&&ops[n].imm.is_relative){out=ip+i.length+ops[n].imm.value.s;return true;}return false;}
bool terminator(ZydisInstructionCategory c){return c==ZYDIS_CATEGORY_COND_BR||c==ZYDIS_CATEGORY_UNCOND_BR||c==ZYDIS_CATEGORY_RET||c==ZYDIS_CATEGORY_INTERRUPT||c==ZYDIS_CATEGORY_SYSTEM;}
}
SemanticCfg build_x86_cfg(std::span<const std::uint8_t>d,const PeInfo&pe,std::uint32_t entry,std::uint32_t max_span,std::uint32_t max_blocks){SemanticCfg cfg;cfg.entry_rva=entry;if(!pe.valid||(pe.machine!=0x8664&&pe.machine!=0x14c)){cfg.error="x86/x64 PE required";return cfg;}auto entryoff=rvaoff(pe,entry,d.size());if(!entryoff){cfg.error="entry RVA cannot map to raw bytes";return cfg;}auto mode=pe.pe64?ZYDIS_MACHINE_MODE_LONG_64:ZYDIS_MACHINE_MODE_LEGACY_32;auto width=pe.pe64?ZYDIS_STACK_WIDTH_64:ZYDIS_STACK_WIDTH_32;ZydisDecoder decoder;if(!ZYAN_SUCCESS(ZydisDecoderInit(&decoder,mode,width))){cfg.error="ZydisDecoderInit failed";return cfg;}std::deque<std::uint32_t>todo;std::set<std::uint32_t>queued,done;todo.push_back(entry);queued.insert(entry);auto lo=entry>max_span?entry-max_span:0u;auto hi=entry+max_span;while(!todo.empty()&&cfg.blocks.size()<max_blocks){auto start=todo.front();todo.pop_front();if(done.count(start)||start<lo||start>hi)continue;done.insert(start);SemanticBlock b;b.rva=start;b.address=pe.image_base+start;std::uint32_t cur=start;std::uint64_t bh=1469598103934665603ull;for(std::uint32_t ins=0;ins<4096;ins++){auto off=rvaoff(pe,cur,d.size());if(!off||*off>=d.size())break;ZydisDecodedInstruction zi{};ZydisDecodedOperand ops[ZYDIS_MAX_OPERAND_COUNT]{};if(!ZYAN_SUCCESS(ZydisDecoderDecodeFull(&decoder,d.data()+*off,d.size()-*off,&zi,ops))||!zi.length)break;auto ih=insn_hash(zi,ops,mode);b.instruction_hashes.push_back(ih);bh=mix(bh,ih);b.instruction_count++;auto next=cur+zi.length;auto cat=zi.meta.category;if(cat==ZYDIS_CATEGORY_CALL){std::uint64_t target=0;if(branch_target(zi,ops,pe.image_base+cur,target)&&target>=pe.image_base){auto tr=target-pe.image_base;if(tr>=lo&&tr<=hi&&rvaoff(pe,static_cast<std::uint32_t>(tr),d.size()))if(queued.insert(static_cast<std::uint32_t>(tr)).second)todo.push_back(static_cast<std::uint32_t>(tr));}}if(cat==ZYDIS_CATEGORY_COND_BR||cat==ZYDIS_CATEGORY_UNCOND_BR){std::uint64_t target=0;if(branch_target(zi,ops,pe.image_base+cur,target)&&target>=pe.image_base){auto tr=target-pe.image_base;if(tr>=lo&&tr<=hi&&rvaoff(pe,static_cast<std::uint32_t>(tr),d.size()))if(queued.insert(static_cast<std::uint32_t>(tr)).second)todo.push_back(static_cast<std::uint32_t>(tr));}if(cat==ZYDIS_CATEGORY_COND_BR&&next>=lo&&next<=hi&&queued.insert(next).second)todo.push_back(next);cur=next;break;}cur=next;if(terminator(cat))break;if(cur<lo||cur>hi)break;}if(!b.instruction_count)continue;b.size=cur-start;b.hash=bh;cfg.blocks.push_back(std::move(b));}
    std::sort(cfg.blocks.begin(),cfg.blocks.end(),[](const auto&a,const auto&b){return a.rva<b.rva;});cfg.valid=!cfg.blocks.empty();if(!cfg.valid)cfg.error="no reachable normalized basic blocks decoded";return cfg;}
SemanticDiff compare_semantic_cfg(const SemanticCfg&t,const std::vector<std::uint64_t>&refs){SemanticDiff d;d.reference_blocks=static_cast<std::uint32_t>(refs.size());d.target_blocks=static_cast<std::uint32_t>(t.blocks.size());std::unordered_map<std::uint64_t,int> counts;for(auto h:refs)counts[h]++;for(const auto&b:t.blocks){auto it=counts.find(b.hash);if(it!=counts.end()&&it->second>0){--it->second;++d.matched_blocks;}else d.changed_ranges.push_back(rva_range(b.rva,b.size,"normalized basic block not found in selected reference",CoordinateBasis::CURRENT_INPUT_IMAGE));}auto denom=std::max<std::uint32_t>(1,std::max(d.reference_blocks,d.target_blocks));d.block_similarity=double(d.matched_blocks)/denom;return d;}
std::uint64_t semantic_cfg_digest(const SemanticCfg&c){std::uint64_t h=1469598103934665603ull;for(const auto&b:c.blocks)h=mix(h,b.hash);return h;}
std::vector<DirectControlRef> find_direct_control_refs(std::span<const std::uint8_t>d,const PeInfo&pe,const std::vector<RangeRef>&targets,std::size_t max_refs){
    std::vector<DirectControlRef> out;if(!pe.valid||(pe.machine!=0x8664&&pe.machine!=0x14c)||targets.empty())return out;
    auto in_target=[&](std::uint32_t rva){for(const auto&r:targets)if(rva>=r.offset&&std::uint64_t(rva)<r.offset+r.size)return true;return false;};
    auto mode=pe.pe64?ZYDIS_MACHINE_MODE_LONG_64:ZYDIS_MACHINE_MODE_LEGACY_32;auto width=pe.pe64?ZYDIS_STACK_WIDTH_64:ZYDIS_STACK_WIDTH_32;ZydisDecoder decoder;if(!ZYAN_SUCCESS(ZydisDecoderInit(&decoder,mode,width)))return out;
    std::vector<std::pair<std::uint32_t,std::uint32_t>> funcs;
    if(pe.pe64&&pe.exception.present&&pe.exception.size>=12){auto eo=rvaoff(pe,pe.exception.rva,d.size());if(eo){auto n=std::min<std::uint64_t>(pe.exception.size/12,(d.size()-*eo)/12);funcs.reserve(static_cast<std::size_t>(n));for(std::uint64_t i=0;i<n;i++){auto p=*eo+static_cast<std::size_t>(i*12);auto b=std::uint32_t(d[p])|(std::uint32_t(d[p+1])<<8)|(std::uint32_t(d[p+2])<<16)|(std::uint32_t(d[p+3])<<24);auto e=std::uint32_t(d[p+4])|(std::uint32_t(d[p+5])<<8)|(std::uint32_t(d[p+6])<<16)|(std::uint32_t(d[p+7])<<24);if(b<e&&rvaoff(pe,b,d.size()))funcs.emplace_back(b,e);}}}
    if(funcs.empty()){for(const auto&s:pe.sections)if(s.characteristics&0x20000000)funcs.emplace_back(s.rva,s.rva+std::min(s.vsize,s.raw_size));}
    std::set<std::pair<std::uint32_t,std::uint32_t>> seen;
    for(auto [begin,end]:funcs){if(out.size()>=max_refs)break;std::uint32_t cur=begin;while(cur<end&&out.size()<max_refs){auto off=rvaoff(pe,cur,d.size());if(!off||*off>=d.size())break;ZydisDecodedInstruction zi{};ZydisDecodedOperand ops[ZYDIS_MAX_OPERAND_COUNT]{};if(!ZYAN_SUCCESS(ZydisDecoderDecodeFull(&decoder,d.data()+*off,std::min<std::size_t>(d.size()-*off,end-cur),&zi,ops))||!zi.length){++cur;continue;}auto cat=zi.meta.category;if((cat==ZYDIS_CATEGORY_CALL||cat==ZYDIS_CATEGORY_COND_BR||cat==ZYDIS_CATEGORY_UNCOND_BR)&&!in_target(cur)){std::uint64_t tv=0;if(branch_target(zi,ops,pe.image_base+cur,tv)&&tv>=pe.image_base&&tv-pe.image_base<=0xffffffffull){auto tr=static_cast<std::uint32_t>(tv-pe.image_base);if(in_target(tr)&&seen.insert({cur,tr}).second){std::string kind=cat==ZYDIS_CATEGORY_CALL?"call":(cat==ZYDIS_CATEGORY_COND_BR?"jcc":"jmp");out.push_back({cur,tr,zi.length,std::move(kind)});}}}cur+=zi.length;}}
    return out;
}

}
